### ISSUE TITLE
Proxy server support

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#10]

**Comment by robsonpeixoto** [comment]
That is a good way to define proxy
http proxy: http://docs.python-requests.org/en/master/user/advanced/#proxies
socks5 proxy: http://docs.python-requests.org/en/master/user/advanced/#socks

**Comment by omainegra** [comment]
Anybody working on this? I can take it

**Comment by adamw** [comment]
@omainegra go ahead :)

**Comment by adamw** [comment]
any luck with that issue maybe? :)

**Comment by omainegra** [comment]
@adamw Still working on this, sorry for the delay but I got hit by Irma and electricity and internet just came back.

**Comment by adamw** [comment]
@omainegra sorry to hear that, hope that you & your family is fine! no hurry with the code, just checking :)

**Comment by atais** [comment]
I would really like to see that working 👍

**Comment by adamw** [comment]
@omainegra hey, is everything fine? we didn't hear from you for a while

**Comment by adamw** [comment]
@omainegra I hope you are fine, for now I implemented proxy support as an option passed to the backend when creating it. Hope to hear from you in the future :)

**Comment by adamw** [comment]
Released in 0.0.17

**Comment by atais** [comment]
How can I use it with `Monix` Backend?

**Comment by adamw** [comment]
For example:

```
implicit val backend = AsyncHttpClientMonixBackend(
  options = SttpBackendOptions.httpProxy("some.host", 8080))

sttp.get(uri"...").send()
```

Sure, reading the default java proxy parameters is an option - though I don't like this style of "global" configuration. Maybe you'd like to attempt making a PR? :)

**Comment by atais** [comment]
> Maybe you'd like to attempt making a PR? :)

I sure will try 👍
