### ISSUE TITLE
Should the zio-telemetry backends absorb the extra dependency?

### ISSUE THREAD

**Issue by thiloplanz** [softwaremill/sttp#1005]
I have a question about the zio-telemetry backend.

As it stands, it wraps an existing backend that works on `Task` into an enhanced one that does telemetry but then no longer works with `Task` (it exposes the extra dependency on `Tracing`.

> The yielded effects are of type `RIO[OpenTracing, *]`

This means that you cannot use this backend as a drop-in replacement for all your code that needed a `SttpClient` (i.e. a `Task`-based backend) and everything has to be refactored to deal with the added dependency.

Would it be possible (or a good idea) to have the wrapped backend absorb the dependency (by taking it in at construction time), so that this gets hidden from users?

**Comment by adamw** [comment]
This sounds reasonable :) That's how I would do this normally, but maybe the "ZIO-way" is different.

**Comment by thiloplanz** [comment]
@duxet Thoughts on this? If there are no objections, I can prepare a PR.
