### ISSUE TITLE
sbt netty eviction warning

### ISSUE THREAD

**Issue by jCalamari** [softwaremill/sttp#101]
```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* io.netty:netty-handler:4.1.22.Final is selected over 4.1.13.Final
[warn] 	    +- org.asynchttpclient:async-http-client:2.4.4        (depends on 4.1.22.Final)
[warn] 	    +- com.typesafe.netty:netty-reactive-streams:2.0.0    (depends on 4.1.13.Final)
[warn] Run 'evicted' to see detailed eviction warnings
```

![screen shot 2018-06-01 at 10 13 15](https://user-images.githubusercontent.com/9678999/40832990-88f21c62-6584-11e8-8fd2-02dfb496310a.png)

**Comment by adamw** [comment]
But isn't that a mismatch pulled in by async-http-client? Here's a searchable tree of depedencies for easier browsing: https://app.updateimpact.com/treeof/com.softwaremill.sttp/async-http-client-backend_2.11/1.2.0-RC2

**Comment by perotom** [comment]
Got the same issue.

**Comment by adamw** [comment]
Probably out of date :)
