### ISSUE TITLE
Parsing Http Response Json to Object Class

### ISSUE THREAD

**Issue by hanangger** [softwaremill/sttp#1011]
I've been reading the documentation for days and still don't seems to figure out how to solve this problem

It's a Simple common usecase

package scala

import sttp.client3._

import com.google.gson.Gson //Gjson to direct 
convert entity to json string

object HttpRequests extends App {
 //Dummy Post Http Request
 final case class RequestBody(val title: String = "foo", val body: String = "bar", val userId: Int = 1)
 final case class ResponseBody(val title: String = "foo", val body: String = "bar", val userId: Int = 1, val id: Int = 1)

 def defaultResponseString: ResponseAs[Either[String, String], Any] = ???
 val request = basicRequest
 // send the body as form data (x-www-form-urlencoded)
 .body(new Gson().toJson(dummyBody).getBytes())
 // use an optional parameter in the URI
 .post(uri"https://jsonplaceholder.typicode.com/posts")
 .response(asJson[ResponseBody]) // Returned an Error
 val backend = HttpURLConnectionBackend()
 val response = request.send(backend)
 println(response)

above codes are the last thing I tried and still return an Error.

We need SOLID Documentation Example how to solve this.

**Comment by adamw** [comment]
Here's a full example on how to parse & serialise an object to json: https://sttp.softwaremill.com/en/latest/examples.html#get-and-parse-json-using-the-akka-http-backend-and-json4s

However, this uses the json4s library, not gson. If you want to use gson, you'll need to write an `asJson` method which uses it yourself. 

Also, you don't mention what is exactly the error that you are getting, what are the sttp dependencies that you add an in which versions?

**Comment by hanangger** [comment]
Thanks for the answer..

I still don't get correct understanding on `asJson` response handler implementation.

the thing is I avoid to use any additional third party library if it's possible

I tried following code 


`
package scala

import sttp.client3._

import com.google.gson.Gson //Gjson to direct convert entity to json string

object HttpRequests extends App {

	//Dummy Post Http Request
	final case class RequestBody(val title: String = "foo", val body: String = "bar", val userId: Int = 1)
	/*
		Softwaremill Sttp . HTTP Request
		https://github.com/softwaremill/sttp
	*/

	/**
		To integrate with a third-party JSON library, and always parse the response as a json (regardless of the status code):
	**/

	type JsonError
	final case class ResponseBody(val title: String = "foo", val body: String = "bar", val userId: Int = 1, val id: Int = 1) // Parse json response body to this class object.

	val dummyBody = RequestBody()
	def parseJson(json: String): Either[JsonError, ResponseBody] = ???
	val asJson: ResponseAs[Either[JsonError, JsonAST], Any] = asStringAlways.map(parseJson)

	val request = basicRequest
	// send the body as form data (x-www-form-urlencoded)
	.body(new Gson().toJson(dummyBody).getBytes())
	// use an optional parameter in the URI
	.post(uri"https://jsonplaceholder.typicode.com/posts")
	.response(asJson)

	val backend = HttpURLConnectionBackend()
	val response = request.send(backend)

	println(response)

}`

and still get these errors :

`JsonError is already defined as type JsonError
[error]         type JsonError
[error]              ^
[error] C:\scala_pro\rest-scala\src\main\scala\RestAPI\HttpRequest.scala:27:43: not found: type JsonAST
[error]         val asJson: ResponseAs[Either[JsonError, JsonAST], Any] = asStringAlways.map(parseJson)
[error]                                                  ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 15 s, completed Jun 14, 2021, 8:45:34 AM
sbt:HelloWorld> run
[info] compiling 1 Scala source to C:\scala_pro\rest-scala\target\scala-2.12\classes ...
[error] C:\scala_pro\rest-scala\src\main\scala\RestAPI\HttpRequest.scala:23:38: not found: type JsonError
[error]         def parseJson(json: String): Either[JsonError, ResponseBody] = ???
[error]                                             ^
[error] C:\scala_pro\rest-scala\src\main\scala\RestAPI\HttpRequest.scala:24:32: not found: type JsonError
[error]         val asJson: ResponseAs[Either[JsonError, RequestBody], Any] = asStringAlways.map(parseJson)
[error]                                       ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Jun 14, 2021, 8:46:14 AM
sbt:HelloWorld> run
[info] compiling 1 Scala source to C:\scala_pro\rest-scala\target\scala-2.12\classes ...
[error] C:\scala_pro\rest-scala\src\main\scala\RestAPI\HttpRequest.scala:25:43: not found: type JsonAST
[error]         val asJson: ResponseAs[Either[JsonError, JsonAST], Any] = asStringAlways.map(parseJson)`

**Comment by hanangger** [comment]
ended up using json4s library

this one works. ;)

`final case class ResponseBody(title: String, body: String, userId: Int , id: Int)
	
	val dummyBody = RequestBody()
	implicit val serialization = org.json4s.native.Serialization
	implicit val formats = org.json4s.DefaultFormats

	try {


		val request = basicRequest
		.contentType("application/json")
		.contentLength(128) // Add Header content-type to adjust byte response
		// send the body as form data (x-www-form-urlencoded)
		.body(s"${new Gson().toJson(dummyBody)}")
		// use an optional parameter in the URI
		.post(uri"https://jsonplaceholder.typicode.com/posts")
		.response(asJson[ResponseBody])

		val backend: SttpBackend[Identity, Any] = HttpURLConnectionBackend()
		val response: Response[Either[ResponseException[String, Exception], ResponseBody]] = request.send(backend)

		println(response.code)
		if(response.code == StatusCode.Created) println(response.body.right.get) // get response body Either[Left, Right]
		else println("Error making request!")`
