### ISSUE TITLE
plus is encoded as '%20' in the path component

### ISSUE THREAD

**Issue by yurique** [softwaremill/sttp#102]
```
scala> import com.softwaremill.sttp._
import com.softwaremill.sttp._

scala> uri"https://test.nowhere/A+B"
res0: com.softwaremill.sttp.Uri = https://test.nowhere/A%20B

// expected:                      https://test.nowhere/A+B
//                                    with literal '+'
```

And it causes problems with some servers: the server finds a resource when there's a literal '+' in the path, and fails with 404 when it's encoded.

Found this: https://stackoverflow.com/questions/1005676/urls-and-plus-signs

> * Percent encoding in the path section of a URL is expected to be decoded, but
> * any + characters in the path component is expected to be treated literally.
> 
> To be explicit: + is only a special character in the query component.

**Comment by yurique** [comment]
// browsers don't replace the literal '+' in the path component

**Comment by adamw** [comment]
Please see 1.2.0-RC3
