### ISSUE TITLE
"return" statement in sttp/model/UriInterpolator.scala

### ISSUE THREAD

**Issue by domdorn** [softwaremill/sttp#1038]
there is a return statement in 
sttp/model/UriInterpolator.scala method splitWithEscape

return statements in scala are implemented with exceptions and should be avoided.

**Comment by adamw** [comment]
Indeed, that's a non-local return. Thanks for spotting this :)

See https://github.com/softwaremill/sttp-model/pull/102

**Comment by adamw** [comment]
Released in sttp model 1.4.8
