### ISSUE TITLE
Add OOTB support for request/response logging

### ISSUE THREAD

**Issue by PeterPerhac** [softwaremill/sttp#106]
with the [standalone play-ws client](https://github.com/playframework/play-ws) one can do `.withRequestFilter(...)` and plug in an OOTB (out-of-the-box) provided `AhcCurlRequestLogger` to see each individual request logged in cURL format.

Similar sort of functionality could be added to the core **sttp** library, and would be a useful addition.

**Comment by asarkar** [comment]
@PeterPerhac Came here looking for the exact same thing. How are you working around this?

**Comment by adamw** [comment]
@asarkar maybe this will work: https://sttp.readthedocs.io/en/latest/backends/custom.html#example-logging-backend-wrapper ?

**Comment by adamw** [comment]
Done in 2.0.0-RC6: https://sttp.readthedocs.io/en/latest/backends/wrappers/slf4j.html
