### ISSUE TITLE
URL percent encoding

### ISSUE THREAD

**Issue by kink80** [softwaremill/sttp#1064]
I'd like to get someone's insight on whether the URI parsing is implemented correctly. 

- RAW string to be parsed into a URL`https://example.com/files/Berts%2BFile%2Bv3%2B%281%29.pdf?token=1234`
- let's assume the token parameter had been generated to match the path part of the URL
- executing this request using sttp fails, surprisingly the URL created by `uri"https://example.com/files/Berts%2BFile%2Bv3%2B%281%29.pdf&token=1234"` gets rendered as `https://example.com/files/Berts+File+v3+(1).pdf&token=1234`, 
- executing this request using plain Java client (URL.openConnection)  succeeds, the string representation of the URL is `https://example.com/files/Berts%2BFile%2Bv3%2B%281%29.pdf&token=1234`when created by `new URL("https://example.com/files/Berts%2BFile%2Bv3%2B%281%29.pdf&token=1234")`

This is a simplified scenario, the real one involves a series of 302 redirections where one of the location headers contains a similar URL pattern as above.

**Comment by adamw** [comment]
I believe this is fine. According to RFC3986, the allowed characters in a path include `+`, `(` and `)` (see https://datatracker.ietf.org/doc/html/rfc3986#section-3.3 and in sttp's code: https://github.com/softwaremill/sttp-model/blob/master/core/src/main/scala/sttp/model/internal/Rfc3986.scala#L12)

The encoding for path segments (and any other segments) can be changed, but it's not that straightforward, as there aren't any helper functions for that (like `.map` over a path), so you need to do it manually:

```scala
import sttp.model.Uri.UriContext
import sttp.model.internal.Rfc3986

object Test extends App {
  val u = uri"https://example.com/files/Berts%2BFile%2Bv3%2B%281%29.pdf&token=1234"
  println(u)
  println(
    u.copy(pathSegments =
      Uri.AbsolutePath(
        u.pathSegments.segments.map(_.copy(encoding = Rfc3986.encode(Rfc3986.PathSegment - '+' - '(' - ')'))).toList
      )
    )
  )
  println("https://example.com/files/Berts%2BFile%2Bv3%2B%281%29.pdf&token=1234")
}

```

**Comment by kink80** [comment]
Thanks @adamw for confirming, that implies that both urls should be equivalent and treated as such (as per https://datatracker.ietf.org/doc/html/rfc3986#section-2.1).
