### ISSUE TITLE
Swagger codegen plugin for sttp

### ISSUE THREAD

**Issue by szimano** [softwaremill/sttp#107]
Would be nice to be able to automatically generate rest client which uses STTP from swagger docs using https://swagger.io/tools/swagger-codegen/

Contribution to https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages

**Comment by adamw** [comment]
This is done in openapi-generators and documented in https://sttp.softwaremill.com/en/latest/openapi.html
