### ISSUE TITLE
Uri.toString has stronger checks than uri interpolation

### ISSUE THREAD

**Issue by InversionSpaces** [softwaremill/sttp#1086]
Next expression does not throw:
```scala
val test = uri"http://sub..domain.com"
```
However, next expression does throw:
```scala
test.toString
// java.lang.IllegalArgumentException: Empty label is not a legal name
```
Expected behavior is that `Uri` constructed with interpolation without errors is correct and could be safely used.

**Comment by adamw** [comment]
Fixed here: https://github.com/softwaremill/sttp-model/pull/112
