### ISSUE TITLE
Convert docs to markdown

### ISSUE THREAD

**Issue by jsw** [softwaremill/sttp#111]
@adamw Would you consider converting the docs to markdown? I think setting up python/sphinx and learning reStructuredText is too high a barrier for external contributors. Everyone already knows markdown, and it would be straightforward to host the docs directly in the repo or get a little more fancy with GitHub Pages. I'd be happy to help. It looks like there's only 1631 lines of rst (including whitespace). Are there significant benefits to using readthedocs?

**Comment by adamw** [comment]
Well the benefit is that it "just works" and produces nice, browseable docs :) Don't ghpages require a separate branch? I really like that the docs live next to the code.

**Comment by jsw** [comment]
You can use master branch 

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

**Comment by adamw** [comment]
Ah, well if the docs get automatically built, deployed, and they look nice, with roughly the same structure as now (menu on the left, content on the right), I'm fine with either :)

**Comment by llfrometa89** [comment]
@adamw  Would you consider creating a microsite?
`sbt-microsites`: https://47deg.github.io/sbt-microsites/docs/ with (`mdoc`: https://scalameta.org/mdoc/) or (`tut`:  https://github.com/tpolecat/tut)
I like that the docs live next to the code too.

**Comment by adamw** [comment]
mdoc/tut definitely. Not sure about microsite, I like the readthedocs workflow, but I guess there's not that much difference in both approaches.

**Comment by adamw** [comment]
Docs converted to .md, still using readthedocs :)

**Comment by ghostbuster91** [comment]
After switching to mdoc we would gain code correctness check, so I think that it might be worth to reconsider it.
