### ISSUE TITLE
Example configuration for HttpUrlConnectionBackend and SSL

### ISSUE THREAD

**Issue by bblaine** [softwaremill/sttp#114]
I'm trying to configure a `HostnameVerifier` for `HttpUrlConnectionBackend` but can't get it to work. Issue is setting this parameter `customizeConnection: HttpURLConnection => Unit` properly.

A simple example on this page would be helpful.
https://sttp.readthedocs.io/en/latest/conf/ssl.html

**Comment by adamw** [comment]
Not sure what you are trying to achieve? But maybe the following will help:
https://stackoverflow.com/questions/1201048/allowing-java-to-use-an-untrusted-certificate-for-ssl-https-connection
https://stackoverflow.com/questions/8339200/how-can-i-use-certificate-authentication-with-httpsurlconnection

**Comment by ameet123** [comment]
there may be 2 ways to do it
1. set system properties if you have appropriate truststore
System.setProperty("javax.net.ssl.trustStore", "your/path/to/trusted/cacerts")
2. invoke the code mentioned in the above SO question, somewhere inside your class before the invocation of sttp request/response.
I made one based on the above link, 

    ```
  def disableSSLVerification(): Unit = {
    val trustAllCerts = Array[TrustManager](new X509TrustManager() {
      def getAcceptedIssuers: Array[X509Certificate] = Array[X509Certificate]()

      override def checkServerTrusted(x509Certificates: Array[cert.X509Certificate], s: String): Unit = ()

      override def checkClientTrusted(x509Certificates: Array[cert.X509Certificate], s: String): Unit = ()
    })

    var sc: SSLContext = null
    try {
      sc = SSLContext.getInstance("TLS")
      sc.init(Array[KeyManager](), trustAllCerts, new SecureRandom())
    } catch {
      case e: KeyManagementException =>
        e.printStackTrace()
      case e: NoSuchAlgorithmException =>
        e.printStackTrace()
    }
    HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory)
    val allHostsValid = new HostnameVerifier {
      override def verify(s: String, sslSession: SSLSession): Boolean = true
    }
    HttpsURLConnection.setDefaultHostnameVerifier(allHostsValid)
  }
```
and then just call this
disableSSLVerification()
```

**Comment by atamboli** [comment]
I have a certificate in pem format. How can i use that to configure HttpUrlConnectionBackend and SSL?
An example would really help. 

Thank you.

**Comment by adamw** [comment]
Documentation added: https://sttp.softwaremill.com/en/latest/conf/ssl.html
