### ISSUE TITLE
json circe docs missing response wrapper?

### ISSUE THREAD

**Issue by dsilvasc** [softwaremill/sttp#115]
Hi,

In the docs at http://sttp.readthedocs.io/en/latest/json.html#circe this example says that `send()` returns an `Either[io.circe.Error, MyResponse]` but we're seeing it actually return a `Response[Either[io.circe.Error, MyResponse]]`.

```scala
val response: Either[io.circe.Error, MyResponse] =
  sttp
    .post(uri"...")
    .body(requestPayload)
    .response(asJson[MyResponse])
    .send()
```

**Comment by adamw** [comment]
@dsilvasc Yes that's of course a typo - maybe you'd like to submit a PR to fix this?

**Comment by dsilvasc** [comment]
https://github.com/softwaremill/sttp/pull/116

**Comment by adamw** [comment]
Thanks!
