### ISSUE TITLE
Node.js compatibility

### ISSUE THREAD

**Issue by mukel** [softwaremill/sttp#117]
`FetchBackend` works great on browsers, it's a very nice feature.
I can't make it work on Node.js due to dependency on `AbortController`. I'm using [mill](https://github.com/lihaoyi/mill) which ATM doesn't have anything like `scalajs-bundler`, but SBT instructions (if any) are also very welcome.
Any hint on how to run on Node.js ? Maybe I'm missing some magic SBT polyfill dependency.
Does it requires another Node.js-specific backend ? (like [hammock](https://github.com/pepegar/hammock) with 2 js backends).

**Comment by adamw** [comment]
Maybe @guymers has an idea? I'm not that familiar with the Scala.JS side :)

**Comment by guymers** [comment]
It doesn't seem possible given node-fetch does not support AbortController yet https://github.com/bitinn/node-fetch/issues/95. I think the best solution would be to add a NodeJS backend (like how RosHTTP has XHR and NodeJS backends). I don't  think it would be that hard to implement, hardest part would be splitting the JS tests into two configs, one which runs the fetch backend against the browser and another that runs the runs the Node backend against Node. I only added a fetch backend as I only need streaming browser suport.

**Comment by kubinio123** [comment]
Issue with `AbortController` has be solved in `node-fetch` module so running `FetchBackend` on Node.js now works.
I updated docs with info how to load `node-fetch` module correctly.

Here is a working code sample:
```
  def main(args: Array[String]): Unit = {

    val g = scalajs.js.Dynamic.global.globalThis

    val nodeFetch = g.require("node-fetch")

    g.fetch = nodeFetch
    g.Headers = nodeFetch.Headers
    g.Request = nodeFetch.Request

    import sttp.client3._

    import JSExecutionContext.Implicits.queue

    val backend = FetchBackend()

    val request = basicRequest.get(uri"https://jsonplaceholder.typicode.com/posts")

    request.send(backend)
      .onComplete(response => {
        println(s"I am completed: $response")
        response.get
      })
  }
```
