### ISSUE TITLE
Error when using json4s

### ISSUE THREAD

**Issue by spacetings** [softwaremill/sttp#119]
Hello, I'm seeing below error when trying to serialize my response using json4s. Not sure what I am doing wrong, any help would be greatly appreciated. 

```
polymorphic expression cannot be instantiated to expected type;
[error]  found   : [R[_]]R[com.softwaremill.sttp.Response[MyResponse]]
[error]  required: com.softwaremill.sttp.Response[MyResponse]
[error]         .send()
```

I am essentially doing the following:
```
import com.softwaremill.sttp._
import com.softwaremill.sttp.json4s._

implicit val backend = HttpURLConnectionBackend()

    case class Payload(stuff: String)
    case class MyResponse(moreStuff: String)
    val requestPayload: Payload = Payload("asdf")
    val response: Response[MyResponse] =
      sttp
        .post(uri"...")
        .body(requestPayload)
        .response(asJson[MyResponse])
        .send()
```

(Apologies if this is not the correct place to request help)

**Comment by spacetings** [comment]
yep that did the trick!

**Comment by spacetings** [comment]
Should the docs be updated?

**Comment by adamw** [comment]
@spacetings That might be a good idea :) Is the explicit type annotation somewhere in the docs? But either way, it could be added as a note, that when using a synchronous backend the inferred type of `send()` is wrapped in `Id` (even though `type Id[X] = X`)
