### ISSUE TITLE
jsoniter-scala support

### ISSUE THREAD

**Issue by borissmidt** [softwaremill/sttp#1246]
I see that you have support for a lot of Json libraries.
Tapir seems to have support for json-iter but sttp does not implement it yet.
It seems it is rather easy to implement a new json implementation so i wouldn't mind giving it a try.

**Comment by adamw** [comment]
Sure, go ahead :)

**Comment by plokhotnyuk** [comment]
Currently jsoniter-scala supports JVM and Scala.JS for 2.11, 2.12, 2.13, and 3 versions of Scala, so it should be easy to integrate it with sttp.

Please prefer parsing and serialization of UTF-8 encoded payload from/to `Array[Byte]`, not `String` for better efficiency.

**Comment by Pask423** [comment]
Implemented in #1248
