### ISSUE TITLE
sttp.shared:zio pulls zio-2 instead of zio-1

### ISSUE THREAD

**Issue by demming** [softwaremill/sttp#1261]
For some reason, the introduction of `"com.softwaremill.sttp.shared" %% "zio" % "1.3.0"` (and 1.3.1) caused pulling in zio-2 instead of zio-1, in particular when used in the concatenation of the following two dependency lists in the same project compiled by Scala 2.13.8.

```scala
val depsServer =
  Seq(
      "com.softwaremill.sttp.tapir" %% "tapir-core" % "0.20.0-M5"
    , "com.softwaremill.sttp.tapir" %% "tapir-zio" % "0.20.0-M5" // exclude("dev.zio", "zio_2.13")
    , "com.softwaremill.sttp.tapir" %% "tapir-zio-http-server" % "0.20.0-M5" // exclude("dev.zio", "zio_2.13")
    // ...
    )

val depsServerVertx =
  Seq(
     "com.softwaremill.sttp.tapir" %% "tapir-vertx-server" % "0.20.0-M5"
   , "com.softwaremill.sttp.shared" %% "zio" % "1.3.0" exclude("dev.zio", "zio_2.13")
   )
```

Apparently, this combination in a single project behaves such that the `sttp.shared:zio` artifact pulls in zio-2 instead of zio-1 --- even when I `exclude` the zio dependency from it. That zio-2 artifact then precedes all zio-1 artifacts in the class path.

If I `exclude` the `dev.zio:zio` dependency from all sttp artifacts and provide it explicitly, everything works as expected, with zio-1. And when I omit the `sttp.shared:zio` artifact everything is fine again. This duality in zio artifacts results in the following scalac exception thrown even for a simple sttp app from the examples: https://github.com/scala/bug/issues/12041#issuecomment-1016695293.

On a side note, the package `"com.softwaremill.sttp.tapir" %% "tapir-zio-http"` is only available for version `"0.19.0-M9"` rather than `"0.20.0-M5"` [in contrast to the docs](https://tapir.softwaremill.com/en/latest/server/ziohttp.html).

**Comment by adamw** [comment]
Yes, since 1.3.0, the `"com.softwaremill.sttp.shared" %% "zio"` depends on zio 2.0, and `"com.softwaremill.sttp.shared" %% "zio1"` on zio1. Same as with cats-effect, the convention is that no-suffix version points to latest, and if we do support previous versions, there's a version suffix.

As for tapir, the docs have a bug (fixed but not yet releaed :) ), the artifact name is `tapir-zio-http-server`: https://github.com/softwaremill/tapir/blob/master/build.sbt#L906

**Comment by demming** [comment]
Oh, I see, wasn't aware of this change. Thanks for pointing this out.

**Comment by adamw** [comment]
I'll put this in the release notes, definitely wasn't clear before :)
