### ISSUE TITLE
Expose Response in PrometheusBackend customization

### ISSUE THREAD

**Issue by Krever** [softwaremill/sttp#1298]
Currently the signature of the `PrometheusBackend.apply` is
```
  def apply[F[_], P](
      delegate: SttpBackend[F, P],
      requestToHistogramNameMapper: Request[_, _] => Option[HistogramCollectorConfig] = (_: Request[_, _]) =>
        Some(HistogramCollectorConfig(DefaultHistogramName)),
      requestToInProgressGaugeNameMapper: Request[_, _] => Option[CollectorConfig] = (_: Request[_, _]) =>
        Some(CollectorConfig(DefaultRequestsInProgressGaugeName)),
      requestToSuccessCounterMapper: Request[_, _] => Option[CollectorConfig] = (_: Request[_, _]) =>
        Some(CollectorConfig(DefaultSuccessCounterName)),
      requestToErrorCounterMapper: Request[_, _] => Option[CollectorConfig] = (_: Request[_, _]) =>
        Some(CollectorConfig(DefaultErrorCounterName)),
      requestToFailureCounterMapper: Request[_, _] => Option[CollectorConfig] = (_: Request[_, _]) =>
        Some(CollectorConfig(DefaultFailureCounterName)),
      requestToSizeSummaryMapper: Request[_, _] => Option[CollectorConfig] = (_: Request[_, _]) =>
        Some(CollectorConfig(DefaultRequestSizeName)),
      responseToSizeSummaryMapper: Response[_] => Option[CollectorConfig] = (_: Response[_]) =>
        Some(CollectorConfig(DefaultResponseSizeName)),
      collectorRegistry: CollectorRegistry = CollectorRegistry.defaultRegistry
  ): SttpBackend[F, P
  ```
  
And so the customization allows you to take data only from requests. It would be useful to have `Response` when available to extract also information from it. 
  
The exact use case I have is to put the response code as a Prometheus label. 

The change itself is rather simple and I could give it a shot but I'm not familiar with the exact compatibility guarantees of sttp. Can we just modify the signatures or do we need to create a separate constructor to keep the back-compat?

**Comment by adamw** [comment]
We have mima enabled only for `core`, but in case of integrations I think it's best to keep backwards compat if possible, just to be nice to people :)

So please give it a shot, if possible - great, if not - we can always do a minor sttp release to mark the breaking change in na integration module (a minor release always draws more attention than a patch one :) )

**Comment by carstenlenz** [comment]
Hi. I used to have custom mappers that add some `request.tags` as labels on the metrics. With this change to  `response` for those 3 metrics (`reponse.request` does not have tags) I have lost the ability to do so :(

I know it's been already changed - but a mapper of `(request, response) => Option[CollectorConfig]` would have / could keep this possibility - there might be more on a request that's interesting.

**Comment by adamw** [comment]
@carstenlenz Ah and the tags aren't available via `response.request`. So we either need to implement https://github.com/softwaremill/sttp/issues/1436 or add the request here. The former is tricky due to binary compat, so let's go with option 2. Maybe you'd like to attempt creating a PR?

**Comment by carstenlenz** [comment]
Hi - thanks for your answer. 
Sorry for my late reply - as these things always happen I went on vacation just the day you answered :)
Yes I could create a PR as I already have an adapted copy of PrometheusBackend in our codebase with these exact changes. But give me a few days as work is always plenty after (long) vacations ;)

**Comment by adamw** [comment]
@carstenlenz Sure, no worries :)
