### ISSUE TITLE
ScalaNative: Unable to download binary files

### ISSUE THREAD

**Issue by darkfrog26** [softwaremill/sttp#131]
When using sttp with ScalaNative, I'm attempting to download a JAR from a URL:

```scala
sttp.get(jar).response(asFile(outputFile)).send().unsafeBody
```
The output of `outputFile` is a 5 byte file.  The output to the console is (which should be another bug as there doesn't seem to be a way to turn it off):

```
Downloading http://repo1.maven.org/maven2/com/outr/jefe-runner_2.12/1.2.4/jefe-runner_2.12-1.2.4.jar...
*   Trying 151.101.48.209...
* TCP_NODELAY set
* Connected to repo1.maven.org (151.101.48.209) port 80 (#0)
> GET /maven2/com/outr/jefe-runner_2.12/1.2.4/jefe-runner_2.12-1.2.4.jar HTTP/1.1
Host: repo1.maven.org
Accept: */*
Accept-Encoding: gzip, deflate

< HTTP/1.1 200 OK
< ETag: "be50aa1ecb13b6ec56baa9f3f0eb6fa3"
< Content-Type: application/java-archive
< Last-Modified: Mon, 23 Apr 2018 18:48:49 GMT
< X-Checksum-MD5: be50aa1ecb13b6ec56baa9f3f0eb6fa3
< X-Checksum-SHA1: 6251244a4a38c1ec1b4ccdb784abf897e27afd63
< Via: 1.1 varnish
< Content-Length: 23591
< Accept-Ranges: bytes
< Date: Tue, 24 Jul 2018 20:27:51 GMT
< Via: 1.1 varnish
< Age: 140
< Connection: keep-alive
< X-Served-By: cache-iad2128-IAD, cache-dfw18645-DFW
< X-Cache: HIT, HIT
< X-Cache-Hits: 1, 1
< X-Timer: S1532464072.507182,VS0,VE1
< 
* Connection #0 to host repo1.maven.org left intact
```

**Comment by adamw** [comment]
@pcejrowski maybe? :)

**Comment by pcejrowski** [comment]
Ack. I will take a look at this tomorrow.

**Comment by darkfrog26** [comment]
Any updates on this?

**Comment by pcejrowski** [comment]
@darkfrog26 I've been working on it, but I cannot get it on. 
My progress is here: https://github.com/pcejrowski/sttp/commit/2b77252128c9d2f3a0119c26df9952f323bfd01f

PS. Verbosity has been fixed here: https://github.com/softwaremill/sttp/pull/136

**Comment by darkfrog26** [comment]
@pcejrowski I appreciate your efforts. I'll take a look and see if there's anything I can contribute, though this is an area where my expertise is incredibly limited.

**Comment by darkfrog26** [comment]
It's almost as if you're not waiting for it to complete the process before terminating the connection.  Is there an asynchronous wait-state you are perhaps not accounting for?

**Comment by pcejrowski** [comment]
I don't think so, but I might be wrong. The execution on the curl's side takes place in `curl.perform` method, which is synchronous. I am reproducing [this](https://curl.haxx.se/libcurl/c/url2file.html) C example.

**Comment by darkfrog26** [comment]
Sorry to pester, but is there any update on this?  If this isn't going to be resolved soon I'll have to contrive a crappy workaround.
