### ISSUE TITLE
missing jsoniter-scala-macros

### ISSUE THREAD

**Issue by Zhen-hao** [softwaremill/sttp#1325]
The [jsoniter example code](https://sttp.softwaremill.com/en/latest/json.html?highlight=jsoniter#jsoniter-scala) won't compile because of 

```
object macros is not a member of package com.github.plokhotnyuk.jsoniter_scala
```

I think the reason is that its scope is `Test` [here](https://github.com/softwaremill/sttp/blob/master/build.sbt#L833)

**Comment by Zhen-hao** [comment]
I tried to use `sttp` in a client project. 

It's not enough to add only
```
"com.softwaremill.sttp.client3"         %% "jsoniter"                        % sttpVersion,
```
to `libraryDependencies`.

Did I miss anything from the documentation? 

Now I have a workaround. Adding the following made it work.

```
 "com.github.plokhotnyuk.jsoniter-scala" %% "jsoniter-scala-macros"           % jsoniterVersion % "provided",
```

Feel free to close this issue if it not a valid one.

**Comment by adamw** [comment]
Ah, I suppose if you want to use macro-based derivation with jsoniter, you need the additional dependency. That's how jsoniter works - probably adding this to the docs would be a good idea. That's however not something we can fix in code.

**Comment by Zhen-hao** [comment]
I see. thanks for the explanation!
