### ISSUE TITLE
Update the OpenAPI generator to generate correct sttp3 requests

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#1358]
There was an PR with an update: https://github.com/OpenAPITools/openapi-generator/pull/11260

However, the generated requests use `Nothing` instead of `Any` as the capability parameter, and api keys aren't added to the generated code.

@mmatloka has more details

**Comment by Pask423** [comment]
Issue with `Nothing` instead of `Any` seemed to be fix and as far as I can tell `Api Keys` works ok. 
Please try at least `v6.2.0` of `openapi-generator`.
