### ISSUE TITLE
Requests with AsyncHttpClientFutureBackend fails on 404 error

### ISSUE THREAD

**Issue by sergeda** [softwaremill/sttp#139]
As understand request shouldn't fail on non-200 error to allow body processing and customization.
But for me requests with AsyncHttpClientFutureBackend fails on 404 error

**Comment by adamw** [comment]
I've just added a testcase for 404 and it passes on all backends - can you check if that's the scenario you are describing, or is it something else?

**Comment by adamw** [comment]
hm `NoSuchElementException` looks suspicious. Can you paste in the whole stack trace, or provide a failing example?

**Comment by sergeda** [comment]
I'm sorry @adamw . It was other block of code that throw that error.
