### ISSUE TITLE
Consider moving the HttpClient backend to core/jvm

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#1401]
This would mean that OOTB sttp's users get a modern, asynchronous, websocket-capable backend, without any other dependencies (an important fact to emphasise in the docs!)

However, this would also require at least Java 11. But maybe it's high time to do that? Would require at least a minor version bump.

We could bundle the monix/zio/cats-effect implementations of the backend together with the `effects` artifacts, to further simplify and lower the entry barrier to using sttp. So e.g. to use the monix backend you would only need the `com.softwaremill.sttp % monix` dependency.

**Comment by dbuschman7** [comment]
Yes please!
