### ISSUE TITLE
`"async-http-client-backend-zio" % "3.5.1"` pulls in zio 2.0 release candidate

### ISSUE THREAD

**Issue by domdorn** [softwaremill/sttp#1406]
the async-http-client-backend-zio uses a zio-2.0 implementation of the `zio-interop-reactivestreams` which in turn pulls in the current RC of zio 2.0
This is unwanted and unexpected behavior
![grafik](https://user-images.githubusercontent.com/100349/163233103-79db1762-3c95-484b-9718-502533652e9a.png)

please release a new version that uses the stable version
```
libraryDependencies += "dev.zio" %% "zio-interop-reactivestreams" % "1.3.9"
```
instead.

**Comment by Pask423** [comment]
Hi @domdorn 

Such version is already released under `"com.softwaremill.sttp.client3" %% "async-http-client-backend-zio1" % "3.5.1"`

![image](https://user-images.githubusercontent.com/59844835/163344713-d02ba66b-a8ad-40d0-8e03-f85e2b251dec.png)

**Comment by domdorn** [comment]
oh, awesome! didn't know that existed and sbt dependencyUpdates just gave the normal one.. THANKS!

**Comment by Pask423** [comment]
Not a problem, glad I could help
