### ISSUE TITLE
upgrade to cats-effect 1.0.0-RC3?

### ISSUE THREAD

**Issue by SethTisue** [softwaremill/sttp#142]
over in the Scala community build I'm trying to get all the Typelevel ducks in a row at https://github.com/scala/community-builds/pull/775, having sttp do this upgrade would help with that

**Comment by adamw** [comment]
Updated, compiles & tests pass :)

**Comment by SethTisue** [comment]
thanks! the ducks aren't all quite aligned yet, not sure the cause yet, working on it at https://github.com/scala/community-builds/pull/783, I'll come back here if it turns out there's something actionable here in this repo
