### ISSUE TITLE
sttp with ZIO 2.0.0-RC6

### ISSUE THREAD

**Issue by otobrglez** [softwaremill/sttp#1433]
Hey, good people of sttp! 👋 

I'm trying the 2.x release of ZIO (`2.0.0-RC6` to be precise) and I would like to use sttp (httpclient-backend-zio or async-http-client-backend-zio) with it. I gave it a shot with `3.5.2` version of sttp. However, it looks like the ZIO's way of defining dependencies and layers have changed since ZIO 1.x and it breaks in 2.x.

This is my attempt

```scala
// la-la-la
 def app: ZIO[SttpClient, Throwable, Unit] =
    for
      _ <- ZIO.logInfo("Booting...")
      _ <- ZIO.debug("Done...")
    yield ()

  def run: ZIO[Any, Throwable, Unit] = app.provideLayer(AsyncHttpClientZioBackend.layer())
```

And the explosion:

```
root timestamp=2022-05-06T09:17:28.342741Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-6" java.lang.NoSuchMethodError: 'zio.ZLayer zio.ZLayer$.fromZIOEnvironment(zio.ZIO, java.lang.Object)'
root    at sttp.client3.impl.zio.SttpClientStubbingBase.$init$(SttpClientStubbingBase.scala:12)
root    at sttp.client3.asynchttpclient.zio.package$SttpClientStubbing$.<clinit>(package.scala:40)
root    at sttp.client3.asynchttpclient.zio.AsyncHttpClientZioBackend$.<clinit>(AsyncHttpClientZioBackend.scala:254)
root    at com.pinkstack.loglog.HelloApp$.run$$anonfun$1(HelloApp.scala:48)
root    at zio.ZIO.provideLayer$$anonfun$3(ZIO.scala:1215)
root    at zio.ZIO$ReleaseExit.apply$$anonfun$3$$anonfun$1$$anonfun$1$$anonfun$1(ZIO.scala:4706)
root    at zio.ZIO$.suspendSucceed$$anonfun$1(ZIO.scala:4254)
root    at zio.internal.FiberContext.runUntil(FiberContext.scala:284)
root    at zio.internal.FiberContext.run(FiberContext.scala:111)
root    at zio.Runtime.unsafeRunWithRefs(Runtime.scala:400)
root    at zio.Runtime.unsafeRunWith(Runtime.scala:355)
root    at zio.Runtime.unsafeRunAsyncCancelable(Runtime.scala:308)
root    at zio.Runtime.unsafeRunAsyncCancelable$(Runtime.scala:28)
root    at zio.Runtime$$anon$7.unsafeRunAsyncCancelable(Runtime.scala:425)
root    at zio.Runtime.run$$anonfun$1$$anonfun$1(Runtime.scala:78)
root    at zio.internal.FiberContext.runUntil(FiberContext.scala:316)
root    at zio.internal.FiberContext.run(FiberContext.scala:111)
root    at zio.internal.ZScheduler$$anon$3.run(ZScheduler.scala:415)
root    at zio.internal.FiberContext.runUntil.macro(FiberContext.scala:518)
root    at com.pinkstack.loglog.HelloApp$.run.macro(HelloApp.scala:48)"
root ... finished with exit code 1
```

Can u tell me if this is an easy fix or a big thing; if it's easy I might try to fix it myself if you can provide me with some pointers and guidance. 😊

Thank you for all the effort and have a nice and lovely day!

- Oto

**Comment by adamw** [comment]
Are you using the same ZIO-RC version that sttp depends on?

**Comment by Pask423** [comment]
Try with 3.6.0 or 3.6.1 as we added RC6 support in 3.6.0

**Comment by vlushn** [comment]
> Try with 3.6.0 or 3.6.1 as we added RC6 support in 3.6.0

It's already out?

**Comment by Pask423** [comment]
3.6.0 was just released, 3.6.1 will be out in few minutes

**Comment by johnduffell** [comment]
I am having the same issue (as the signature of fromZIOEnvironment has changed in zio 2 RC6 - the ZIO parameter is now lazy so the JVM can't find it any more.)

I saw that 3.6.1 should solve the issue.

I am using the latest httpclient-backend-zio

`"com.softwaremill.sttp.client3" %% "httpclient-backend-zio" % "3.5.2"`
as I can't see a 3.6.1 released yet.

Even if I override the dependencies to force a later version of the underlying library:
```
    "com.softwaremill.sttp.client3" %% "httpclient-backend-zio" % "3.5.2"  exclude("org.scala-lang.modules","scala-collection-compat_2.13"),
    "com.softwaremill.sttp.client3" %% "zio" % "3.6.1"  exclude("org.scala-lang.modules","scala-collection-compat_2.13"),
```
I get other issues due to compatibility.

Please could you check and see if a 3.6.1 can be released for the `httpclient-backend-zio`?

I would appreciate this if you have time to resolve this - Thanks!

**Comment by Pask423** [comment]
As for `3.6.1` httpclient based backend was move to core.
The artefact `httpclient-backend-zio` no longer exists since then.
Here you can find description on how to use `httpClientZioBackend`: https://sttp.softwaremill.com/en/latest/backends/zio.html

**Comment by Pask423** [comment]
Happy to help
