### ISSUE TITLE
Cookies are not passed to the redirect calls

### ISSUE THREAD

**Issue by pylesage** [softwaremill/sttp#1434]
In case you get a redirect , the cookie recieved from the first result should be passed the following ones.
By now they are getting lost. 

The usecase I encountered: 
  * POST to a login api , the api response provides a cookie
  * following the redirect issues a second call (get or post based on config) but the recieved cookie is not passed to this second call.
  * the redirect call recieves a new cookie which is not valid anymore

A possible workaround is to read the cookies from the first call issued and passing it to the next ones manually.  

I suspect we should copy the cookies recieved from the response to the next request here:
https://github.com/softwaremill/sttp/blob/7e76fb5d83cae09b52e72e18195c442f65a881c6/core/src/main/scala/sttp/client3/FollowRedirectsBackend.scala#L73

**Comment by adamw** [comment]
Automatically propagating cookies can be a security issue, hence it's not enable by default. You can change that behavior by changing the `sensitiveHeaders` parameters of `FollowRedirectsBackend`, and removing `Cookie` (and possibly `SetCookie`) from the set. So sth along the lines should work:

```scala
val backend = new FollowRedirectsBackend(myBackend, sensitiveHeaders = HeaderNames.SensitiveHeaders - HeaderNames.Cookie)
```

**Comment by karl-chan** [comment]
@adamw What OP described is a different problem, the `Set-Cookie:` headers from the response of the `N`th redirect need to be saved and added to the `Cookie:` header of the request for `N+1`th redirect onwards, but the FollowRedirectsBackend does not have built-in logic to handle this scenario.
