### ISSUE TITLE
Is Java 8 still supported?

### ISSUE THREAD

**Issue by thiloplanz** [softwaremill/sttp#1502]
Getting this after upgrading to Sttp 3.7.0 (Scala 2.13).

> java.lang.UnsupportedClassVersionError: sttp/client3/SttpBackend has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Does Sttp require Java 11 now?

**Comment by thiloplanz** [comment]
The Scala 2.12 version of Sttp 3.7.0 still works with Java 8.

**Comment by adamw** [comment]
Java 11 is required since 3.6.0: https://github.com/softwaremill/sttp/releases/tag/v3.6.1
