### ISSUE TITLE
openTelemetryTracingZioBackend library does not exist

### ISSUE THREAD

**Issue by dmitrykozinets** [softwaremill/sttp#1503]
As per the documentation [here](https://sttp.softwaremill.com/en/v3.7.0/backends/wrappers/opentelemetry.html#tracing-zio)
library `"com.softwaremill.sttp.client3" %% "opentelemetry-tracing-zio-backend" % "3.7.0"` does not exist

Please publish the openTelemetryTracingZioBackend  library

**Comment by adamw** [comment]
Should be released in 3.7.1 soon
