### ISSUE TITLE
Error: value uri is not a member of string context 

### ISSUE THREAD

**Issue by Innko** [softwaremill/sttp#1515]
Hello, 
can you please help with the following issue: I am trying to run solely this pice of code as in uri.md :

```
import sttp.client3._
import sttp.model._

val user = "Mary Smith"
val filter = "programming languages"

val endpoint: Uri = uri"https://swapi.dev/api/people/1"
```

However, I am getting error: value uri is not a member of StringContext
uri"https://swapi.dev/api/people/1"
----------------------
Env:
Scala: 2.11.1
JDK: 1.8 
IntelliJ
dependency is added in pom, version 3.7.1

Do you have any idea what could be causing this error?

Thanks

**Comment by adamw** [comment]
There must be something wrong with your setup, this works properly: https://scastie.scala-lang.org/KbCmpgJzQeeDKg49fRuB0w

One thing is that sttp 3.7 requires at least java 11, but I doubt that's causing your error. Also your Scala is very old, do you need to use 2.11?

**Comment by Innko** [comment]
Thank you very much! Unfortunately that is the setup, I cannot change. Thank you for the guidance!

**Comment by Innko** [comment]
Yes, I think I went trhough everything.... I have removed all imports, ran in object, in scala worsheet  in IntelliJ, all attempts give me same error. Just tried with 3.5.2, again same error. Must be my project set up.

**Comment by adamw** [comment]
Hm can you try outside of a worksheet? Last I checked these had problems

**Comment by adamw** [comment]
In a normally compiled Scala code

**Comment by Innko** [comment]
Yes, have tried that as well. Does not work properly, I think we can close this issue as there is not much I can do about it.

**Comment by adamw** [comment]
Just compiled the following:

```scala
class X {
  import sttp.client3._
  import sttp.model._

  val endpoint: Uri = uri"https://swapi.dev/api/people/1"
}
```

using 2.11, works just fine. So there must be something wrong with your setup.
