### ISSUE TITLE
ZioWebSockets was made private, preventing use of fromTextPipeF

### ISSUE THREAD

**Issue by pvgoran** [softwaremill/sttp#1522]
For some reason `ZioWebSockets` was made private in 5a564bf471678fe0d461fc3847dbf77c19418c2e, so library clients can no longer use its `fromTextPipe` or `fromTextPipeF` to simplify websocket handling. `Fs2WebSockets` and `MonixWebSockets` remain public.

Funnily, this doesn't affect tests which are within the `sttp.client3` package. So this regression was not noticed by testing.

**Comment by adamw** [comment]
Right, making it public :) a release will be out soon
