### ISSUE TITLE
Add explanation for response StatusCode in documentation

### ISSUE THREAD

**Issue by ScriptHound** [softwaremill/sttp#1558]
Hello, I've stuck a little with StatusCode, because I don't know how can I convert it to int for HTTP 200 or else codes and I suggest to explain more transparently how user supposed to get the actual HTTP code.

What I got:
When I've tried to get the HTTP code I got this:
```
scala> response.code
val res1: sttp.model.StatusCode = 200
```
And documetation had no example
![image](https://user-images.githubusercontent.com/24416779/189476646-1bb40c30-efd3-4020-8bc7-4c0e5f2ba35f.png)

What I expected:
An example in documentation, where it is shown how to get the actual HTTP code

What I want to do:
I want to get an integer HTTP code and assert it is equals 200 in my tests.

**Comment by adamw** [comment]
If you take a look at the definition of `StatusCode` (try the go-to-definition in your IDE, and make sure the options to download dependency sources is checked), you'll see that it has a single field:

```scala
class StatusCode(val code: Int) extends AnyVal
```

So `.code.code` will give you the int. Though in tests, I think it might be more readable to compare against `StatusCode.Ok`.
