### ISSUE TITLE
Make it easier to extending a base Uri

### ISSUE THREAD

**Issue by IainHull** [softwaremill/sttp#157]
Uri interpellation is really great, however I am increasingly duplicating complicated uri expressions because there is no easy way to append paths to a base uri.

For example

```scala
val request = sttp.get(uri"http://${clientInterface}:${config.http.port}/jobs")
// Use request

// ...

// Later in the same file
val request = sttp.get(uri"http://${clientInterface}:${config.http.port}/jobs/${job.tenant}/${job.referenceId}")
// Use request
```

I would like to do something like this

```scala
val baseUri = uri"http://${clientInterface}:${config.http.port}/jobs"

val request = sttp.get(baseUri)
// Use request

// ...

// Later in the same file
val request = sttp.get(baseUri / job.tenant / job.referenceId)
// OR
val request = sttp.get(baseUri / s"${job.tenant}/${job.referenceId})
// Use request
```

This could be supported by adding an `appendPath` method to `Uri` and create `/` as an alias. It should also be possible to some syntactic sugar for query parameters maybe with `?` and `&`.

I am happy to create a straw man PR for further discussion and later implement this feature if you think it would be as useful as me.

**Comment by adamw** [comment]
Wouldn't `uri"$baseUri/${job.tenant}/${job.referenceId}" work? Or if it doesn't, maybe it should :)

**Comment by IainHull** [comment]
Of course, I don't know why I didn't think of that.

Closing

**Comment by adamw** [comment]
Maybe the documentation should be improved then? Either the javadocs, or https://sttp.readthedocs.io/en/latest/requests/uri.html ?

If you didn't try this, quite possible others won't as well :)

**Comment by bjmc** [comment]
@adamw the example you give works well if you already know exactly how many components will make up the path. But, for example, this doesn't work:

```scala
val variablePath = "maybe/two/more" 
val fullUri = uri"$baseUri/$variablePath"
```
because the internal slashes will get url-escaped automatically.

Is the best workaround just to do `variablePath.split('/')` before interpolating?

**Comment by adamw** [comment]
@bjmc yes, the intention here is to use a collection instead of constructing the URL by hand :)
