### ISSUE TITLE
wrong uri encoding

### ISSUE THREAD

**Issue by capacman** [softwaremill/sttp#1586]
Hi,

i think there is bug in uri interpolator. Used version is 3.8.2. It does not encode ':' character after https in pathParam

```scala
val pathParam = "https://github.com/capacman/yuksekisler.git"
pathParam: String = "https://github.com/capacman/yuksekisler.git"

uri"http://abc/$pathParam".toString
res16: String = "http://abc/https:%2F%2Fgithub.com%2Fcapacman%2Fyuksekisler.git"

"http://abc/"+java.net.URLEncoder.encode(pathParam)
res17: String = "http://abc/https%3A%2F%2Fgithub.com%2Fcapacman%2Fyuksekisler.git"
```

**Comment by adamw** [comment]
That's because the `:` doesn't need to be encoded when in the path. See: https://sttp.softwaremill.com/en/latest/model/uri.html#faq-encoding-decoding-uri-components

**Comment by capacman** [comment]
Woov. Thank you. I fixed my problem with
`uri"$argoCDUri/api/v1/repositories/$repoURL".pathSegmentsEncoding(Uri.QuerySegmentEncoding.All)`
server side is go and when i dont encode everything it returns 404. Probably an error in go side.

In the mean time thank you for such an excellent library.
