### ISSUE TITLE
IgnoreResponse and Scala 2.13.9+

### ISSUE THREAD

**Issue by aheiska** [softwaremill/sttp#1599]
Hi

Sttp version: 3.8.2
Compiler flags: Defaults from sbt-tpolecat

I have a trivial function:

```
  def head(
      uri: Uri
  )(implicit
      sttpBackend: SttpBackend[IO, Any]
  ): IO[Response[Unit]] = {
    val result = basicRequest
      .head(uri)
      .response(IgnoreResponse)
      .send(sttpBackend)
    result
  }
```

This compiled fine with Scala 2.13.8. But after upgrading to .9 (also happens with .10) I started getting warning:

```
[error] ....: a type was inferred to be `Any`; this may indicate a programming error.
[error]       .response(IgnoreResponse)
[error]        ^
[error] one error found
```

Which is of course an annoyance (since sbt-tpolecat has `-Xfatal-warnings` enabled by default). Workaround is simple though:

```
      // add @nowarn before expression or
      // .response(IgnoreResponse) // remove and replace with:
      .mapResponse(_ => ())
```

I looked Scala 2.13.9 and .10 changelogs, but nothing seemed directly relevant. This feels a bit more scala (or sbt-tpolecat) regression, but I'm not completely sure, so I decided to report it here.

**Comment by adamw** [comment]
I think the scope of this warning was somehow extended ... but I also have no idea where this comes from. The work-around might be to upcast the specification (`.response(IgnoreResponse: ResponseAs[Unit, Any])`) or use `.response(ignore)`.

Ignore might be slightly more efficient than `.mapResponse(_ => ())` as the discarding is done at a lower level.

**Comment by aheiska** [comment]
Thanks. I'm not really sure why I had used `IgnoreResponse` instead of `ignore`, but it indeed removes the warning. What changed in compiler to trigger this is a mystery to me.
