### ISSUE TITLE
Will STTP remain open-source library with AKKA moving away from it 

### ISSUE THREAD

**Issue by fvukojevic** [softwaremill/sttp#1635]
Hi

Simple and quick question:

We were using AKKA in our project, but since it is moving away from being open-sourced, and it will have it's own pricing, we are looking for alternatives. 
STTP looks amazing and promising, but since it relies on AKKA, what is the future of this library? 

https://www.infoq.com/news/2022/09/akka-no-longer-open-source/

**Comment by adamw** [comment]
sttp will remain open-source and freely available. akka-http is only one of the backends, there's a lot of other ones as well, completely independent of akka. See https://sttp.softwaremill.com/en/latest/backends/summary.html for a reference. In fact, the "default" sttp backend uses Java's `HttpClient`.

We do plan to keep the akka 2.6 (last open-source version)-based backend as well.
