### ISSUE TITLE
Is it possible to specify pathSegmentsEncoding when using SttpClientInterpreter? 

### ISSUE THREAD

**Issue by kmudrick** [softwaremill/sttp#1642]
When I am using sttp directly and giving it the full path, I can use `pathSegmentsEncoding` to control how path segments get encoded:

```scala
val url = uri"${config.baseUrl}/foo/${foo}/bar/${bar}".pathSegmentsEncoding(myEncodeFunction)
```

If I am using defined sttp `Endpoints` to derive a client eg `SttpClientInterpreter().toQuickClientThrowErrors`, is there a way to do the same? Seems the only direct uri one can control in that situation is the optional `baseUri`

**Comment by adamw** [comment]
I think this is only possible using `toRequestThrowErrors`, as this gives you the `Request`, and you can then simply modify the contained `Uri` (it's a normal case class). The other methods perform the `send` right away so there's no way to manipulate the generated request or the uri

**Comment by kmudrick** [comment]
Thanks for the quick response! I will try `toRequestThrowErrors`. Thanks for the sttp & tapir awesomeness!

**Comment by kmudrick** [comment]
This worked perfectly.
