### ISSUE TITLE
Case Sensitive Headers in RequestT

### ISSUE THREAD

**Issue by ygoeksu** [softwaremill/sttp#1659]
Hello,
why is the Cookie Header here Case-Sensitive?
[https://github.com/softwaremill/sttp/blob/8feb13503fb916b33518a6012ae843880b617312/core/src/main/scala/sttp/client3/RequestT.scala#L118](url)
From this definition [https://www.rfc-editor.org/rfc/rfc9110.html#name-field-names](url) i found that field-names are case-insensitve.
Thanks for the help in advance.

**Comment by adamw** [comment]
This is a bug - it should use the `.is` method on a header. Can you maybe submit a PR? Thanks!

**Comment by ygoeksu** [comment]
Unfortunately i don't have the access to read from remote repository. I was also not able to open up a branch in the web UI.
Can I help you somehow in this situation?

**Comment by adamw** [comment]
Ah I see ... sure, I'll fix that
