### ISSUE TITLE
`:status` header on responses for simpleHttpClient

### ISSUE THREAD

**Issue by francisdb** [softwaremill/sttp#1670]
```scala
//> using lib "com.softwaremill.sttp.client3::core::3.8.5"

val resp = simpleHttpClient.send(quickRequest.get(uri"https://www.google.com"))
resp.headers.foreach(println)
```

outputs

```
server: gws
...
:status: 200
...
```

Is it expected to see this extra `:status` header in the response headers?

Have not tested any other Sttp clients.

**Comment by adamw** [comment]
It seems these are HTTP/2 pseudo-headers. Indeed, we might want to filter `:status` out

**Comment by adamw** [comment]
We'll keep the pseudo-headers as-is, as they might contain valuable information, so no need to filter them out
