### ISSUE TITLE
Known-length streaming request

### ISSUE THREAD

**Issue by jgulotta** [softwaremill/sttp#1676]
I would like to stream a request body of a known length, i.e. call `RequestT.streamBody` and have the request sent with a `Content-Length` header instead of `Transfer-Encoding: chunked`, much like a `File` can be. This looks like it was possible with the `async-http-client-backend` but does not seem to be be possible with new backends via `BodyToHttpClient` since

- `StreamBody` does not carry a length field
- `BodyToHttpClient.streamToPublisher` does not accept the `Request`, so implementations cannot look at a pre-set `Content-Length` header, nor does it accept a length parameter
- Neither `BodyToHttpClient` nor implementations like `HttpClientZioBackend` are open for extension/customization

My use case is putting an object into S3, which requires a content length, but I do not wish to buffer the full contents into memory.

I think it should be possible since `BodyPublishers.fromPublisher` has an overload accepting a length.

In the meantime, or in the event this amounts to a wont-fix feature request, is there a workaround available?

**Comment by adamw** [comment]
I haven't checked, but just a quick thought: I assume that explicitly setting the content length using `request.header("Content-Length", 123)` doesn't work as expected?

**Comment by jgulotta** [comment]
Correct. `Content-Length` is one of the few `java.net.http` considers disallowed, along with `Connection`, `Expect`, `Host`, and `Upgrade`, unless you explicitly allow them with the `jdk.httpclient.allowRestrictedHeaders` property. Trying to set a restricted header will throw an exception and never make a request.

The expectation is apparently that only `BodyPublisher` instances set restricted headers, what they call "system headers" internally. `Content-Length` is set when a `BodyPublisher` has a known non-negative content length property, and otherwise `Transfer-Encoding` is set to `Chunked`.

The most minimal change would likely be to have `BodyToHttpClient.streamToPublisher` also accept a length parameter and then forward that to `BodyPublishers.fromPublisher`, and also have something like `FiniteStreamBody` that carries the length from the user to invoke `streamToPublisher` correctly. I don't know if this would violate any source/binary stability guarantees you have around this code, however.
