### ISSUE TITLE
headers() method duplicating existing headers in request

### ISSUE THREAD

**Issue by ezequielmasciarelli** [softwaremill/sttp#1677]
Hello.

I have noticed that the headers() method duplicates existing headers instead of replacing existing ones. I realised this after bumping from version 3.8.2 to 3.8.5 and noticing that some API calls were failing because the server wasn't prepared to consume duplicated headers.
I think that this method was also duplicating the headers in version 3.8.2, but my suspicion is that somewhere else in that previous version the duplicated headers were being filtered before sending the real request.

Proposal:
It would be convenient to make the headers() method filter duplicated, or provide a flag like `replaceExisting` that already exist for the simple `header()` method.
My quick hack right now with the latest version is to do something like this:

```
val request: Request[T, Any] = ???
val customHeaders: Map[String,String] = ???
val withHeadersReplaced = customHeaders.toList.foldl[Request[T, Any]](request) { (seed, header) => seed.header(header._1, header._2, replaceExisting = true) }
```

The idea would be having something like this:

```
request.headers(customHeaders, replaceExisting = true)
```

Thanks

**Comment by adamw** [comment]
Sure, adding a new variant with the `replaceExisting` flag is a good idea. Maybe you'd like to try to attempt creating a PR which implements this?

**Comment by ezequielmasciarelli** [comment]
Sure! There it is, let me know what you think. Thanks
