### ISSUE TITLE
websocket client endpoint GotAWebSocketException exception with http4s and ZIO

### ISSUE THREAD

**Issue by dacr** [softwaremill/sttp#1682]
Tapir version: 2.0.2

Scala version: 3.2.1

Got `sttp.client3.ws.GotAWebSocketException: Got a web socket, but expected normal content` on scala.js client side while attempting to get a tapir client websocket endpoint.

## What is the problem?

Used tapir server backend is http4s.

With this endpoint : 
```scala
  val serviceEventsEndpoint =
    endpoint
      .in("ws")
      .in("system")
      .in("events")
      .tag("System")
      .name("Application service events")
      .summary("Receive application service events")
      .description("Receive broadcasted application service events")
      .out(webSocketBody[ClientMessage, CodecFormat.Json, ServerMessage, CodecFormat.Json](ZioStreams))
```

used from client side, scala.js code :
```scala
  val events: Task[Either[Unit, Stream[Throwable, ClientMessage] => Stream[Throwable, ServerMessage]]] =
    SttpClientInterpreter()
      .toClientThrowDecodeFailures(serviceEventsEndpoint, baseUri = Some(uri"ws://127.0.0.1:3000"), backend)
      .apply(())
      .tapError(err => Console.printLine("===>" + err.toString))
```

I'm unable to connect to the websocket and I get this error message on chrome console : 
![image](https://user-images.githubusercontent.com/381901/202841484-8a5e6717-f6ad-46bf-8075-372d4e81eb29.png)
```
===>sttp.client3.ws.GotAWebSocketException: Got a web socket, but expected normal content
```

If I check the websocket endpoint using curl 
```
$ curl -v http://127.0.0.1:3000/ws/system/events
...
This is a WebSocket route.
```

## How to reproduce?

This is quite easy to reproduce, from this experimental project code : https://github.com/dacr/data-recorder/tree/full-tapir
(on the `full-tapir` branch) using 3 terminals:
- terminal1, execute `make backend` : to start the scala compile/run loop
- terminal2, execute `make frontend` : to start the scala.js compile/run loop
- terminal3, execute `make frontend-vite` to start the vite "proxy" auto-reload client
- then browse to : http://127.0.0.1:3000/

**Comment by adamw** [comment]
So I checked in an sttp test trying to ping `wss://ws.postman-echo.com/raw` in JS and indeed, there's a problem due to the fact that the response has status code 200, instead of 101 (switching protocols). Not sure why this doesn't surface in tests yet

**Comment by adamw** [comment]
Ah maybe it's because we're using `asWebSocketAlways` there ... let's see

Btw., that's also a work-around - use `asWebSocketAlways` instead of `asWebSocket`.

**Comment by adamw** [comment]
A more permanent fix is on its way (I hope ;) )

**Comment by dacr** [comment]
I'll test the fix as soon as available :)

**Comment by adamw** [comment]
This might be different from what we get in the response from fetch - it might be hiding the 101 status code and exposing 200 instead

**Comment by dacr** [comment]
Hello, I still have an issue with tapir but for sttp the fix is working fine, I do not need anymore to use the asWebSocketAlways workaround : 
```
    val request =
      basicRequest
        .get(uri"ws://127.0.0.1:3000/ws/system/events")
        //.response(asWebSocketAlways(processWebsocket))
        .response(asWebSocket(processWebsocket))
```

When using sttp through tapir (from scala.js), I still encounter the issue `sttp.client3.ws.GotAWebSocketException: Got a web socket, but expected normal content` : 
```
  val events: Task[Either[Unit, Stream[Throwable, ClientMessage] => Stream[Throwable, ServerMessage]]] =
    SttpClientInterpreter()
      .toClientThrowDecodeFailures(serviceEventsEndpoint, baseUri = Some(uri"ws://127.0.0.1:3000"), backend)
      .apply(())
      .tapError(err => Console.printLine("===>" + err.toString))
```

`serviceEventsEndpoint` is declared as follow : 
```
  val serviceEventsEndpoint =
    endpoint
      .tag("System")
      .name("Application service events")
      .summary("Receive application service events")
      .description("Receive broadcasted application service events")
      .out(webSocketBody[ClientMessage, CodecFormat.Json, ServerMessage, CodecFormat.Json](ZioStreams))
      .get
      .in("ws")
      .in("system")
      .in("events")
```
