### ISSUE TITLE
correct documentation+code regarding Async-http-client 

### ISSUE THREAD

**Issue by domdorn** [softwaremill/sttp#1684]
The docs and code state that Async-http-client is no longer maintained. 
This is no longer true as of 2022-11-22, so the notices in code and docs should be reverted. 
https://github.com/AsyncHttpClient/async-http-client/commit/57326c796175214818dfd6e2ebe457cb78e2ce8a

**Comment by domdorn** [comment]
Thanks a lot!

**Comment by acloudmovingby** [comment]
My company uses the async zio backend and we had a whole ticket about replacing it because of that deprecation warning. Thank you for doing this! Made our lives a lot easier

**Comment by donce** [comment]
Hey, async-http-client is still marked as deprecated in this page: https://sttp.softwaremill.com/en/stable/conf/ssl.html#using-async-http-client-deprecated

**Comment by adamw** [comment]
@donce thanks, fixed: https://github.com/softwaremill/sttp/commit/2b3c81e7e0dc560ef298c80463c964f2f449e706
