### ISSUE TITLE
Possible bug with early termination in the fs2 backend

### ISSUE THREAD

**Issue by kubukoz** [softwaremill/sttp#169]
I'm not sure if it's the fault of sttp/AHC/fs2/circe-fs2, but a combination of these two causes some weird behavior.

Here's my original code (that works):

```scala

import java.nio.ByteBuffer

import cats.effect.Sync
import com.softwaremill.sttp.{Request, SttpBackend}
import com.typesafe.scalalogging.Logger
import fs2.{Chunk, Stream}
import io.circe.Decoder

object SttpClientUtils {

  type StreamedRequest[F[_]] = Request[Stream[F, ByteBuffer], Stream[F, ByteBuffer]]

  type StreamingBackend[F[_]] = SttpBackend[F, Stream[F, ByteBuffer]]

  /**
    * Sends the request and decodes the response as a JSON array, in a streaming manner, using the given decoder.
    * */
  def sendAndDecodeResponseAsStream[F[_]: Sync, A: Decoder](
    request: StreamedRequest[F]
  )(implicit
    sttpBackend: StreamingBackend[F],
    logger: Logger
  ): Stream[F, A] = {
    import io.circe.fs2._

    fs2.Stream
      .eval(request.send())
      .flatMap[F, A] { response =>
        response.body.fold(_ => fs2.Stream.raiseError(new Throwable("foo")), identity)
        .map(Chunk.byteBuffer)
        .through(byteArrayParserC)
        .through(decoder)
      }
  }
}
```

However, there's a difference in behavior when I move the `.through(byteArrayParserC)` part of the stream to the outside:

```scala
fs2.Stream
  .eval(request.send())
  .flatMap[F, Chunk[Byte]] { response =>
    response.body.fold(_ => fs2.Stream.raiseError(new Throwable("foo")), identity)
      .map(Chunk.byteBuffer)
  }
  .through(byteArrayParserC)
  .through(decoder)
```

Because `fs2.Stream` is capable of keeping resources open for the duration of the whole stream even after flatMap chains, this should be equivalent to the above (and also because of the monad associativity law). However, it's not.

The first execution of such a request works perfectly fine, however the second (and every subsequent one) fails:

`io.circe.ParsingFailure: expected eof got [ (line 1, column 853423)`

**Comment by adamw** [comment]
Trying to reproduce this, so far no luck :) I'm assuming you are using the `AsyncHttpClientFs2Backend` backend?

Here's the test I added there:

```
"receive a stream 2" in {
    val body = "LONG TEXT" * 100000
    val request = sttp
      .post(uri"$endpoint/streaming/echo")
      .body(body)
      .response(asStream[Stream[IO, ByteBuffer]])

    val run = fs2.Stream
      .eval(request.send())
      .flatMap { response =>
        response.body
          .fold(_ => fs2.Stream.raiseError[IO](new Throwable("foo")), identity)
          .map(Chunk.byteBuffer)
      }
      .through(text.utf8DecodeC)
      .compile
      .foldMonoid
      .map { responseBody =>
        println(s"CHECK ${responseBody == body}")
        responseBody shouldBe body
      }

    (run >> run >> run)
      .toFuture()
  }
```

There's a large body, streaming response, decoding it outside of the response's flatMap, and repeating the whole thing three times. And it passes of course ;) Do you see any place where it's significantly different from yours? 

(I assume you tried latest btw?)

**Comment by kubukoz** [comment]
I haven't seen this happen in a while so I'll close the issue :)
