### ISSUE TITLE
Bug: `request.get(...).body(...).send(...)` runs a POST request instead of GET

### ISSUE THREAD

**Issue by winitzki** [softwaremill/sttp#1710]
I am using STTP3 client version 3.3.1 because I have to run JDK 8. The latest version of STTP3 is 3.8.8 but I could not test that.

Description of the bug:

I am running a `GET` request with a request body. (This is what I need to do, although GET requests usually don't have a request body.)

I expect that `request.get().body().send()` will work but it does not work because it makes a `POST` request instead of `GET`.

To reproduce:

In a terminal window, run `echo | nc -l 11111` and leave it running, this will mock the web server.

In another terminal window, run a `GET` request with body:

```scala
@  import $ivy.`com.softwaremill.sttp.client3::core:3.3.1`
@  import sttp.client3.quick._
@  quickRequest.get(uri"http://localhost:11111/asdf").body("xyz").send(backend)
sttp.client3.SttpClientException$ConnectException: Exception when sending request: GET http://localhost:11111/asdf
  sttp.client3.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:33)
```

The exception is "Connection refused". Then I go to the first terminal window and observe the following server input:

```bash
$ echo |nc -l 11111
POST /asdf HTTP/1.1
Accept-Encoding: gzip, deflate
Content-Type: text/plain; charset=utf-8
User-Agent: Java/1.8.0_312
Host: localhost:11111
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 4

xyz
```

The request was actually a `POST` request.

I inspect the STTP request value but don't see any `POST` methods anywhere, the request looks correct:

```scala
@ val req = quickRequest.get(uri"http://localhost:11111/asdf").body("xyz")
req: sttp.client3.RequestT[sttp.client3.package.Identity, String, Any] = RequestT(
  method = Method(method = "GET"),
  uri = Uri(
    scheme = Some(value = "http"),
    authority = Some(value = Authority(userInfo = None, hostSegment = Segment(v = "localhost", encoding = sttp.model.Uri$HostEncoding$$$Lambda$2171/2055967078@77d4ac52), port = Some(value = 11111))),
    pathSegments = AbsolutePath(segments = List(Segment(v = "asdf", encoding = sttp.model.Uri$PathSegmentEncoding$$$Lambda$2177/1575407418@3b98b809))),
    querySegments = List(),
    fragmentSegment = None
  ),
  body = StringBody(s = "xyz", encoding = "utf-8", defaultContentType = MediaType(mainType = "text", subType = "plain", charset = None, otherParameters = Map())),
  headers = Vector(Accept-Encoding: gzip, deflate, Content-Type: text/plain; charset=utf-8, Content-Length: 4),
  response = MappedResponseAs(raw = ResponseAsByteArray, g = sttp.client3.SttpApi$$Lambda$2152/737897289@e09f1b6, showAs = Some(value = "as string")),
  options = RequestOptions(followRedirects = true, readTimeout = 1 minute, maxRedirects = 32, redirectToGet = false),
  tags = Map()
)
@ req.toCurl
res5: String = "curl -L --max-redirs 32 -X GET -H 'Content-Type: text/plain; charset=utf-8' -H 'Content-Length: 4' --data 'xyz' 'http://localhost:11111/asdf'"
```

This curl request produces a `GET` request when run against the `nc -l 11111` server.

**Comment by winitzki** [comment]
I did not have a lot of time to go through the sttp3 source code but I could not quickly locate the place where the `GET` method from the `requestT` type is getting replaced by `POST` when the actual HTTP call is made.

**Comment by adamw** [comment]
I think this might be hard-coded in the `HttpURLConnection` that you are (indirectly) using, see: https://stackoverflow.com/questions/18664413/can-i-do-an-http-get-and-include-a-body-using-httpurlconnection

A solution would be to use another synchronous backend (such as [OkHttp](https://sttp.softwaremill.com/en/latest/backends/synchronous.html#using-okhttp)), or to update Java and use the `HttpClient`-based one.

**Comment by winitzki** [comment]
Thank you, this makes sense.

**Comment by winitzki** [comment]
@adamw Thank you again for your help. Just FYI, I tried the `OkHttp` backend but it refuses to run a `GET` request with body, instead it throws an exception right away saying that it's not allowed. Upgrading JDK is not possible for me right now, so I'm out of options with STTP3. I had to fall back on an apache HTTP client with custom-made SSL context and custom-made HTTP `GET` request.

**Comment by adamw** [comment]
@winitzki hm, well sorry tohear that :) Yet another option would be to use a `Future`-based backend (such as the one based on async-http-client - I think it allows GETs with a body), and call `Await.result(...)` on the future. A bit indirect, though.
