### ISSUE TITLE
Inconsistent JSON parsing error handling

### ISSUE THREAD

**Issue by NPCRUS** [softwaremill/sttp#1721]
Hi folks, I stumbled across interesting issue lately. I'm converting response from other api into json using spray-json. So if I use real backend and real api `DeserealizationException` is being throwed as part of `SttpClientException.ReadException`. When I'm trying to write tests for my logic and I stub `Backend` this exception is being thrown on it's own, bypassing it being wrapped into `ReadException`
```
"catch DeserializationException" in {
  val testingBackend = SttpBackendStub.synchronous
    .whenAnyRequest
    .thenRespond("{}", StatusCode(400))

  val request = () => basicRequest
    .get(uri"./test")
    .response(asJsonEither[AuthError, String].getEither)
    .send(testingBackend)

  an [sttp.client3.DeserializationException[_]] should be thrownBy request()
}

"catch ReadException with DeserializationException inside" in {
  val realClient = SimpleHttpClient()

  val request = () => basicRequest
    .get(uri"$realUrl")
    .response(asJsonEither[AuthError, String].getEither)
    .send(realClient.backend)

  val readException = the [sttp.client3.SttpClientException.ReadException] thrownBy request()
  readException.cause shouldBe a [sttp.client3.DeserializationException[_]]
}
```
as you've guessed - both tests are green. Is this behavior intended?

**Comment by adamw** [comment]
Good catch, the adjust-exceptions step was indeed missing from the stub backend

**Comment by NPCRUS** [comment]
@adamw great! Thanks for quick response. Wanted to ask if I can make a PR, but you were much faster creating it, than me resolving to ask
