### ISSUE TITLE
Multipart form-data request error

### ISSUE THREAD

**Issue by gowravshekar** [softwaremill/sttp#173]
Content type isn't set when using multipart form-data.

```bash
curl -X POST \
  http://localhost:2004/v2/api/artifacts \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F file=@/Users/username/filename
```

Below is the scala code.

```scala
val request = sttp
      .multipartBody(multipart("file", new FileInputStream(filePath)))
      .post(uri"$mistApiUrl/v2/api/artifacts")
val response = request.send()
```

The field `file` is not being sent properly.

**Comment by adamw** [comment]
which backend are you using? And how is it not sent properly, what's wrong exactly?

**Comment by gowravshekar** [comment]
I tried `AkkaHttpBackend` and `HttpURLConnectionBackend`. 

The expectation is making a multipart form data POST request with file parameter. The server responds with `file` parameter not found. Details [here](https://hydrosphere.io/mist-docs/http_api.html).

The problem might be with the server. I created a mock server and logged the request and was able to see the `file` parameter.  I have notified the server library about the issue.

**Comment by gowravshekar** [comment]
The problem was with sttp api pasted [here](https://github.com/softwaremill/sttp/issues/173#issue-395455097).

Works after calling `fileName` function. Please add it in the documentation.

```scala
val request = sttp
        .multipartBody(multipart("file", new FileInputStream(filePath)).fileName(fileName))
        .post(uri"$mistApiUrl/v2/api/artifacts")
```

**Comment by adamw** [comment]
@gowravshekar there's already some documentation around multi-part: https://sttp.readthedocs.io/en/latest/requests/multipart.html

if you think something can be explained more clearly, maybe you could try creating a PR? Here's the source: https://github.com/softwaremill/sttp/blob/master/docs/requests/multipart.rst
