### ISSUE TITLE
Feature Request: Make MonadError implicit param

### ISSUE THREAD

**Issue by enzief** [softwaremill/sttp#174]
It should be intuitive making a stub like this
```scala
val c: SttpBackend[Try, A] = SttpBackendStub[Try, A]
```
instead of currently
```scala
SttpBackendStub[Try, A](TryMonad)
```

**Comment by adamw** [comment]
👍 

Though that would require making all the monad implementations implicit, a bigger change probably for the next major version

**Comment by enzief** [comment]
Is it in any short term plan? Or is there a roadmap somewhere that I missed?

**Comment by adamw** [comment]
@enzief no short term plan, I have some ideas on what I'd like to change in the API (nothing major, but still breaking), but not sure when the time is going to find itself ;)

**Comment by adamw** [comment]
Stubs can be now convientently created from the backend companion objects, and I think there hasn't been other demand for making the monad instances implicit. As we don't want to pollute the implicit scope without a good cause, closing.
