### ISSUE TITLE
Follow redirects option does not pass through the auth methods

### ISSUE THREAD

**Issue by leszekgruchala** [softwaremill/sttp#1745]
Suppose you make a call that returns 303 redirects. In that case, the `.followRedirects(true)` option does a redirect, but without the previously specified authentication (e.g. `.auth.bearer("token")`), which makes the redirect ineffective at this point.

**Comment by adamw** [comment]
Yes, that's on purpose, see: https://sttp.softwaremill.com/en/latest/conf/redirects.html#important-note-on-the-authorization-header
