### ISSUE TITLE
Feature Request: MonadError for Either

### ISSUE THREAD

**Issue by enzief** [softwaremill/sttp#175]
`Either[Throwable, ?]` also forms a `MonadError`. Can we please make an instance for it?

**Comment by adamw** [comment]
Sure - would this also come as some backends/backend wrappers?

**Comment by enzief** [comment]
Sorry I don't get your question 😕 I'd imagine the implementation should look like `TryMonad`.

**Comment by adamw** [comment]
Yes, but these monads are usually there because they are used in a `SttpBacked` - such as the `TryBackend` wrapper. My question was would you envision creating a backend wrapper for the `Either` monad as well :)

**Comment by enzief** [comment]
That'd be desirable I think. If it's not too difficult I can submit a PR.

**Comment by adamw** [comment]
Shoudln't be :) looking forward, let me know if you come across any problems
