### ISSUE TITLE
Add WebSocket support to HttpClientSyncBackend

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#1767]
Depends on https://github.com/softwaremill/sttp/issues/1766

**Comment by adamw** [comment]
cc @adpi2 @szymon-rd: this would change the type of the default backend from `SyncBackend` to `WebSocketSyncBackend`

**Comment by adpi2** [comment]
I was wondering why `HttpClientSyncBackend` did not support `WebSockets` and here is the answer: because it is not yet implemented. :)

Do we still have an implementation of `SyncBackend` that do not support `WebSockets`?

**Comment by adamw** [comment]
E.g. `HttpURLConnectionBackend` and `CurlBackend`
