### ISSUE TITLE
Add a Variant of asJson that always throws 

### ISSUE THREAD

**Issue by bishabosha** [softwaremill/sttp#1771]
## version affected

4.0.0-M1

## Describe the issue

To me it seems strange that `asJsonAlways` merges success and error bodies for http errors, but still wraps the body in `Either` in case of deserialisation problems, which still requires the user to explicitly handle deserialisation errors.

In the spirit of `import sttp.client4.quick.*` it seems it would make sense to have a variant of `asJson` that extends `asJsonAlways` but also throws in the case of deserialisation errors, so that for scripting, assuming a happy path has no friction from handling errors.

e.g. imagine a script like

```scala
import sttp.client4.quick.*
import sttp.client4.upicklejson.*

def allNotes: ujson.Value =
  val resp = quickRequest
    .get(uri"http://localhost:8080/api/notes/all")
    .response(asJsonOrThrow[ujson.Value])
    .send()
  resp.body

allNotes.arr.foreach(println)
```

**Comment by adamw** [comment]
I think `.getRight` does what you want: https://sttp.softwaremill.com/en/stable/responses/body.html#failing-when-the-response-code-is-not-2xx

Not saying that the defaults shouldn't change, this might be the case :)

**Comment by bishabosha** [comment]
Thanks, I didn't know about `.getRight` before, that's really useful!

**Comment by bishabosha** [comment]
@adamw what do you think about adding another variant of `quickRequest` (or changing `quickRequest`) to use `asString.getRight` rather than `asStringAlways`

**Comment by bishabosha** [comment]
I think my core frustration is just wanting a simple way to ignore errors for a beginner - so they do not need to consider `Either[SomeException, T]` - and just get the `T`. So far the standard library only gives us `.toTry.get` which is annoying to explain.

The suggestion to use `asJson[T].getRight` could work for that case, but then all the cases where we do not need to deserialise a json body now have different error handling behaviour (unless we explicitly add `asString.getRight`).

**Comment by adamw** [comment]
@bishabosha wouldn't this be the same as `.getRight`? https://github.com/softwaremill/sttp/blob/0c5e312ef1a70d9c1180eb34d847a0a1378b680d/core/src/main/scala/sttp/client3/ResponseAs.scala#L112

**Comment by bishabosha** [comment]
No because the `simple` extension would only throw for deserialisation errors, not for http status codes

**Comment by adamw** [comment]
So what would happen then if the response is a 404 or a 500 (which probably wouldn't bo formatted as a `Value` json)?

**Comment by bishabosha** [comment]
> So what would happen then if the response is a 404 or a 500 (which probably wouldn't bo formatted as a `Value` json)?

If that is the most likely case, then again I guess to have a consistent error model for `asJson.getRight` what is missing is a default request that uses `asString.getRight`?

e.g. if you were making some `NotesRepo` object with several responses that can return json body, some responses that return no body, but you want the same throwing behaviour for 404/502 etc on the empty responses.

**Comment by adamw** [comment]
This seems as a quite specialised case, if you want to have specific JSON parsing for some status code, but not for others, I think you should simply do `asString.mapWithMetadata(...)`.

The default requests in sttp don't throw, they return an `Either[String, String]` (the `basicRequest`).

But coming back to the original issue, I did consider adding a `asJsonOrThrow`, but in the end decided on adding a `.getRight` method which has less code duplication (you don't have to define the same method for every JSON integration). But it might be better to pay that price

**Comment by bishabosha** [comment]
I think then for consistency in the Scala Toolkit tutorials we should then recommend handling Either explicitly for deserialising JSON, I guess then also use `basicRequest`, so `Right` always means success.

**Comment by adamw** [comment]
Well we could have a `asStringOrThrow`, just as we can have `asJsonOrThrow`. Both are possible today, but they require `asString.getRight` or `asJson.getRight`. I'll reopen this to re-evaluate if it's maybe better to add the explicit response specifications(at the expense of more code), or somehow document `.getRight` better.
