### ISSUE TITLE
Sending large files through multipart IS 

### ISSUE THREAD

**Issue by Philldomd** [softwaremill/sttp#1780]
Hi,

I am trying to send large files thourgh multipart but it doesn't seem to get the right output buffer from Http.
I have tried to send in contentLength to PUT Header, MultipartBody and to multipart(as header(string, string)). None of them registers with contentLength in class HttpURLConnectionBackend. This section seems to be the problem:

```
val contentLength = partsWithHeaders
      .map { case (headers, p) =>
        val bodyLen: Option[Long] = p.body match {
          case StringBody(b, encoding, _) =>
            Some(b.getBytes(encoding).length.toLong)
          case ByteArrayBody(b, _)   => Some(b.length.toLong)
          case ByteBufferBody(_, _)  => None
          case InputStreamBody(_, _) => None
          case FileBody(b, _)        => Some(b.toFile.length())
          case NoBody                => None
          case StreamBody(_)         => None
          case MultipartBody(_)      => None
        }

        val headersLen = headers.getBytes(Iso88591).length

        bodyLen.map(bl => dashesLen + boundaryLen + crLfLen + headersLen + crLfLen + crLfLen + bl + crLfLen)
      }
      .foldLeft(Option(finalBoundaryLen)) {
        case (Some(acc), Some(l)) => Some(acc + l)
        case _                    => None
      }
```

I get an heap out of memory exception here:
``` 
private[client3] def transfer(is: InputStream, os: OutputStream): Unit = {
    var read = 0
    val buf = new Array[Byte](IOBufferSize)

    @tailrec
    def transfer(): Unit = {
      read = is.read(buf, 0, buf.length)
      if (read != -1) {
        os.write(buf, 0, read)
        transfer()
      }
    }

    transfer()
  }
```

Then why am I doing it this way, the stream I try to send is a large file that i find inside of an even larger zip. So i utilize the zipEntry data to get inputstream, filename and size to the file I need. We used to send this as a file before but discspace has limited our possibilities. Is there any way of forcing it to use an stroutputbuffer, as the one used in multipartFile.

**Comment by SethTisue** [comment]
seems better suited to https://softwaremill.community/c/sttp-client than to the bug tracker

**Comment by Philldomd** [comment]
That site needs login, and the markdown doesn't seem to work

**Comment by Philldomd** [comment]
If there is no way of forcing it, then it is a major bug or oversight in the implementation.

**Comment by Philldomd** [comment]
The website above blocked my ticket. But shouldn't this switch case at least look for a ContentLength in the multipart? 

```
val contentLength = partsWithHeaders
      .map { case (headers, p) =>
        val bodyLen: Option[Long] = p.body match {
          case StringBody(b, encoding, _) =>
            Some(b.getBytes(encoding).length.toLong)
          case ByteArrayBody(b, _)   => Some(b.length.toLong)
          case ByteBufferBody(_, _)  => None
          **case InputStreamBody(_, _) => Some(r.headers.find(_.name == HeaderNames.ContentLength).toString.split(":").last)**
          case FileBody(b, _)        => Some(b.toFile.length())
          case NoBody                => None
          case StreamBody(_)         => None
          case MultipartBody(_)      => None
        }

        val headersLen = headers.getBytes(Iso88591).length

        bodyLen.map(bl => dashesLen + boundaryLen + crLfLen + headersLen + crLfLen + crLfLen + bl + crLfLen)
      }
      .foldLeft(Option(finalBoundaryLen)) {
        case (Some(acc), Some(l)) => Some(acc + l)
        case _                    => None
      }
```

Something like the solution above.

**Comment by SethTisue** [comment]
Clarification: I hadn't understood — partly because the mangled Markdown made the code very hard to read — that the first piece of code was code inside sttp, not your own personal code.

I'm also not an sttp maintainer, so perhaps someone more knowledgeable will comment next.

**Comment by Philldomd** [comment]
Further investigation showed me that according to proposed rfc 7578, https://www.rfc-editor.org/rfc/rfc7578 , there is no content length per multipart object. So the content length specified in multipartbody should be the size of all included objects. Then the above calculation should still calculate each parts size. Then add contentlength as the last size. 

Then in this case the implementation could be a bit tricky as the switch case should be left as is but a check for multipartbody content length should determine if the output buffer is of post or stream size.

**Comment by adamw** [comment]
I think we should either discuss here or on https://softwaremill.community/t/sending-large-files-through-multipart-is-1780/163/3 (where I originally replied).

I'm still not sure what the core problem is, so it would be great if you provided some code example of what you're trying to do (using sttp's API), and what's the effect - is it wrong headers, an OOM, or sth else :)

**Comment by Philldomd** [comment]
Okey i will keep my posting to here then. 

Clarification: We are today unpacking a large zip file from a zip, 10+ gig of content from a file even bigger, that we then send to our server through http. Today we unpack the zip from the zip and send it as a File like this:
```
val request: Request[Either[String, String], Any] = 
    basicRequest.put(uri"${Url}")
         .readTimeout(10.minutes)
        .multipartBody(multipartFile("file", Package))
```
This works great but we now face the problem that the volume we use is limited and we fill it out when unpacking this zip. So our new solution is to just zipstream it from the file and then send the InputStream as a multipart instead, like this:
```
     val request: Request[Either[String, String], Any] = 
       basicRequest.put(uri"${Url}")
         .readTimeout(10.minutes)
        .multipartBody(
          multipart("file", Package)
          .dispositionParam("filename", filename)
          .contentType(ApplicationZip)
        ).contentLength(size)
```

The change here is that Package is an input stream and the size of the stream is sent in as an multipartBody.contentLength. What happen here then is that val contentLength = partsWithHeaders return None for all input stream bodies, this is a major problem as in the next step it tries to copy every byte to an outputbuffer. This is as far as my implementation was able to reach:
```
private[client3] def transfer(is: InputStream, os: OutputStream): Unit = {
    var read = 0
    val buf = new Array[Byte](IOBufferSize)

    @tailrec
    def transfer(): Unit = {
      read = is.read(buf, 0, buf.length)
      if (read != -1) {
        os.write(buf, 0, read)
        transfer()
      }
    }

    transfer()
  }
```

Instead of sending this as an PostOutputBody as above. I would like to be able to force it somehow to use StreamOutputBody in http. In this case i need to specify the actual length of the stream. So sending it in as a contentLength to multipart would be nice but sending it to multipartBody could also work. I know that multipart/form-data doesn't have contentLength on multiparts but if sttp is to calculate the multipartBody contentlength then it might need to be able to set on each part. 
```

**Comment by adamw** [comment]
If you're on 3.5.2, you'll need an additional dependency, see: https://sttp.softwaremill.com/en/v3.5.2/backends/synchronous.html#using-httpclient-java-11

I think there are two separate issues here:

1. the ability to add a hint to a `Part`, so that the content length might provided, even if it's not known directly from the type; note that this should be specified on the `Part`, not on the whole multipart body, as there may be many parts, and the size of the boundaries is unknown (so you are not able to provide the total correct content length)

2. the fact that the entire input or output is accumulated in memory, instead of only a sliding window being buffered; could you determine, if it's the input, or the output stream, that accumulates the data (using e.g. a profiler)? How do you obtain the input stream from the zip file?

**Comment by Philldomd** [comment]
1. `Part` did not seem to have a length or size variable to set, or at least not a function allowing me to do so. I would like a solution like this though and have the input size only state the content length. So that the calculation form-data calculation is still correct.  

2. The input stream is of standard Java io format. In my unit test I actually try to save it to disk, and that it does as a buffered stream. So in this case it seems that `Transfer` function, that is called as soon as I call send, is trying to copy all of it to an output. Resizing the buffer over and over again. So in this case it is the choice of output buffer in HttpURLConnectionBackend that selects the wrong one. That choice depends on contentlength and will always choose the post one if it is None. 

Would this work for us if we just switch to Sync? I haven't had time to look through that implementation yet and, as said before, can't test it yet. 

Sorry for weird format but I am answering on my phone.

**Comment by adamw** [comment]
1. yes, that's not yet available for `Part`. Something we'd have to add :)
2. the whole problem here might be what kind of concrete implementations of `InputStream` / `OutputStream` are chosen, and how they work - do they buffer the whole input, for example? That's why I'd like to try the same thing with `HttpClientSyncBackend`, which is a different (more modern) http client implementation than the one based on `HttpURLConnection`.

**Comment by adamw** [comment]
I've published a SNAPSHOT release with the following changes: https://github.com/softwaremill/sttp/pull/1786/files
which should take into accoun the content-length as a hint for the part size

The version number is `3.8.13+2-f9894b77+20230329-1245-SNAPSHOT`, available from `https://s01.oss.sonatype.org/content/repositories/snapshots`

But please try with `HttpClientSyncBackend` as well :)

**Comment by Philldomd** [comment]
This seems promising, I will try both in the upcoming days. I will post my results here as soon as I tried it out.

**Comment by Philldomd** [comment]
Hi, now i have had time to test the HttpClientSyncBackend instead of the HttpUrlConnect. It solved all of my problems and worked out of the box for all of my other connections. Do you still want me to try out the snapshot?
