### ISSUE TITLE
Verify & fix if needed using sttp native (curl) from scala-cli

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#1789]
See: https://twitter.com/otobrglez/status/1637762311761846272?s=46&t=rklTHFPDf0gOQs_iFaCzkw

**Comment by kciesielski** [comment]
Together with @wydra98 we have created a nice working example:

```scala
//> using toolkit latest

import sttp.client4.*
import sttp.client4.curl.*
import sttp.client4.Response

object sttpClient4NativeWorkingExampleWithLongNameOfTheMainClass extends App:
    val backend = CurlBackend()
    val response: Response[String] = quickRequest
      .get(uri"http://icanhazip.com")
      .send(backend)

    println(response.body)
```
The strange main object name is not accidental. A different name can cause build errors depending on small changes in the code, I reported an issue in the scala-native repo: https://github.com/scala-native/scala-native/issues/3363

**Comment by adamw** [comment]
@kciesielski awesome :)

**Comment by kciesielski** [comment]
I guess we better wait for the scala-cli fix before we proceed with announcing how cool it is to write sttp apps on Scala Native? :)

**Comment by adamw** [comment]
Yes sure ;)
