### ISSUE TITLE
Interest on a play-ws (standalone) backend for STTP?

### ISSUE THREAD

**Issue by ragb** [softwaremill/sttp#179]
I need to have support for [play-ahc-ws-standalone](https://github.com/playframework/play-ws) as a backend for sTTP. 

Question is: is there interest on contributing it to STTP itself or is it better to work on an external project? There is already an old play-ws (full play framework version) of this which I'm using as an initial reference.

**Comment by ragb** [comment]
They bundle their version of AHC shaded. I tried to use the AHC backend but with no look.

**Comment by adamw** [comment]
Ah ... I suppose you could reuse most of the AHC backend then.
Anyway, I think it would be best to start as a separate project. If there's much interest, we can always later merge into the main one.

**Comment by ragb** [comment]
I have a prototype using play-ws own API. It’s simpler than Akka-http. I’ll try reusing async HTTP approach also.

Will keep as a separate project for now.

**Comment by adamw** [comment]
Ok, when it's released, please share a link, I'll add it to the docs. Thanks!

**Comment by ragb** [comment]
Started implementation for this, however play-ws-standalone doesn't support important stuff like multipart form content (play-ws supports it though). We decided to use the akka-http-backend meanwhile. I'm closing this since I dropped this effort.

**Comment by ragb** [comment]
Happen to need this again so finished the implementation based on standard play-ws (not standalone). it's useful in a play application context where one needs to use already coded sttp request descriptions.

Code is at https://github.com/ragb/sttp-play-ws
and it's released to Sonatype. Reopening this issue, please add to documentation if it makes sense.

**Comment by adamw** [comment]
Done: https://sttp.readthedocs.io/en/latest/backends/summary.html

Thanks!

**Comment by veysiertekin** [comment]
Since https://github.com/ragb/sttp-play-ws wasn't maintained, I have published updated with play 2.8 & recent sttp version here: https://github.com/scalamania/sttp-play-ws

**Comment by adamw** [comment]
@veysiertekin Thanks, I've udpated the link: https://github.com/softwaremill/sttp/commit/14e0ddfecbf58f89e24465f592d4cfea664f6d16
