### ISSUE TITLE
Feature request: Publish `jsoniter` module for Scala Native

### ISSUE THREAD

**Issue by kyri-petrou** [softwaremill/sttp#1795]
Hi there 👋 I'm working on building [Caliban client](https://github.com/ghostdogpr/caliban) for Scala Native. Currently, the only dependency of it that doesn't publish for Scala Native is sttp's `jsoniter` module. `jsoniter-scala` recently [added support for Scala Native](https://github.com/plokhotnyuk/jsoniter-scala/releases/tag/v2.17.4).

Would you be interested in publishing the `jsoniter` module for Scala Native? I've got a [working version (aiming at v3)](https://github.com/softwaremill/sttp/compare/v3...kyri-petrou:sttp:jsoniter-scala-native), so I can open a PR if you're happy with support it

**Comment by adamw** [comment]
Sure! waiting for the PR :)

**Comment by kyri-petrou** [comment]
Should my PR target the `master` or `v3` branch?

**Comment by adamw** [comment]
If you'd like to publish for v3, then `v3`, but we'll have to forward-port to `master` as well

**Comment by kyri-petrou** [comment]
Okay sounds good. I [created a PR](https://github.com/softwaremill/sttp/pull/1796) targeting `v3` and I'll create another for `master` once it's been approved

**Comment by kyri-petrou** [comment]
By the way I realised `v4` already has a Scala Native build for jsoniter, so we don't need to forward-port
