### ISSUE TITLE
POST / REDIRECT / GET

### ISSUE THREAD

**Issue by Ferada** [softwaremill/sttp#182]
I have an API here that follows the usual pattern of requiring a POST, then it will redirect you to a different URL. With `followRedirects` on, `sttp` follows the redirect, but then does the POST again, which then (thankfully not silently in this case) caused a 501 "Not Implemented" output.

Edit: [Similar curl issue](https://github.com/curl/curl/issues/578) - so I suppose it's something where a reasonable default behaviour would be nice that can be used instead of implementing this yourself? Or, if not, maybe a small note in the docstring of the option then?

**Comment by adamw** [comment]
Interesting problem :) 

Looking at https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections, it seems that handling POST 301/302 redirects is something of a grey area - some clients use GET for the redirect, some use POST, some do nothing.

So it seems we should somehow support 301/302 POST redirects - through an additional option? Always using GET? Always preserving the method? Doing nothing?

(btw. there are also 307/308 redirects where the method should always be preserved)

**Comment by Ferada** [comment]
Yes I think it'd also be completely okay to keep it as it is, with a warning attached to remind people that indeed the `POST` will be attempted again at the new location.

However, that'd mean, since there's no general purpose "follow redirects" wrapper, that users will have to keep writing code for that in case they just need behaviour like a (typical) browser / command line tool.

I could see a new flag like `redo(Action)AfterRedirect` (or even more specific, `useGetAfterRedirect`) that would keep the current behaviour when unchanged (backwards compatibility) and that would, when set to a different value, not issue a `POST`/`PUT`/... action, but a `GET` instead. I'm not sure that covers all bases though.

About the different codes ... beats me, I'd go for least surprise, i.e. match `curl`/`wget`'s behaviour :)

**Comment by adamw** [comment]
1.5.10 contains a new option, `redirectToGet` (defaults to `false`), which should cause POSTs to be redirected to GETs. Maybe in the next major release we can consider swapping the default.

Could you test it?

**Comment by Ferada** [comment]
Splendid, yes, I will.
