### ISSUE TITLE
Consideration for Release of sttp Version 3.8.15 With Updated Dependencies Of FS2 and http4s-client For CE 3.5.0

### ISSUE THREAD

**Issue by cosmir17** [softwaremill/sttp#1842]
Hello,

Firstly, let me express my profound appreciation for your diligent work on the sttp library. 
I've been using version "3.8.15" of "com.softwaremill.sttp.client3" %% "http4s-backend", which has dependencies on fs2 version 3.6.1 and "org.http4s" %% "http4s-client" version "0.23.18".

However, as the recently released Cats Effect 3.5.0 necessitates FS2 version 3.7.0 and http4s-client version 0.23.19, I find myself needing to update these dependencies in my project.

Upon checking sttp's master branch, I was pleased to find that it already houses FS2 version 3.7.0 and http4s-client version 0.23.19. Given this, I was wondering if it might be possible, at your convenience, to release version 3.8.16 of sttp that includes these updated dependencies.

Thank you once again for all the effort you put into maintaining this invaluable project. I truly appreciate your time and contributions.

**Comment by adamw** [comment]
I think you should be able to use sttp client with all the new versions - all of the dependency updates have gone through without needing any kind of code updates. Does that work for you?

**Comment by cosmir17** [comment]
Our project's tests run in a flaky manner with different versions of FS2 (3.7.0, 3.6.1, etc).
As [the Cats effect 3.5.0 release note](https://github.com/typelevel/cats-effect/releases/tag/v3.5.0) demonstrates,
Would it be ok if the [sttp fs2](https://mvnrepository.com/artifact/com.softwaremill.sttp.client3/fs2_3) component's fs2 version to be upgraded to 3.7.0, please 🙏  Currently, it seems 3.6.1 

[sttp fs2](https://mvnrepository.com/artifact/com.softwaremill.sttp.client3/fs2_3/3.8.15) is used by [sttp http4s-backend](https://mvnrepository.com/artifact/com.softwaremill.sttp.client3/http4s-backend_3/3.8.15)

**Comment by adamw** [comment]
@cosmir17 Ok, we can do that - can you prepare a PR which updates the necessary components, against the `v3` branch?

**Comment by kciesielski** [comment]
@cosmir17 Dependencies updated and released as v.3.8.16
