### ISSUE TITLE
Retry mechanism

### ISSUE THREAD

**Issue by Ferada** [softwaremill/sttp#185]
I'd like to have a configurable retry mechanism similar to what's described in https://github.com/softwaremill/sttp/blob/master/docs/backends/custom.rst#example-retrying-backend-wrapper, but as a proper part of the library. In fact I just found that link now, so I scrapped what I had written before about the manual retry mechanism I added for a particular API call. Would a PR to add it as such be of interest? One addition I'd like to add is the backoff mechanism, in fact some reuse of https://github.com/softwaremill/retry is probably a good idea ...

---

Part of the original question remains though, how do people deal with the massive stacktraces caused by the tail calls that aren't optimised away from the use of `responseMonad.flatMap`? My example isn't exactly using a fixed number of retries, but instead it's a polling call which would easily have 100 or more retries before succeeding.

![stacktrace](https://user-images.githubusercontent.com/13713/52728903-6bc3e900-2fb8-11e9-87a3-40872d661b55.png)

^ Just for illustration, that's three retries, 4 x `wait`, which is basicallly this:

```
  def wait(interval: Duration = 1 second): R[Response[...]] = {
    backend.responseMonad.flatMap(status(...))(status => {
      if (status.body.isLeft) {
        Thread.sleep(interval.toMillis)
        wait()
      } else {
        val result = status.body.right.get
        if (<still not done ...>) {
          Thread.sleep(interval.toMillis)
          wait()
        } else {
          backend.responseMonad.unit(status)
        }
      }
    })
  }
```

I've looked at a solution for that based on trampolines, but that would require modifying the `trait MonadError` and thus is a _very_ invasive change. Any other projects using `sttp` with this issue?

**Comment by adamw** [comment]
I was thinking about adding a retry mechanism but I'm a bit afraid about re-inventing the wheel. It boils down to the question: at what level should the retries by done? Is it inside a backend wrapper, or maybe higher, independently from sttp?

In the second scenario, if you have `request.send(): F[Response]` for some container `F`,you can treat it is a function `() => F[Response]`. There are libraries such as https://cb372.github.io/cats-retry/docs/index.html, https://github.com/softwaremill/retry or ZIO retry (https://scalaz.github.io/scalaz-zio/overview/error_handling.html) which allow flexible retry policies. So maybe that's a good level to apply them?

As for stack safety, as `MonadError` is just a wrapper, it "inherits" the stack safety of the monad it wraps. `Try` is not stack safe, however `Future`, `Task` and `IO` are, and so the sttp monads wrapping them are as well.

**Comment by Ferada** [comment]
> I was thinking about adding a retry mechanism but I'm a bit afraid about re-inventing the wheel. It boils down to the question: at what level should the retries by done? Is it inside a backend wrapper, or maybe higher, independently from sttp?
> 
> In the second scenario, if you have `request.send(): F[Response]` for some container `F`,you can treat it is a function `() => F[Response]`. There are libraries such as https://cb372.github.io/cats-retry/docs/index.html, https://github.com/softwaremill/retry or ZIO retry (https://scalaz.github.io/scalaz-zio/overview/error_handling.html) which allow flexible retry policies. So maybe that's a good level to apply them?

I'll try that as a wrapper on the outside first, might be easier than changing library internals.

> As for stack safety, as `MonadError` is just a wrapper, it "inherits" the stack safety of the monad it wraps. `Try` is not stack safe, however `Future`, `Task` and `IO` are, and so the sttp monads wrapping them are as well.

Okay thanks.
