### ISSUE TITLE
Extend Slf4jLoggingBackend so that it allows markers to be added to logs

### ISSUE THREAD

**Issue by sebastianrozyczka** [softwaremill/sttp#1866]
Maybe it's worth to extend Slf4jLoggingBackend so that it allows you to add markers to logs. It would be much better to have this as a sttp's feature than to create a custom logging backend (wrapping slf4j) just for this need.

**Comment by adamw** [comment]
Sounds reasonable :) Can you propose some code changes that would be needed to achieve this?

**Comment by sebastianrozyczka** [comment]
Sure, I'll try to push something out. :)
