### ISSUE TITLE
HttpURLConnectionBackend ignore additional headers

### ISSUE THREAD

**Issue by alexdupre** [softwaremill/sttp#187]
eg. using `sttp.header("Origin", "http://localhost:5000").body("Test").post(...)` doesn't add the Origin header to the request.
With OkHttpSyncBackend it's addded.

**Comment by adamw** [comment]
Unfortunately that's a "limitation" of `HttpURLConnection`. See: https://stackoverflow.com/questions/13255051/setting-origin-and-access-control-request-method-headers-with-jersey-client/13266620

As a work-around, you can set the `sun.net.http.allowRestrictedHeaders` system property to `true`.

**Comment by alexdupre** [comment]
Perhaps it deserves a warning in the doc.

**Comment by adamw** [comment]
@alexdupre You are right, maybe you'd like to add this? Should be a simple PR :) All the docs are in the `docs` directory
