### ISSUE TITLE
URI interpolator does not enforce scheme

### ISSUE THREAD

**Issue by imRentable** [softwaremill/sttp#1911]
[This snippet](https://scastie.scala-lang.org/xm1PZVnkSZayzgXsvyclAA) that depends on `"com.softwaremill.sttp.client3" %% "core" % "3.8.16"` parses a URI without a scheme just fine. However, sending a request via the `HttpClientFutureBackend` using said URI throws a `java.lang.IllegalArgumentException: invalid URI scheme ...`.

I did some research and it looks like it should enforce a valid scheme when parsing.

**Comment by adamw** [comment]
The URI from the snippet: `foo-bar:8080/v1/api`, has the following components after parsing: schema = `foo-bar`, path = `8080/v1/api`. There's no authority (host+port), query or fragment.

From the point of view of the spec, this is a valid URI (see also [wikipedia](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)). However `foo-bar` is not a valid schema for the http backends, which is what the exception message states.

I think the kind of validation you have in mind would be needed if we tried to model an "HTTP URI" or a "Web URI". However, the `URI` class from sttp-model corresponds to the more general notion of "a valid URI", hence validation passes here just fine.

**Comment by imRentable** [comment]
Makes sense, thanks for the clarification @adamw.
