### ISSUE TITLE
JS artifact for ZIO module is incomplete

### ISSUE THREAD

**Issue by Iltotore** [softwaremill/sttp#1928]
The ZIO module contains two subpackages: `impl` and `httpclient`. However, the JS artifact only contains `impl`. Therefore, SJS projects using this module cannot compile.

**Comment by adamw** [comment]
The JS and JVM versions of the module contain different backend implementations; for JS, it's `FetchZioBackend`, for the JVM, it's `HttpClientZioBackend`. They delegate to different libraries under the hood (a JS and JVM one)

Can you maybe expand on what you  mean by "SJS projects using this module cannot compile"?

**Comment by Iltotore** [comment]
Here is an example taken from the docs:

```scala
//> using scala "3.3.0"
//> using lib "com.softwaremill.sttp.client3::zio::3.9.0"
//> using lib "dev.zio::zio::2.0.15"

import sttp.client3._
import sttp.client3.httpclient.zio._
import zio._

val request = basicRequest.get(uri"https://httpbin.org/get")
val sent: ZIO[SttpClient, Throwable, Response[Either[String, String]]] = 
  send(request)
```

It compiles successfully when targetting JVM (`scala-cli compile <file>`) but fails when targetting JS (adding the `--js` flag) with this error:
```
[error] .\teststtp.sc:6:8
[error] value httpclient is not a member of sttp.client3
[error] import sttp.client3.httpclient.zio._
[error]
```

Also tested with STTP 4.0.0-M4

**Comment by adamw** [comment]
You're right, this won't compile, as the httpclient backend is for JVM only. The docs generally present examples that compile under the JVM.

And indeed the JS variant is incomplete - there's no top-level `send`, which would use the layers. Something that should get fixed :) Maybe simply moving this from the JVM definition to the shared one will work?

In the meantime, for JS, you need to use another backend: https://sttp.softwaremill.com/en/latest/backends/javascript/fetch.html#zio-based

Hence, the snippet will become sth like this:

```scala
//> using scala "3.3.0"
//> using lib "com.softwaremill.sttp.client3::zio::3.9.0"
//> using lib "dev.zio::zio::2.0.15"

import sttp.client3._
import sttp.client3.impl.zio._
import zio._

val backend = FetchBackend()
val request = basicRequest.get(uri"https://httpbin.org/get")
val sent: ZIO[Any, Throwable, Response[Either[String, String]]] = request.send(backend)
```
