### ISSUE TITLE
Add default structured logging ?  

### ISSUE THREAD

**Issue by fmeriaux** [softwaremill/sttp#1932]
It would be interesting to add a structured logging backend by default (using slf4j's MDC for example). 

Among the things that would be tracked are the uri, the method, the status code... (with the possibility of enabling/disabling entries if required). 

Any comments?

**Comment by adamw** [comment]
Sure! How would you think it could integrate with the current logging infrastructure? https://github.com/softwaremill/sttp/blob/e7ed7720a3ae4389c4b755b476e94bafb26ba694/core/src/main/scala/sttp/client4/logging/Log.scala#L9

**Comment by fmeriaux** [comment]
Why not passing a `context` of type `Map[String, Any]` in the `apply` method of `Logger[F]` and using the MDC on the Slf4J implementation side, and the same for scribe which also supports the MDC? 

It has the advantage of being completely transparent for users. 

For configuration, it may not be necessary to add properties; you can always pass the context, built on the basis of the current configuration (logRequestBody, logRequestHeaders...).  As for the headers, you can also filter the `sensitiveHeaders` so as not to put them in the context. 

What do you think?

**Comment by adamw** [comment]
Sounds good, we wouldn't loose the structure then.

Is there some standardised list of attribute names for the HTTP use-case?

**Comment by fmeriaux** [comment]
As far as I know, there isn't really an established standard, unfortunately.

I can suggest something quite simple like: 

- `http.version`
- `http.method`
- `http.uri` 
- `http.status_code`

And, possibly for debugging: request headers or body?

**Comment by adamw** [comment]
Sure, adding the headers seems easy enough. The body is risky, as it might be large, but it's already optional, so maybe we can pass it optionally as well. But I'm not sure about the use-cases for that.

**Comment by fmeriaux** [comment]
For the body, I agree with you that it can be voluminous and may contain sensitive information. The only case I can imagine is for debugging. 
But it's clearly not critical.
