### ISSUE TITLE
Not able to make a sttp call with a combination of Map[String,String] and InputStream as the body

### ISSUE THREAD

**Issue by sonal1111** [softwaremill/sttp#196]
Hi ,

I have a use case in which I need to send a binary file as well as some key value pairs as a body in a single STTP POST call but I am not able to find a way to do so. As of now I am only able to send either key value pairs or an inputStream as a body to STTP calls. Is there any way to achieve my Use Case?

**Comment by adamw** [comment]
I suppose what you need to do is send a multipart request? See https://sttp.readthedocs.io/en/latest/requests/multipart.html

**Comment by sonal1111** [comment]
![image](https://user-images.githubusercontent.com/49858761/56497370-dba3a200-651a-11e9-96a1-e14fdac8d955.png)

var fileLoc = "C:/Downloads/Insight_Text_data.csv"
var file : File = new File(fileLoc)
request = sttp
        .post(uri"$uri")
        .multipartBody(multipart("form_part",body),multipartFile("binary",file))
I want to make a POST call where my body will be form-data but one of the Key field is File type and its value is a CSV file . The other key-value pairs are text type. In STTP i can only send a Map[String, String] as body. How is this achievable by multipart body? I tried using MultiPart option but my endpoint is looking for the file only as a value for the key "binary" as in the screenshot. Hence my above code is failing.

**Comment by adamw** [comment]
Maybe this will work?

```
request = sttp
  .post(uri"$uri")
  .multipartBody(
    multipart("output","json"),
    multipart("format","xls"),
    multipart("bgjob","true"),
    multipartFile("binary",file))
```

**Comment by sonal1111** [comment]
Thanks Adam, it worked but in my use case since I am working with multiple endpoints hence these multipart parameters are not same everytime. I tried making my code generic like below but it didn't worked
`val body : Map[String, Any] = Map("output"->"json","format"->"xls","bgjob"->"true","binary" -> inputStream)    // body Map will be created dynamically for each endpoint
val multiPartReq= body.map(x=> multipart(x._1,x._2)).toSeq
request = sttp
        .post(uri"$uri")
        .multipartBody(multiPartReq)
        .headers(headers)`

**Comment by adamw** [comment]
I think you just need to expand the `val multiPartReq : Seq[Multipart]` into multiple parameters and things will work fine:

```
.multipartBody(multiPartReq: _*)
```

or use an immutable sequence (the default `Seq` in Scala is mutable):

```
.multipartBody(multiPartReq.toList)
```
