### ISSUE TITLE
Release version 3 with circe upgraded to 0.14.6

### ISSUE THREAD

**Issue by awilliamsOM1** [softwaremill/sttp#1994]
I know version 3 is going to be deprecated in favor of 4. But there is a new version of circe available 0.14.6. It would be great to include the new circe version into a version 3 release to support strict dependency builds. Version 4 is still getting M releases, so until it is fully released it would be helpful to continue releasing version 3 with package upgrades. Thank you.

**Comment by adamw** [comment]
Can you prepare a PR? I'll be doing a v3 release soon (tomorrow probably)

**Comment by awilliamsOM1** [comment]
Thanks for the quick response. I put up a PR #1996 . Please let me know if you need me to do anything else. Thank you.
