### ISSUE TITLE
CatsMonadAsyncError shouldn't use eval for blocking

### ISSUE THREAD

**Issue by kciesielski** [softwaremill/sttp#1998]
Reported here: https://softwaremill.community/t/sttp-monad-monaderror-blocking-for-cats-effect/314/3

`CatsMonadAsyncError` uses the default implementation from `MonadError`:
```scala
def blocking[T](t: => T): F[T] = eval(t)
```
and `eval` is implemented as follows:
```scala
override def eval[T](t: => T): F[T] = F.delay(t)
```
So, delay is used for blocking actions.

**Comment by adamw** [comment]
Fixed here: https://github.com/softwaremill/sttp/pull/1993 :)
