### ISSUE TITLE
ZIO Streaming

### ISSUE THREAD

**Issue by loicdescotte** [softwaremill/sttp#200]
ZIO now supports streaming via scalaz-zio-streams module, so it should be possible to implement  `streamBodyToPublisher`, `publisherToStreamBody` and `publisherToBytes` methods in `AsyncHttpClientZioBackend`, to allow response streaming with ZIO backend.

ZIO also provides a scalaz-zio-interop-reactivestreams module that would help to develop this feature. 

Example : 

```scala
import scalaz.zio._
import scalaz.zio.stream._
import scalaz.zio.interop.reactiveStreams._

val stream: Stream[Throwable, ByteBuffer] = ???
stream.toPublisher
```

Or 

```scala
val p: Publisher[ByteBuffer] = ???
p.toStream
```

For `publisherToBytes`, it may be somethig like `p.toStream.foldLeft(ByteBuffer.allocate(0))(concatByteBuffers)`

**Comment by adamw** [comment]
Great! Maybe you'd like to attempt creating the module? The testsuite is already done, you just need to instantiate it with a new stream type :)

**Comment by loicdescotte** [comment]
I've started and had some compilation issues, I don't have a lot of time right time but I will retry ASAP and will ask for help on ZIO/Sttp gitter channels if needed :)
