### ISSUE TITLE
Feature request: Shorthand to receive response as R[T]

### ISSUE THREAD

**Issue by xicmiah** [softwaremill/sttp#202]
It would be nice to have an option to receive a response as `R[T]` instead of `R[Response[T]]`, in case you just want the body and don't care about metadata.

Using `.unsafeBody` helps but it's clunky at times. Options:
* `request.send().map(_.unsafeBody)` - works depending on `R[_]`, in case of `Future` requires implicit `ExecutionContext`; relies on `map` catching exceptions.
* `responseMonad.map(request.send())(_.unsafeBody)` - works on any `R[_]`, no additional imports required; relies on response monad catching exceptions; somewhat clunky.
* Pattern match on `response.body`, wrap it into `R[_]` manually - works always, needs almost an extra block of code.

The last option can be done as an implicit class:
```scala
  implicit class RichRequest[T, +S](private val underlying: Request[T, S]) extends AnyVal {
    implicit def sendUnwrap[R[_]]()(implicit backend: SttpBackend[R, S]): R[T] = {
      import backend.responseMonad

      responseMonad.flatMap(underlying.send()) { response =>
        response.body match {
          case Right(v) => responseMonad.unit(v)
          case Left(v)  => responseMonad.error(new NoSuchElementException(s"Status code ${ response.code }: $v"))
        }
      }
    }
  }
```
It would be nice to have something like that directly on `Request` or `SttpBackend`.

**Comment by adamw** [comment]
Probably out of date, changed in sttp2
