### ISSUE TITLE
Uri interpolation incorrectly percent-encodes some characters

### ISSUE THREAD

**Issue by ghost** [softwaremill/sttp#2063]
Hello. I've encountered wrong behavior of `Uri` interpolation. I've tried to to find the problem and fix it but couldn't in given time. Anyway, here is how it can be reproduced:

```
❯ scala-cli repl --dep "com.softwaremill.sttp.client3::core:3.9.2"
Welcome to Scala 3.3.1 (21.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> import sttp.client3._

scala> uri"http://test.com/path?q1=q1value&q2=q2value"
val res0: sttp.model.Uri = http://test.com/path?q1=q1value&q2=q2value

scala> val hostname = "test.com"
val hostname: String = test.com

scala> uri"http://$hostname/path?q1=q1value&q2=q2value"
val res1: sttp.model.Uri = http://test.com/path?q1=q1value&q2=q2value

scala> val params = "?q1=q1value&q2=q2value"
val params: String = ?q1=q1value&q2=q2value

scala> uri"http://$hostname/path$params"
val res2: sttp.model.Uri = http://test.com/path%3Fq1=q1value&q2=q2value
```

Notice how in the last `uri` interpolation the question mark `?` is URL-encoded as `%3F`.

**Comment by adamw** [comment]
That's because `params` is treated as a path component - whatever is embedded into an URI, isn't parsed, but treated as a component and escaped (which component is context-dependent)

If you try doing `val params = Map("q1" -> "q1value", "q2" -> "q2value")`, things should work fine.
