### ISSUE TITLE
where is basicRequest? 

### ISSUE THREAD

**Issue by acodervic** [softwaremill/sttp#2068]
where is basicRequest? 

![image](https://github.com/softwaremill/sttp/assets/57204004/1ebfbe09-ac5a-4121-8312-ec4d2d82f0a6)

I cant found basicRequest  in project source code .

**Comment by adamw** [comment]
It's over here: https://github.com/softwaremill/sttp/blob/master/core/src/main/scala/sttp/client4/SttpApi.scala#L44
I think go-to-definition should take you to the appropriate place? :)

The `SttpApi` trait is then extended by the package object: https://github.com/softwaremill/sttp/blob/master/core/src/main/scala/sttp/client4/package.scala#L3, but you can also extend it yourself to create your own imports
