### ISSUE TITLE
Parsing response body

### ISSUE THREAD

**Issue by francescaLonedo** [softwaremill/sttp#207]
I tried deserializing the response body as params setting sttp.response(asParams), and I expected a [Seq[(String, String)], Nothing] to be returned. However when I read the body.right the sequence is empty, while I expecte it to contain tuples of field-value Strings. Am I using this feature in the wrong way? I'm sure the response body shouldn't be empty because I can correctly read it when I request it as String.

**Comment by adamw** [comment]
Could you provide an example of what's returned when reading the body as a string? If you are getting an empty sequence when using `asParams` this would indicate that the original was empty ... or that something is wrong :)

**Comment by adamw** [comment]
Closing due to lack of details :)
