### ISSUE TITLE
`send()` throws exception with Async Http Client Cats backend

### ISSUE THREAD

**Issue by mmatloka** [softwaremill/sttp#209]
When I do:
```sttp
      .body(multipartRequest)
      .post(InvalidUrl)
      .response(asString.map...)
      .send())
````

with invalid url (e.g. `ps` instead of `https`) then illegal argument exception is thrown from the `send`

```java.lang.IllegalArgumentException: The URI scheme, of the URI ps://sth.com, must be equal (ignoring case) to 'http', 'https', 'ws', or 'wss')```
I would except it would be passed inside of the `F`

**Comment by adamw** [comment]
Fixed in 1.5.17
