### ISSUE TITLE
Expose AsyncHttpClient when creating AsyncHttpClientBackend

### ISSUE THREAD

**Issue by mikegpl** [softwaremill/sttp#2104]
Hello there!

I'm using AsyncHttpClientBackend in Monix flavor and I'd like to expose some metrics related to idle and active connections. I can access them via `org.asynchttpclient.AsyncHttpClient#getClientStats` but most of builders for this type of backend do not allow easy access to `AsyncHttpClient` instance used. 

With current implementation (due to `sttp.client3.asynchttpclient.AsyncHttpClientBackend#defaultConfigBuilder` being private) the only way to achieve behavior similar to `sttp.client3.asynchttpclient.monix.AsyncHttpClientMonixBackend#usingConfigBuilder`, but with possibility to register some metrics listener, is to copy implementation `sttp.client3.asynchttpclient.AsyncHttpClientBackend#clientWithModifiedOptions` and later use `sttp.client3.asynchttpclient.monix.AsyncHttpClientMonixBackend#usingClient` to build the backend. 

Do you have any advice how to approach this? Having `sttp.client3.asynchttpclient.AsyncHttpClientBackend#clientWithModifiedOptions` public sounds reasonable, but I'm not sure why it was set package-private in the first place; if making it public would be OK, I'll be happy to provide quick PR.

**Comment by adamw** [comment]
Which version of sttp are you using? There's a `usingClient` method which I think should suit your needs: https://github.com/softwaremill/sttp/blob/beba3ec1d27d045d6f8684da6877f0321f67a1f9/async-http-client-backend/monix/src/main/scala/sttp/client3/asynchttpclient/monix/AsyncHttpClientMonixBackend.scala#L200

**Comment by adamw** [comment]
Closing this as I think the functionality is there. Please reopen if something is missing
