### ISSUE TITLE
Preserve request-metadata in SttpBackendStub

### ISSUE THREAD

**Issue by jumale** [softwaremill/sttp#2106]
## Current behaviour
SttpBackendStub does not include actual metadata of the dispatched request. 
Instead it always includes `sttp.client3.Response.ExampleGet`

```scala
val testingBackend = SttpBackendStub.asynchronousFuture
  .whenRequestMatches(_.uri.path.contains("foo"))
  .thenRespond("success")

val response = basicRequest.post(uri"https://myapp.com/foo").send(testingBackend).futureValue
println(s"${response.request.method} ${response.request.uri}")
```
prints `GET http://example.com`

## Expected behaviour
It prints `POST https://myapp.com/foo`

## Impact
It makes it harder to write functional tests for integrated modules which suppose to handle the RequestMetadata in some way (e.g. error handlers which should capture and obfuscate URI).
Besides that, I think it would be nice have it just for the sake of consistency.

As far as I can see from the code, in order to support it, we only need to change one line:
```scala
class WhenRequest(p: GenericRequest[_, _] => Boolean) {
  ...
  def thenRespond[T](resp: => Response[T]): Self = {
    ...
    case r if p(r) => monad.eval(resp.copy(request = RequestMetadata(r.method, r.uri, r.headers)))
```
Unless there are other reasons I'm not aware of why it shouldn't be done like that.

**Comment by Pask423** [comment]
closed by #2146
