### ISSUE TITLE
Integrate oauth?

### ISSUE THREAD

**Issue by Fristi** [softwaremill/sttp#2110]
Hi,

While using http, you often have to deal with oauth2. There's usually some code around which manages these interactions by keeping a atomic ref with the needed token. However there is already this **great** library which does that in a generic way: https://github.com/ocadotechnology/sttp-oauth2/

Would it be an idea to integrate this into sttp it self ? Or _propose_ to transfer their repository? I think the activity is quite low, not sure if it's still active.

Great to hear you opinions, have a good day!

Pinging @majk-p @kubukoz

**Comment by adamw** [comment]
Thanks for reaching out. While I'm not sure if the current maintainers would want any ownership transfer in the first place, so that's all very hypothetical, but even if, I can't say that we would have any capacity to evolve the project further. We could plug it into our automated update / release processes (that would be a one-off task), but I wouldn't want to make any promises or take responsibility for fixing issues / adding features. So just FYI :)

**Comment by Fristi** [comment]
>  I reached out to the team to ask if they are willing to transfer the project and will update you when they respond.

Let's see what they would like :)


> I think sttp-oauth2 makes sense as a separate project. The main benefit being the separate release process and versioning. Those projects evolve at different rate and common versioning wouldn't make a lot of sense.

Agreed, but having it integrated in one active project with a release cycle which is quite it's pretty nice to see updated dependencies and new features being released if they get contributed

> We could plug it into our automated update / release processes (that would be a one-off task), but I wouldn't want to make any promises or take responsibility for fixing issues / adding features. So just FYI :)

I think having updated dependencies and an automatic release process in place is already valuable!

Thing is with some integration modules in open source world is that they are incredible valuable, it happens quite a lot that the maintainers stop it. If it's still being released and updated within another library I think it's a great win for the eco system

**Comment by majk-p** [comment]
I agree with @Fristi, having automated updates + releases is a value on it's own. The project could be marked as contribution-first.

Let's hear from current maintainers first.

**Comment by zstoychev** [comment]
Hi everyone,

I am from Ocado Technology, the maintainers of the library. Michal got in contact with us. We discussed this internally and we would be happy if `sttp-ouath2` can find a home closer to the community and to transfer ownership if there is interest to take it as we are low in capacity to be able to maintain it well.

Let us know what your thoughts are.

**Comment by Fristi** [comment]
What if we would transfer it to softwaremill anyway and get contributor permissions or alternatively integrate it into the build of sttp? Having at softwaremill has better publicity reach and therefore more likelihood to get more contributions :) Of course softwaremill would want to do this of course :)

**Comment by adamw** [comment]
I think keeping it as a separate project makes most sense. The build of sttp is big enough already :) 

Also, maybe the decision would be best made by the new maintainers? I can of course give contributor permissions if the project were to end up on our account, but https://github.com/polyvariant/ seems to be a great place as well. For publicity, we'll for sure link from the docs (I think we do already), so that should be taken care of :)

**Comment by majk-p** [comment]
If we are to maintain the project (with the help of others in Polyvariant), it would be best to do it within our own organization. We are not affiliated with SoftwareMill and do not want to give the false impression that there is any responsibility on their side.

As per visibility - transferring the project on Github should automatically redirect all links so bookmarks and search results should remain relevant. This will require a proper communication with the community as well of course.

**Comment by Fristi** [comment]
I understand, was hoping to bring more people together to bundle the efforts in all the work which has been done so far! 

I think it's already great that the work of `sttp-oauth` somewhere else ❤️

**Comment by majk-p** [comment]
> was hoping to bring more people together

We are very open to contributions!

**Comment by Fristi** [comment]
@zstoychev When would you able to transfer the repository? I've got a ZIO PR ready :)

**Comment by majk-p** [comment]
The transfer plan is ready https://github.com/ocadotechnology/sttp-oauth2/issues/477. Looking forward for your input before I proceed.

I think we can close this issue and continue there

**Comment by zstoychev** [comment]
Polyvariant looks a great option, thank you Michal for driving this!

**Comment by Fristi** [comment]
Repository has been migrated, thanks everybody for your input !
