### ISSUE TITLE
Add Scala 3 support for play-json

### ISSUE THREAD

**Issue by markarasev** [softwaremill/sttp#2138]
Hi,
Play-JSON publishes artifacts for Scala 3 since play-json 2.10.0. It would be good to be able to use it with sttp.client3 in Scala 3 natively.

**Comment by adamw** [comment]
Sure, can you maybe prepare a PR for the sttp3 branch?

**Comment by markarasev** [comment]
I'll try.

**Comment by markarasev** [comment]
Hi again, is a 3.9.6 release planned or should we wait for 4.0.0 ?

**Comment by adamw** [comment]
@markarasev no problem in adding it to v3, just prepare a PR against the `v3` branch :)
