### ISSUE TITLE
No json4s release for scala 3

### ISSUE THREAD

**Issue by dwischolek-modulon** [softwaremill/sttp#2153]
There is still no json4s binding release for scala 3. Is there something missing? A corresponding pull request #1095 was closed in 2021.

**Comment by adamw** [comment]
The PR was closed, not merged. There where some issues, maybe they are now resolved. Can you try creating another PR?

**Comment by dwischolek-modulon** [comment]
Not knowing what those issues were and not being to deep into this project, I would rather not. At least not without some more information. Maybe @nryanov does remember and can shed some light onto it.

**Comment by adamw** [comment]
Turns out it just worked
