### ISSUE TITLE
Spray json support for scala 3

### ISSUE THREAD

**Issue by MichelEdkrantz** [softwaremill/sttp#2179]
Hi, 
reaching out since my company is using spray json for a lot of things, and we also like your libraries :) 

Wanted to check regarding spray json, and scala 3 support. Spray json also has a Scala 3 build, but not linked in your sbt build. Any historic reason for this or not doing this? It might be as easy as adding scala3 below. 

If I opened a PR for this, should it be for the client3 or client4? 

```
lazy val sprayJson = (projectMatrix in file("json/spray-json"))
  .settings(commonJvmSettings)
  .settings(
    name := "spray-json",
    libraryDependencies ++= Seq(
      "io.spray" %% "spray-json" % "1.3.6"
    ),
    scalaTest
  )
  .jvmPlatform(scalaVersions = scala2)
  .dependsOn(core, jsonCommon)

```

**Comment by adamw** [comment]
Probably nobody submitted a patch yet - no other reasons, if the tests pass. Can you maybe create a PR?

**Comment by kciesielski** [comment]
> If I opened a PR for this, should it be for the client3 or client4?
I think it's worth adding for client3 and client4.

**Comment by MichelEdkrantz** [comment]
#2186
