### ISSUE TITLE
typo (jeager) in build.sbt

### ISSUE THREAD

**Issue by pjfanning** [softwaremill/sttp#2196]
https://github.com/softwaremill/sttp/blob/55bb70ca71f07fef98f012a50837a64adfc30299/build.sbt#L1106

I think this is meant to be Jaeger. GitHub search doesn't seem to have other mentions of this - so maybe it isn't used.

**Comment by adamw** [comment]
Yeah, seems not used. Can you create a PR which cleans this up maybe? :)
