### ISSUE TITLE
sttp simple could offer a better error message on jdk < 11

### ISSUE THREAD

**Issue by lbialy** [softwaremill/sttp#2249]
Related to toolkit issue: https://github.com/scala/toolkit/issues/39

This is basically an improvement proposal for ClassNotFoundException thrown when built-in java http client class is missing on jdks below 11.

**Comment by lbialy** [comment]
This has changed I think as sttp4 dropped java 8 support altogether, didn't it?

**Comment by adamw** [comment]
True :)
