### ISSUE TITLE
Support 2.13.0 Scala version

### ISSUE THREAD

**Issue by jeduardocosta** [softwaremill/sttp#227]
Update the required dependencies and also the configuration needed to support Scala version 2.13.0.

**Comment by xuwei-k** [comment]
https://github.com/softwaremill/sbt-softwaremill/pull/8

**Comment by brazosreniel60** [comment]
Opps hello everyone

**Comment by adamw** [comment]
The 1.6.0 release contains some modules published for 2.13: https://github.com/softwaremill/sttp/releases/tag/v1.6.0
