### ISSUE TITLE
Add OpenTelemetry attributes to the metrics backend

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#2292]
Currently the [OpenTelemetryMetricsBackend](https://github.com/softwaremill/sttp/blob/master/observability/opentelemetry-metrics-backend/src/main/scala/sttp/client4/opentelemetry/OpenTelemetryMetricsBackend.scala) reports a number of metrics, following the naming conventions of OpenTelemetry. 

However, we only report raw metric values, without any of the attributes as defined [here](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#http-client).

The goal of this issue is to report the metrics along with the **required** attributes. Optionally, we might include other attributes, if this is feasible and "makes sense".

The abstractions currently present in `OpenTelemetryMetricsBackend` might need updating/extending/refactoring; since this targets version 4 (yet unreleased), there are no compatibility requirements.

**Comment by varshith257** [comment]
@adamw I have experience with OTEL and my experience through an internship and contributions to OTEL and Jaeger. I am throwing my hat to crack this 
/attempt #2292

**Comment by iRevive** [comment]
> The goal of this issue is to report the metrics along with the required attributes

(copy-paste from https://github.com/softwaremill/tapir/issues/4057).

You can use OpenTelemetry [semantic conventions](https://github.com/open-telemetry/semantic-conventions) to generate specs and tests to ensure all required attributes are in place.

Here are a few examples:
- https://github.com/typelevel/otel4s/pull/773 - metric specs generator in otel4s
- https://github.com/typelevel/otel4s/blob/main/semconv/metrics/stable/src/main/scala/org/typelevel/otel4s/semconv/metrics/HttpMetrics.scala - generated spec 
- https://github.com/http4s/http4s-otel4s-middleware/pull/129/files#diff-3f8cb430fb564f7ac7cc04d5658720b1566be69f3dddaac00721f7a69955cb3aR156-R182 - the test itself

**Comment by adamw** [comment]
@iRevive thanks, this looks interesting. @varshith257 if we could use this somehow to simplify / automate the testing, that would be great

**Comment by adamw** [comment]
As we are getting first PRs for the bounties, I've published our ["How to prepare a good PR" guide](https://softwaremill.community/t/how-to-prepare-a-good-pr-to-a-library/448). I should have probably done this right away, sorry! :)
