### ISSUE TITLE
Scala Native 0.5.x in v3

### ISSUE THREAD

**Issue by nob13** [softwaremill/sttp#2301]
We are using sttp as client library in some internal project and are on the way to update Scala Native Dependencies.

Unfortunately, sttp 3.9.x relies on Scala Native 0.4.x. 

Is it possible to have an updated version with Scala Native 0.5.x?

**Comment by adamw** [comment]
Sure! Maybe you could try creating a PR for the v3 branch?

**Comment by nob13** [comment]
Will come back to you, may take some time.

- Some libs may need to be updated, but this was to be expected
- Cats Effect doesn't have support for Scala Native 0.5.x https://github.com/typelevel/cats-effect/issues/4076
- Some API calls in Scala Native 0.5.x have a different signature for Scala-2 and Scala-3 (e.g. `unsafe.Zone`)

**Comment by nob13** [comment]
Seems to blocked by https://github.com/softwaremill/sttp/issues/2243 as updating sttp-shared (with support for scala native 0.5.x) leads to transitive updates of ZIO.

**Comment by adamw** [comment]
I had to update Native in #2244 as well - so this should be done.

**Comment by nob13** [comment]
@adamw 
Oh, thank you!
