### ISSUE TITLE
Proper way to compose requests

### ISSUE THREAD

**Issue by kell18** [softwaremill/sttp#231]
Hi! Thank you for the nice library!

I faced one problem while using Sttp - it isn't clear how to compose requests on the abstract backend level (without specifying R: MonadError explicitly). For example - we need to read the data from endpointA, transform it and send it to endpointB.

What I end up with:
```scala
trait Requests[R[_]] {
    implicit val sttpBackend: SttpBackend[R, Nothing]
    implicit val monadError: MonadError[R]

    def requestA: Request[Int, Nothing]

    def requestB(arg: Float): Request[String, Nothing]

    def transform: Int => Either[String, Float]

    def epAThenB: R[Either[String, Response[String]]] = {
      monadError.flatMap(requestA.send()) { resp1 =>
        resp1.body.fold(
          error => monadError.error(
            new RuntimeException(s"epA query failed with $error, full response: $resp1")
          ),
          epAResult => {
            val epBArgs = transform(epAResult)
            epBArgs.traverse(x => requestB(x).send())
          }
        )
      }
    }
  }
```

This solution was problematic for me for a few reasons:
1. There are mostly machinery to chain requests together in the monadic fashion "send A and if successful send B" rather then an actual code. I would be so much happier if I'd be able to chain it with simple `flatMap` call.
2. And then, kind of implementation-specific problem - there is no cats.Applicative instance for sttp.MonadError, so I end up providing it myself.

What I can propose to make requests composable, given my little restricted understanding of the library:
1. Compose it on Reqest level. Add some kind of `sendAndThen` method to RequestT class, for example, to conceal all the details there.
2. Compose it on R (MonadError) level. For example with something like: `compose(r1: R[Response[T1]])(f: T1 => R[Response[T2]]): R[Response[T2]]`.

I know that it's much easier to compose such things on specific MonadError level, but we'll lose benefits of computations delay (in case of Fututre) and ability to use other backends on demand.

@adamw What do you think about this problem and proposed solutions? Maybe there are better ways to go?

**Comment by adamw** [comment]
I understand the problem, but not sure if I have a good solution :)

A `RequestT` instance is a description of a single request - a data class - so I think it wouldn't be the right place to add composition there.

The second option is the right place to define composition - as there we have access to the full response (along w/ metadata), as well as errors are handled inside the `R` monad. The best solution would be to use the one and only `Monad`/`Applicative`/... implementations for Scala, unfortunately there are multiple, so sttp can't simply depend on one :) Hence the custom (and very feature-poor) abstraction of `com.softwaremill.sttp.MonadError`

There is some support to integrate with cats, through `import com.softwaremill.sttp.impl.cats.implicits._`. Maybe using this you could make your example work with a for-comprehension? Or maybe something should be added there? The `compose` you describe is exactly a `flatMap` so hopefully we can just make it work using flatMap :)

**Comment by kell18** [comment]
Cool! I didn't know about that Cats compatibility module, thank you!

Regarding the main problem... I thought about it a lot and I think the second solution with flatMapping on the response level isn't great: we still give up on delaying computations + composition of the requests still not that simple and convenient. The first solution looks beautiful to me as for library user (composition on pure Requests level) so I worked on that idea and I end up with a simple proposal with no breaking changes to API. It is in PR#237, please have a look :)

**Comment by adamw** [comment]
Whether you give up delaying computations or not depends really on how you represent effects - you don't get this with `Future`, but you do get this with `IO` or `Task`.

I agree that the solution from the PR looks nice, but I am still hesitant to include this in sttp. This would change the idea behind `Request` from a datastructure describing a single request, to a datastructure describing a whole request-based sequence of computations. That's only a small step from defining a full monad on top of request :) (you would need an "identity" request). I don't think there would be any benefit in expressing a sequence of requests via `Request` comparing to e.g. `IO`.

So I'll hold off on merging this; maybe others will face the same problem, then we'll revisit.

**Comment by kell18** [comment]
Okay, got your point. :) Then I'll close the PR for now.

**Comment by adamw** [comment]
Closing for now
