### ISSUE TITLE
missing implicit izumi.reflect.Tag breaks build after upgrade to latest tapir and sttp

### ISSUE THREAD

**Issue by fixbits** [softwaremill/sttp#2368]
As of versions:

val sttpVersion = "3.10.0" 
val tapirVersion      = "1.11.3"
  "com.softwaremill.sttp.tapir"   %% "tapir-sttp-client"       % tapirVersion,
  "com.softwaremill.sttp.tapir"   %% "tapir-json-zio"          % tapirVersion,
  "com.softwaremill.sttp.tapir"   %% "tapir-swagger-ui-bundle" % tapirVersion,
  "com.softwaremill.sttp.client3" %% "zio"                     % sttpVersion,

the below code doesn't compile anymore.

```
import zio.Task
import zio.ZIO
import zio.ZLayer

import sttp.client3.*
import sttp.capabilities.zio.ZioStreams
import sttp.capabilities.WebSockets
import sttp.tapir.client.sttp.SttpClientInterpreter
import sttp.client3.impl.zio.FetchZioBackend

object BackendClientLive {
  val layer = ZLayer {
    for {
      backend     <- ZIO.service[SttpBackend[Task, ZioStreams & WebSockets]]
      interpreter <- ZIO.service[SttpClientInterpreter]
    } yield ()
  }

  val configuredLayer = {
    val backend = FetchZioBackend()
    val interpreter: SttpClientInterpreter = SttpClientInterpreter()

    ZLayer.succeed(backend) ++
    ZLayer.succeed(interpreter) >>> layer
  }

}
```
the error message is:

> could not find implicit value for izumi.reflect.Tag[sttp.client3.SttpBackend[zio.Task, sttp.capabilities.zio².ZioStreams &
>   sttp.capabilities.WebSockets]]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in sttp.client3.SttpBackend[zio.Task, sttp.capabilities.zio².ZioStreams &
>   sttp.capabilities.WebSockets]? e.g. def x[T: Tag, F[_]: TagK] = ....
> I found:
> 
>     zio.Tag.materialize[
>       
>         sttp.client3.SttpBackend[zio.Task, sttp.capabilities.zio².ZioStreams &
>           sttp.capabilities.WebSockets]
>       
>     ]
> 
> But macro expansion was stopped.
> 
> where:    zio  is a package in the empty package
>           zio² is a package in package sttp.capabilities
> bloop(172)

Environment:
sbt.version=1.10.6
scala version = 3.6.2
openjdk 22.0.1 2024-04-16
OpenJDK Runtime Environment GraalVM CE 22.0.1+8.1 (build 22.0.1+8-jvmci-b01)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.1+8.1 (build 22.0.1+8-jvmci-b01, mixed mode, sharing

The last working sttp version is 3.9.8, increasing to 3.10.0, while keeping the tapir version the same, breaks build
The last working tapir version 1.11.2, increasing to 1.11.3, while keeping the sttp version the same, breaks build

**Comment by adamw** [comment]
Yes, something in Izumi/ZIO broke things unfortunately. https://github.com/softwaremill/sttp/pull/2312/files#diff-32888da9198a99120cc792cbf86f6aeb0d2d648f9eec2b828322425d3ba7d811R11 should have a work-around: define the type alias, or use the one that's provided. Does this help?

**Comment by fixbits** [comment]
Hi adamw,

yes this indeed helps, thanks!

To have a complete workaround one must adapt my code as follows (just for complete reference - note the explicit type annotation at` val backend`):

import zio.Task
import zio.ZIO
import zio.ZLayer

import sttp.client3.*
import sttp.capabilities.zio.ZioStreams
import sttp.capabilities.WebSockets
import sttp.tapir.client.sttp.SttpClientInterpreter
import sttp.client3.impl.zio.FetchZioBackend

type ZioWebSocketsStreams = ZioStreams & WebSockets

object BackendClientLive {
  val layer = ZLayer {
    for {
      backend     <- ZIO.service[SttpBackend[Task, ZioWebSocketsStreams ]]
      interpreter <- ZIO.service[SttpClientInterpreter]
    } yield ()
  }

  val configuredLayer = {
    val backend:SttpBackend[Task, ZioWebSocketsStreams ] = FetchZioBackend()
    val interpreter: SttpClientInterpreter = SttpClientInterpreter()

    ZLayer.succeed(backend) ++
    ZLayer.succeed(interpreter) >>> layer
  }

}
