### ISSUE TITLE
Upgrade org.asynchttpclient:async-http-client <3.0.1 due to CVE

### ISSUE THREAD

**Issue by gergelyfabian** [softwaremill/sttp#2372]
async-http-client in versions below 3.0.1 has a new CVE (2 weeks old):

https://github.com/advisories/GHSA-mfj5-cf8g-g2fv

sttp depends on this library (even in its newest version).
Unfortunately async-http-client 2.* is not binary compatible with 3.0.1, so it's not possible to upgrade the transitive dependency when using sttp.

Could this be fixed for both client3 and client4?

**Comment by adamw** [comment]
I tried working on a PR, however AHC [removed](https://github.com/AsyncHttpClient/async-http-client/discussions/1925) reactive-streams support, which means that our streaming integrations top working. This means that modules such as `async-http-client-fs2` need to be removed, as they don't make sense.

At this point, I'm wondering if it's simply not better to switch to another backend and remove AHC altogether?

**Comment by gergelyfabian** [comment]
> At this point, I'm wondering if it's simply not better to switch to
> another backend and remove AHC altogether?
>
Thank you. This is exactly what I did. Moved to HttpClient. It's in the
cats dependency just for the record (I had a hard time finding it).

>

**Comment by gergelyfabian** [comment]
FYI, the CVE was updated: https://github.com/advisories/GHSA-mfj5-cf8g-g2fv
async-http-client 0.12.4 is not any more affected

**Comment by gergelyfabian** [comment]
> At this point, I'm wondering if it's simply not better to switch to another backend and remove AHC altogether?
> Thank you. This is exactly what I did. Moved to HttpClient (both for cats-effect and Future). The cats-effect backend is in the cats dependency just for the record (I had a hard time finding it).

Just for the record I moved to OkHttp backend, as with HttpClient there were thread pool issues.
