### ISSUE TITLE
use zio from its new organization instead of scalaz

### ISSUE THREAD

**Issue by softinio** [softwaremill/sttp#244]
Looking at the sttp codebase we are using the old version on maven of zio when it was part of scalaz organization. Best to migrate to using the new version under its own `zio` org:

https://search.maven.org/search?q=g:dev.zio

**Comment by adamw** [comment]
could be :) maybe you could make a PR with this change?

**Comment by softinio** [comment]
Will def do a PR sir once I have bandwidth :-) Using sttp for the first time its fabulous.

**Comment by adamw** [comment]
ok, done, zio updated :)

**Comment by adamw** [comment]
Released in 1.6.1

**Comment by softinio** [comment]
awesome! Thank you!
