### ISSUE TITLE
async backend .close() sequencing

### ISSUE THREAD

**Issue by aappddeevv** [softwaremill/sttp#269]
I'm unable to sequence my effects and obtain errors because I cannot sequence the close processing properly. Is there a way to get the API to provide, for async backends, some type of `closeF` (or something like that) that would allow us to obtain an async effect that completes when the backend close completes?

**Comment by adamw** [comment]
I suppose so, for a `SttpBackend[R[_], -S]` the `closeF` method could return a `R[Unit]`

However, in many cases that would amount to wrapping the result of `close` in the effect, that is wrapping the synchronous effect in the effect wrapper.

**Comment by aappddeevv** [comment]
The idea is to ensure that we can sequence our effects properly. Right now, according to the docs, the close may happen after the actual call to `.close()`, hence, the resource may still be "open" after the call.

**Comment by adamw** [comment]
Sounds good. Maybe you'd like to create a PR? For 1.x we could call it `closeF`, and fold the two methods into one for 2.x

**Comment by aappddeevv** [comment]
I'm not sure I know enough to do that. The other thing we should think about is some of the 2.13 auto closeable interfaces as well as the fairly standard bracket pattern used in alot of libraries. Perhaps some of those patterns make better sense. Let's take a breather and I'll come across those other areas shortly.

**Comment by adamw** [comment]
See the changes in the v2 branch

**Comment by aappddeevv** [comment]
I will do that.

**Comment by aappddeevv** [comment]
I think that will work.

**Comment by adamw** [comment]
Released in 2.0.0-M3
