### ISSUE TITLE
Multiple Cookie headers sent in HTTP request

### ISSUE THREAD

**Issue by tomcham** [softwaremill/sttp#279]
Per each invocation of `sttp.cookie` a `Cookie` header is added. Having multiple invocations can be useful if you are sharing a common request of some sort but want to add a certain cookie to a specific request.

RFC 6265 says that

> When the user agent generates an HTTP request, the user agent MUST NOT attach more than one Cookie header field.

**Comment by adamw** [comment]
You're right, it would make more sense for these calls to be cumulative. Maybe you would like to attempt creating a PR?

**Comment by adamw** [comment]
Released in 2.0.0-M3, thanks!
