### ISSUE TITLE
unable to properly escape chars in uri

### ISSUE THREAD

**Issue by aappddeevv** [softwaremill/sttp#287]
There are some chars that still need escaping in the URI to allow request processing such signing. One of them is the `*` character. There needs to be an easy way to change either escaping behavior or to allow a `%` escape e.g. `%%`. I think `*` is the only other char I have encountered that has this issue and it as discovered when working with AWS request signing.

**Comment by adamw** [comment]
Not sure I understand - do you mean that some characters need to be escaped in the URI, even though it's not required by the URI spec? Could you give an example?

**Comment by aappddeevv** [comment]
I need to sign AWS bound requests and *, even as a normal character, needs to be escaped although it's not in the spec. For example, [one AWS](https://github.com/rama-nallamilli/aws4-request-signer/blob/master/src/main/scala/com/rntech/RequestSigner.scala) libraries are escaping it along with the standard escapes you would expect. It's a specialized need, I've encountered a situation where I needed to double escape a URI before but that's not the case at the moment.

**Comment by adamw** [comment]
there is already a mechanism for a similar thing in the query (`QueryFragment`, which accepts different encoding strategies), so maybe we could generalise it to `PathFragment` and ... `FragmentFragment` (not the best name ;) )? 

Maybe we could come up with a single set of encoding strategies (currently members of `QueryFragmentEncoding`) which can be re-used?

**Comment by aappddeevv** [comment]
I know that my * was in the path itself vs the fragments. It may be easier to allow you to "escape" an existing % so that it is not double-escaped. That would solve it everywhere.

**Comment by adamw** [comment]
How would that look like in practice?

**Comment by aappddeevv** [comment]
Perhaps a %% in a string means the % is not to be escaped again. I don't think using a type to represent "don't escape this string" is a good idea unless you can tag the string cleanly e.g. `"blah%%2A" @@ IgnoreDoubleEscapes` :-).

**Comment by adamw** [comment]
Well introducing a `%%` means "don't escape" rule might be surprising (if you do have %% in your query). Then you'll need some way of actually escaping what normally shouldn't be escaped (... or the other way round).

Wouldn't an `Unescaped("...")` or `Literal("...")` fragment, used in the path or query be more readable? You could potentially use it in interpolation (`uri"http://x.y.z/a/${Literal("*")}`) or when hand-constructing the uri

**Comment by aappddeevv** [comment]
I don't disagree that was the first thing that came to mind. I like the typed approach.

**Comment by aappddeevv** [comment]
Oh I just hit this again...the API I'm using needs to have : escaped.

**Comment by aappddeevv** [comment]
K...it looks like it still escaping the path segments even when using the Uri case class directly.

**Comment by adamw** [comment]
@aappddeevv does the mechanism introduced in #309 (and released in 1.7.0) help?

**Comment by aappddeevv** [comment]
Argh, I think I'm getting whiplash. We should have closed either #309 or closed this issue at some point so there were not duplicates issues open at the same time...having said that...I'll have to check. I need to turn off escaping everywhere in the Uri not just path segments. If it addressed that, then I'm fine.

**Comment by adamw** [comment]
:)

well there's already a mechanism for queries, you can add arbitrary query fragments. Now it's also possible for paths. There's still no way to turn off escaping for domains/fragments, though (and schemes ;) )
