### ISSUE TITLE
allow request customization prior to send

### ISSUE THREAD

**Issue by aappddeevv** [softwaremill/sttp#290]
Currently, there is not a good way to customize requests in the layer below sttp prior to send. A similar issues exists for "HttpURLConnectionBackend, see the openConnection."

See this gitter message: [September 13, 2019 5:20 PM](https://gitter.im/softwaremill/sttp?at=5d7c081372fe1251119d9849)

**Comment by adamw** [comment]
Released in 2.0.0-M3, thanks!
