### ISSUE TITLE
The uri interpolator fails when combining IPv6address and port

### ISSUE THREAD

**Issue by ScalaBender** [softwaremill/sttp#312]
Using only the IPv6 address without specifying a port works fine: 
`uri"""http://[2001:0db8:85a3:0000:0000:8a2e:0370:7334]"""`

Using the IPv6 address together with port:
`uri"""http://[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:8080"""`
fails with:
`Exception in thread "main" java.lang.IllegalArgumentException: port specified multiple times
	at com.softwaremill.sttp.UriInterpolator$UriBuilder$HostPort$.hostPortFromTokens(UriInterpolator.scala:341)`

Building the same URI using the Uri class works fine:
`Uri("http", """2001:0db8:85a3:0000:0000:8a2e:0370:7334""", 8080)`

**Comment by adamw** [comment]
Fix released in 1.7.1
