### ISSUE TITLE
Investigate integration with Zipkin

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#329]

**Comment by adamw** [comment]
(similar to brave/prometheus)

**Comment by will-sargent-eero** [comment]
Wouldn't it be easier to provide an opentracing-api backend, and add zipkin/jaeger as implementations?

**Comment by adamw** [comment]
@will-sargent-eero yes, you are probably right :)

**Comment by will-sargent-eero** [comment]
https://github.com/Colisweb/scala-opentracing although I have not tried it myself

**Comment by ghostbuster91** [comment]
Done in #341
