### ISSUE TITLE
Encoding of URL paths is incorrect.

### ISSUE THREAD

**Issue by agourlay** [softwaremill/sttp#33]
Version: `okhttp-handler-monix` 0.0.9.

The `URI.toString` method is encoding URL paths [using](https://github.com/softwaremill/sttp/blob/master/core/src/main/scala/com/softwaremill/sttp/Uri.scala#L120) `URLEncoder.encode`.

This `String` is then used to build the `OkHttpRequest` [here](https://github.com/softwaremill/sttp/blob/master/okhttp-handler/src/main/scala/com/softwaremill/sttp/okhttp/OkHttpClientHandler.scala#L31).

As `URLEncoder.encode` is meant to encode query parameters, it can generate incorrect path for chararacters being usually encoded in queries.

The instance I ran into is regarding the character `'='` in the following URL:

`http://localhost:8080/key=something` encoded into `http://localhost:8080/key%3Dsomething`

This causes the request to fail with status code `404` as the path does not exist.

I believe it should be a rather straightforward fix.

FYI I have found some similar discussions online:
- https://stackoverflow.com/questions/724043/http-url-address-encoding-in-java
- https://github.com/dispatch/reboot/issues/23

Thank you for this nice lib 👍

**Comment by adamw** [comment]
Can you try 0.0.10? It's not using `URLEncoder` for anything except the query

**Comment by agourlay** [comment]
It works on `0.0.10`.

Thank you very much for the ultra fast fix release, I really appreciate it 👍
