### ISSUE TITLE
FileOutputStream os is not closed in FileHelpers.saveFile

### ISSUE THREAD

**Issue by FlyCoder** [softwaremill/sttp#342]
https://github.com/softwaremill/sttp/blob/1387c2d4ff00e452bd00c431980c0ef438c50128/core/native/src/main/scala/sttp/client/FileHelpers.scala#L22

This new FileOutputStream os is not closed after `transfer(is, os)`. In Linux, when I use `Uri.parse(url).map(basicRequest.get).map(_.response(asFile(f)).send())` to download an executable file, and use `Runtime.getRuntime.exec` to run it, I will catch IOException like `"error=26, Text file busy"`.
In my humble opinion, this os should be closed after `transfer(is, os)` .

**Comment by adamw** [comment]
Should be fixed in 2.0.0-M8. Thanks for reporting!
