### ISSUE TITLE
Expected behaviour of uri macro with multiple query param groups

### ISSUE THREAD

**Issue by guymers** [softwaremill/sttp#356]
Passing a string that contains multiple query parameter groups produces the following URI:
```
scala> uri"https://example.com/path?param=value?${Map.empty}".toString()
res1: String = https://example.com/path?param=value?Map()

scala> uri"https://example.com/path?param=value?${Map("key" -> "value")}".toString()
res2: String = https://example.com/path?param=value?Map(key+-%3E+value)

scala> uri"https://example.com/path?param=value?key=value".toString()
res3: String = https://example.com/path?param=value?key&param=value
```
Is this expected or should multiple query parameter groups be combined or maybe even error?

**Comment by adamw** [comment]
The last one is definitely a bug - an uri without any expressions should result in the same value after parsing & serialising. In the query part, `?` doesn't have any meaning (except for the initial one, which delimits them).

Though I'm wondering how you got there - what are these "multiple query parameter groups"?

**Comment by guymers** [comment]
Using two variables with the first one containing a `?`: `uri"${path}?${params}` (wasn't a smart thing to do)

**Comment by adamw** [comment]
Closing as interpolation only works for correctly formatted parameters; if the expressions are in random places, we can't do much
