### ISSUE TITLE
Remove hard dependency on Blaze in the http4s module

### ISSUE THREAD

**Issue by Baccata** [softwaremill/sttp#377]
As a developer, I greatly appreciate the interop with http4s. However, I would prefer if sttp wasn't forcing the Blaze client onto my classpath

Would you consider either : 

 * Remove the hard dependency on the blaze-client artifact, in favour of the generic client artifact ? That'd be my personal preference, but it would mean a non-backward compatible change in the sense that a couple helper constructors would have to be removed. 
*  If you're absolutely against making this small breaking change, make the blaze-client dependency "% Optional" ?

**Comment by adamw** [comment]
I'm not that familiar with http4's module structure, but I suppose `usingClient` would remain, and `usingClientBuilder` and `usingDefaultClientBuilder` would be eliminated?

One feature I'd like to keep is to have a "quick start" path where I could just do `Http4sBackend()` or `Http4sBackend.resource` and get a backend which I can use - without having to initialize other components as well. Would this be achievable without the blaze-client dependency?

**Comment by Baccata** [comment]
> I'm not that familiar with http4's module structure, but I suppose usingClient would remain, and usingClientBuilder and usingDefaultClientBuilder would be eliminated?
 
Exactly  

> One feature I'd like to keep is to have a "quick start" path where I could just do Http4sBackend() or Http4sBackend.resource and get a backend which I can use - without having to initialize other components as well. Would this be achievable without the blaze-client dependency? 

My subjective opinion is that http4s ain't really the kind of client you want to get quick-started with. However, I do appreciate the fact that your users might hold a different opinion. There's a few solutions I can think of for this : 

1. As stated previously, making the dependency "Optional" in your sbt build [here](https://github.com/softwaremill/sttp/blob/master/build.sbt#L474) and adding `"org.http4s" %% "http4s-client" % version` as a mandatory dependency would probably do the trick, at the cost of having to document that users should add the `http4s-blaze-client` themselves to their own builds. 

2. Split the current http4s module into `http4s`and `http4s-blaze`, and put the blaze-specific quickstart method in the `http4s-blaze` module.

**Comment by adamw** [comment]
Maybe the quick-start wouldn't be a long-term solution, but when you are trying out a library, and would like to explore the API - see what it can do - then it's definitely useful :)

Anyway, I'm fine with the optional dependency approach + documentation. Could you maybe prepare a PR?

**Comment by Baccata** [comment]
> Could you maybe prepare a PR? 

Will do :+1:

**Comment by adamw** [comment]
Done, will be released in 3.0.0-RC14

**Comment by adamw** [comment]
Sorry, RC15 :)

**Comment by Baccata** [comment]
cool ! sorry, I never got around to doing it myself 😢

**Comment by adamw** [comment]
no worries ;) Only took a year ;)
