### ISSUE TITLE
sttp2: Uri.parse does not fail on invalid URIs

### ISSUE THREAD

**Issue by bmarinovic** [softwaremill/sttp#396]
The safe `Uri.parse` function does not fail on invalid URIs.

Examples:
-  `Uri.parse(" ")` returns `Right(http://%20)`
- `Uri.parse("https:/ /uri")` returns `Right(http://https%3A%2F%20%2Furi)`

Expected: `Left("Invalid URI")` or some similar message

Also, not sure if this is expected behavior, but this prefixes invalid protocol with valid protocol and also succeeds:
- `Uri.parse("ttps:/www.google.com")` returns `Right(http://ttps%3A%2Fwww.google.com)`

**Comment by adamw** [comment]
I understand why this might be surprising, but should `Uri.parse("somehost")` parse as `http://somehost`? That is, if unspecified we use the http protocol, and assume the first token is a host?

The same is happening with `Uri.parse(" ")`. The string is encoded (to `%20`) and this is assumed to be the host.

**Comment by ghostbuster91** [comment]
Shouldn't we trim the input before encoding?

**Comment by adamw** [comment]
That would solve `" "` (hopefully ;) ). Still, wouldn't solve `https:/ /uri`

**Comment by kusamakura** [comment]
My issue here https://github.com/softwaremill/sttp-model/issues/2 seems to be pointing at the same surprising behavior.
I didn't realize that `uri"abcdef"` would default to `http://abcdef`. I think that it's handy to have this, but maybe it's also good to have a stricter parser that would require the scheme to be present. What do you think?

**Comment by adamw** [comment]
Thinking about this issue, I'm leaning towards requiring the scheme. As you said, why should `http` be the default, and not `https`. I think it's a sane requirement, and as you write, having this implied is suprising.

**Comment by adamw** [comment]
Of course PRs are welcome :) This would probably be a change both to the interpolator and `Uri.parse`, which I think simply calls the interpolator.

**Comment by kusamakura** [comment]
@adamw I'd love to take on this issue if it's alright :)

**Comment by adamw** [comment]
Sure, go ahead :)

**Comment by kusamakura** [comment]
I think I got the `uri" "` case down by trimming the parts of the string context in the interpolator, but work for scheme validation seems a bit more involved. For instance, I expect `mailto:test@test.com` to work just fine. Right now, it's treated as `http://mailto:test@test.com`. With softwaremill/sttp-model#3, it's `mailto://test@test.com`, which works fine, but is still not ideal – there's no authority for `mailto`, and the email address is just the path.

I found out that the `//` part is optional, and denotes the optional authority if it's present. However, some URI schemes don't require an authority, such as `mailto`. For the interpolator to know which ones require that, we'll have to add a list of common schemes. Considering the context in which this library is used, I think it's an okay compromise to support the usual cases (`http`, `https`, `ftp`, `sftp`, etc.). What do you think, @adamw?

**Comment by adamw** [comment]
Sure, makes sense. Would be great if we could also make it work well for ftp/mailto etc.
I suppose by default the authority would be optional, with special-casing for http, ftp which would require it?

Btw.: in the `mailto:test@test.com` case, I suppose the uri consists of the scheme and a single path component, equal to `test@test.com`?

**Comment by kusamakura** [comment]
Sorry for the late reply. Yeah, I was thinking that the authority should be optional by default, and then we can have a list of schemes that require it.

And yes, for `mailto`, it's exactly that: scheme + path. That's usually the case for custom URIs as well, such as `isbn` or `news`.

So the work I think will be in the tokenizer, where we start with scheme, and then branch off the tokenizers depending on whether the scheme requires an authority or not.

**Comment by Pask423** [comment]
As first case handling is implemented in https://github.com/softwaremill/sttp-model/pull/194 and meanwhile we added relative URL handling - second case is valid thought contains unnecessary empty space.
If we start adding such corner-cases we'll end up with 1000 if-s which is not the best option in the long term.
