### ISSUE TITLE
OpenTracing: Propagate span with a tag

### ISSUE THREAD

**Issue by Krever** [softwaremill/sttp#398]
Currently `OpenTracingBackend` relies on span marked as active in the `Tracer` when creating a new span. This is correct yet not very convenient for use cases which dont use this method of span propagation. 
Alternative could be to have a specific sttp tag used for setting up the span which should be used a parent and fallback to tracer when its missing.

WDYT?

**Comment by ghostbuster91** [comment]
I don't know opentracing well enough to tell whether it is a good/common way of span propagation in which you do not have active parent span in the tracer. 

However maybe this is not important here. This change will make `OpentTracingBackend` more flexible which is generally a good idea in my opinion.

**Comment by ghostbuster91** [comment]
Closing as done
