### ISSUE TITLE
ClassCastException when using `thenRespondNotFound`

### ISSUE THREAD

**Issue by arjun-1** [softwaremill/sttp#406]
My production code deserializes a request if it the response was successful (since `asJson` :
```
def execute[A](request: SttpRequest[A]) =
  request.send.flatMap(response =>
    response.body match {
      case Left(HttpError(body)) =>
        Task.fail(MomaError.UnexpectedStatusCode(response.code, body))
      case Left(DeserializationError(_, error)) =>
        Task.fail(MomaError.DecodeError(error.getMessage))
      case Right(value) => Task.succeed(value)
    }
  )

def getNodeUrl(sessionId: String) = execute(
  basicRequest
    .get(
      uri"someUrl"
    )
    .response(asJson[Uri])
)
```
I have a test which mocks a notFound response using the `thenRespondNotFound()` method:
```
sttpBackendStub.whenAnyRequest.thenRespondNotFound
```
However, this makes my test fail with an exception:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class sttp.client.ResponseError (java.lang.String is in module java.base of loader 'bootstrap'; sttp.client.ResponseError is in unnamed module of loader sbt.internal.LayeredClassLoader @538cbf70))
```
After doing some debugging, the problem seems to be that `asJson` should return an `Left(HttpError(body))`, it's actually `Left(body)` (with `body` being `"Not found"`).

If I rewrite my test to
```
sttpBackendStub.whenAnyRequest.thenRespond(
  Response(
    Left(HttpError("Not found")),
    StatusCode.NotFound
  )
)
```
it works.

**Comment by adamw** [comment]
I cannot reproduce your problem - could you maybe post a failing example, with the way you setup the stub and the request you're sending?

**Comment by arjun-1** [comment]
Hi @adamw . Sure, no problem :)
I've created the following repo which demonstrates the problem: https://github.com/arjun-1/failing-sttp-test

**Comment by adamw** [comment]
Can you try 2.0.0-RC6? I think I wasn't able to reproduce the issue as it was fixed in that version ;)

**Comment by arjun-1** [comment]
@adamw indeed updating the dependencies fixed the issue :). Thanks
