### ISSUE TITLE
Use cats' MonadError instead of providing your own

### ISSUE THREAD

**Issue by vilunov** [softwaremill/sttp#409]
Hi!

sttp in both major versions has its own `MonadError[F]` definition and its implementations ([doc](https://www.javadoc.io/doc/com.softwaremill.sttp.client/core_2.12/latest/sttp/client/monad/index.html)). Meanwhile, cats already have a definition of `MonadError[F, T]`, which is generalization of sttp's typeclass for `T=Throwable` [doc](https://typelevel.org/cats/api/cats/MonadError.html).

In my code where I have to use both of these type classes for my own type constructors, and I feel like defining instances for both of them is a bit anti-ergonomic. Would it be too bad for sttp to depend on cats-core and its type classes?

**Comment by adamw** [comment]
I don't like duplication either, however one of the assumptions of sttp is to have a minimal number of dependencies. As there are akka, scalaz, zio and java-native modules, depending on cats isn't a necessity.

There's an integration module, however, with implicits to convert the cats MonadError to the sttp one: https://github.com/softwaremill/sttp/blob/master/implementations/cats/src/main/scala/sttp/client/impl/cats/implicits.scala

They probably should be documented, though :)

**Comment by vilunov** [comment]
While I don't really understand the need for minimal dependencies, knowing that cats is quite good at binary compatibility, there is a good place a between – non-orphan implicit conversions with optional dependencies, see [article here](https://blog.7mind.io/no-more-orphans.html). That way you don't need to depend on additional integration module and import implicits.

**Comment by adamw** [comment]
Most applications have many dependencies, each is a cost, and transitive dependencies only multiply that :)

Anyway - the trick with optional dependencies might work, but then the library would behave differently depending on what's on your classpath. That is, code that compiles, could stop compiling for non-obvious reasons once you remove or change something on the classpath.

I'll keep things as-is for now, as this impacts only situations where you write custom backend wrappers - and these are in some part served by the cats integration module.

However, I'll also keep this issue open, if there's more people that would like this change, we'll reconsider then.

**Comment by LGLO** [comment]
Cats dropped support of Scala 2.11 in September, at least that's what I can see in maven repository.

**Comment by adamw** [comment]
Since we are supporting akka/cats/zio/scalaz, closing the issue as won't fix.
