### ISSUE TITLE
Unified way of accessing response body in case of failure.

### ISSUE THREAD

**Issue by Krever** [softwaremill/sttp#424]
It would be nice if there was a unified way of getting body out of `Response[Either[ResponseError[E], T]]`, especially in case of failure. 
Possible solutions: 

-  Add `body: String` to `ResponseError` which would translate to `HttpError#body` and `DeserializationError#original`
- Add `rawErrorBody: String` to `Response` - this probably have some far going implications, especially when request is consumed as stream

**Comment by adamw** [comment]
The first is easy - done :)

The second is not possible. If you always need the body as string, create a response specification which will read the result as a e.g. `(String, T)`

For example: `asStringAlways.map(s => (s, ResponseAs.deserializeWithError(deserializeJson)(s)))`

**Comment by adamw** [comment]
(1) released in 2.0.0-RC8

**Comment by Krever** [comment]
Awesome, thank you!
