### ISSUE TITLE
Error with the example in the doc.

### ISSUE THREAD

**Issue by wpoosanguansit** [softwaremill/sttp#425]
I am following the doc for:

```
AsyncHttpClientZioBackend()
    .flatMap { implicit backend =>
      val localhostRequest = basicRequest
        .get(uri"http://localhost/test")
        .response(asStringAlways)

      val sendWithRetries: ZIO[Clock, Throwable, Response[String]] = localhostRequest
        .send()
        .either
        .repeat(
          Schedule.spaced(1.second) *>
            Schedule.recurs(10) *>
            Schedule.doWhile(result => RetryWhen.Default(localhostRequest, result))
        )

      sendWithRetries *> backend.close()
    }
```

And I am getting the errors:

Error:(22, 29) type mismatch;
 found   : zio.Schedule[Any,Either[Throwable,sttp.client.Response[String]] with sttp.client.Response[String],Either[Throwable,sttp.client.Response[String]] with sttp.client.Response[String]]
 required: zio.Schedule[zio.clock.Clock,Either[Throwable,sttp.client.Response[String]],sttp.client.Response[String]]
            Schedule.doWhile(result => RetryWhen.Default(localhostRequest, result))

The version of ZIO might be too recent.  I am just not sure how to help out the type inference to point to the env Clock.

```
libraryDependencies ++= Seq(
  "com.softwaremill.sttp.client"  %% "core"                           % "2.0.0-RC8",
  "com.softwaremill.sttp.client"  %% "async-http-client-backend-zio"  % "2.0.0-RC8",
  "dev.zio"                       %% "zio"                            % "1.0.0-RC17",
  "dev.zio"                       %% "zio-streams"                    % "1.0.0-RC17"
)
```

Thank you for your help.

**Comment by adamw** [comment]
You're missing the `.absolve` from the example :) the last step. 

It's needed as we first convert a `ZIO[R, Throwable, T]` into a `ZIO[R, Nothing, Either[Throwable, T]]` - as we need to retry depending on both the exception & the return value. That's done using `.either`.

After the retries are done, we once again push the exceptions back to the error branch of `ZIO` using absolve, removing the `Either`.

The docs are sometimes broken, but here's a version which should always compile: https://github.com/softwaremill/sttp/blob/master/examples/src/main/scala/sttp/client/examples/RetryZio.scala

**Comment by wpoosanguansit** [comment]
Thank you, Adam.  With that code, I do see inference errors in Intellij.  But I manage to compile and run it.  But I ran into this errors:

```
A checked error was not handled.
()

Fiber:Id(1580889043819,10) was supposed to continue to: <empty trace>

Fiber:Id(1580889043819,10) execution trace:
  at zio.Schedule.check(Schedule.scala:238)

Fiber:Id(1580889043819,10) was spawned by:

Fiber:Id(1580889043818,8) was supposed to continue to: <empty trace>

Fiber:Id(1580889043818,8) ZIO Execution trace: <empty trace>

Fiber:Id(1580889043818,8) was spawned by:

Fiber:Id(1580889043021,1) was supposed to continue to:
  a future continuation at zio.ZIO.zipWithPar(ZIO.scala:1574)
  a future continuation at zio.ZIO.repeatOrElseEither(ZIO.scala:1103)
  a future continuation at zio.ZIO.repeatOrElse(ZIO.scala:1086)
  a future continuation at zio.ZIOFunctions.absolve(ZIO.scala:1666)
  a future continuation at com.playground.inqluziv.main.Main$.run(Main.scala:27)
  a future continuation at com.playground.inqluziv.main.Main$.run(Main.scala:29)

Fiber:Id(1580889043021,1) execution trace:
  at zio.ZIO.zipWithPar(ZIO.scala:1572)
  at zio.ZIOFunctions.fiberId(ZIO.scala:2054)
  at zio.ZIOFunctions.descriptor(ZIO.scala:1874)
  at zio.ZIO.repeatOrElseEither(ZIO.scala:1110)
  at zio.ZIO.zipWithPar(ZIO.scala:1575)
  at zio.UIO$.effectSuspendTotal(UIO.scala:189)
  at zio.ZIO.zipWithPar(ZIO.scala:1575)
  at zio.internal.FiberContext.await(FiberContext.scala:678)
  at zio.ZIO.zipWithPar(ZIO.scala:1574)
  at zio.ZIO.zipWithPar(ZIO.scala:1572)

Fiber:Id(1580889043021,1) was spawned by:

Fiber:Id(1580889042876,0) was supposed to continue to:
  a future continuation at zio.App.main(App.scala:57)
  a future continuation at zio.App.main(App.scala:56)

Fiber:Id(1580889042876,0) ZIO Execution trace: <empty trace>

Fiber:Id(1580889042876,0) was spawned by: <empty trace>

Process finished with exit code 1
```

How do I add error handling into this code?  Appreciate your help.

**Comment by adamw** [comment]
I think you might want to modify the `sendWithRetries` process description, e.g.:

```
val sendWithRetriesHandleErrors = sendWithRetries.catchAll(_ => IO(...))
```

or `.catchSome`. Let me know if this helped :)

**Comment by wpoosanguansit** [comment]
I did have this:

```
val sendWithRetries: ZIO[Clock, Throwable, Response[String]] = localhostRequest
            .send()
            .either
            .repeat(
              Schedule.spaced(1.second) *>
                Schedule.recurs(5) *>
                Schedule.doWhile(result => RetryWhen.Default(localhostRequest, result))
            )
            .absolve
            .catchAll(_ => RIO.effect(Response.ok("ok")))
```

But the errors still get thrown like before.  Should this not just gracefully retry and just return ok?  Thank you for your help.

**Comment by adamw** [comment]
So this in fact does return the `"ok"` response (try adding `.map(x => println("Response: " + x))` just to debug this quickly)

But still the fiber error gets logged, despite the catchAll - not sure why, you'll have to ask on ZIO's discord I think

Let me know when you'll have an answer, this might be useful to include here :)

**Comment by adamw** [comment]
I'll keep this issue open for now until we know why the fiber get logged

**Comment by wpoosanguansit** [comment]
Thanks Adam.  Will do.

**Comment by wpoosanguansit** [comment]
I have got this from @dapperware on ZIO's dicord:

this is a known issue that the fiber still logs even if it is handled, it should be fixed in latest master. If you look above there are some other people with similar issues. You should be able to turn off tracing for it I think.

I just couldn't find the post and I still yet to find out how to turn the tracing off.

**Comment by adamw** [comment]
Ah :) I think you turn off tracing with `.untraced` on the effect

**Comment by wpoosanguansit** [comment]
I quick test I did.  It still fails with:

code:

            .catchAll(_ => RIO.effect(Response.ok("ok")))
            .untraced

in the shell:

Fiber failed.
A checked error was not handled.
()

Fiber:Id(1580920609343,10) was supposed to continue to: <empty trace>

Fiber:Id(1580920609343,10) ZIO Execution trace: <empty trace>

Fiber:Id(1580920609343,10) was spawned by: <empty trace>

**Comment by wpoosanguansit** [comment]
I did it with 

sendWithRetries.untraced

and on send

.send().untraced

Those didn't change anything.  Were they the places that are considered effects?

**Comment by adamw** [comment]
That's what I would try. Maybe there's a problem with turning tracing off as well :)
