### ISSUE TITLE
Support exceptions in SttpBackendStub

### ISSUE THREAD

**Issue by gabbah** [softwaremill/sttp#43]
Would be nice if something like this was supported:
```scala
implicit val testingBackend: SttpBackendStub[Future, Nothing] = SttpBackendStub(AkkaHttpBackend())
    .whenRequestMatches(_.uri.path.nonEmpty)
    .thenRespond(throw SomeException("Timeout or something else happened"))
```
This way you can write tests that describes certain cases, such as timout or connection errors.

**Comment by adamw** [comment]
Please test 1.0.3 & see the docs at http://sttp.readthedocs.io/en/latest/testing.html!
