### ISSUE TITLE
WebSocket support for ScalaJS

### ISSUE THREAD

**Issue by ghostdogpr** [softwaremill/sttp#432]
As far as I understand, the only backends for ScalaJS are the Fetch-based ones and they don't support WebSockets. Would it be possible to have a ScalaJS backend that supports WebSockets?

**Comment by adamw** [comment]
Sure, the websocket handlers are quite flexible, so there are no technical barriers :) 

The only barrier is the need for somebody to code this :)

**Comment by ghostdogpr** [comment]
Okay, I might give it a try when it’s the last blocker for caliban-client to support subscriptions with ScalaJS. 

In the meantime, if anyone wants to tackle this, feel free 😄🙏

**Comment by adamw** [comment]
Released in 3.1.7
