### ISSUE TITLE
sttp2: Incorrect SttpBackendStub contruction example in documentation

### ISSUE THREAD

**Issue by bmarinovic** [softwaremill/sttp#434]
Documentation states that `SttpBackend` can be created by providing the "real" backend, e.g.: 
`SttpBackendStub(AsyncHttpClientZioBackend())`
which is incorrect since `SttpBackend.apply` takes `SttpBackend`, but `AsyncHttpClientZioBackend()` returns `zio.Task[SttpBackend]`.

**Comment by adamw** [comment]
This is fixed by changing the way backend stubs are created in 2.0.0-RC10. You should now use `AsyncHttpClientZioBackend.stub`, which creates an empty stub with the correct type parameters.
