### ISSUE TITLE
Support raw json in Response

### ISSUE THREAD

**Issue by gabbah** [softwaremill/sttp#44]
Would be useful if you can test that a json response is decoded and handled correctly.

Something like:
```scala
implicit val testingBackend: SttpBackendStub[Future, Nothing] = SttpBackendStub(AkkaHttpBackend())
    .whenRequestMatches(_.uri.path.nonEmpty)
    .thenRespond(json"{ 'myjson' : 'here' }")
```

**Comment by adamw** [comment]
Please test 1.0.3 & see the docs at http://sttp.readthedocs.io/en/latest/testing.html!
