### ISSUE TITLE
Publish circe module for ScalaJS with Scala 2.13

### ISSUE THREAD

**Issue by ghostdogpr** [softwaremill/sttp#442]
The circe module for ScalaJS is published only for 2.11 and 2.12. (see https://repo1.maven.org/maven2/com/softwaremill/sttp/client/)

I'm building a library that depends on it, so this is preventing me to release on 2.13 as well. It seems to have been disabled because of test issues. @yoohaemin and I tried to add it back in #436 and didn't see any error, but we found unrelated tests to be flaky.

Any way we could get this published?

Thanks in advance!

**Comment by adamw** [comment]
Released in 2.0.0-RC10. Some tests are still flaky, but less ;)

**Comment by ghostdogpr** [comment]
Awesome!
