### ISSUE TITLE
Support websockets in SttpBackendStub

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#443]
Currently websockets are unsupported:

```
class SttpBackendStub[F[_], S] private (
    monad: MonadError[F],
    matchers: PartialFunction[Request[_, _], F[Response[_]]],
    fallback: Option[SttpBackend[F, S, NothingT]]
) extends SttpBackend[F, S, NothingT] { // TODO
```

(note the TODO for the `NothingT` type parameter which specifies what kind of websockets are supported).

The backend stub could return a user-provided websocket handler stub. Additionally, a stub could be provided for the high-level `sttp.client.ws.WebSocket` implementation.

**Comment by ghostbuster91** [comment]
Closing as done
