### ISSUE TITLE
Feature Request: ResponseAs instances with error rethrown into F[_]

### ISSUE THREAD

**Issue by xicmiah** [softwaremill/sttp#451]
My usecase:
* I don't have different handling for response errors, be it connection error, non-2xx response, or unparsable body.
* End result just needs to have a good error message, it's going to be lifted into `F[_]` anyway.
* In case of non-2xx, having both response code and error body is really helpful. Calling `.map(_.unsafeBody)` in sttp1 worked for that purpose (impure, but works for `Id`, `Future`, or monix `Task`).

I can suggest having a group of `ResponseAs[F[T], _]` instances, for example
```scala
def asStringF[F[_]](implicit backend: SttpBackend[F, Nothing, NothingT]): ResponseAs[F[String], Nothing] = ???
```

Usage becomes
```scala
request
  .response(asStringF)
  .send() // F[Response[F[String]]]
  .flatMap(_.body) // F[String]
  .flatMap(parseBody) // F[Domain]; for example, io.circe.parser.decode[T] with some lifting
```

Sample implementation for `asStringF`: https://gist.github.com/xicmiah/0170570ba85c6d8d9cabec732c3cb80a
Notes:
* Implicit backend should probably be implicit `MonadError` instead, the latter isn't in implicit scope yet.
* `FullHttpError` is only used for response body, it can be replaced with existing `HttpError`

**Comment by adamw** [comment]
Makes sense. There are two options with the backend:
* accept an implicit backend
* add an implicit on `MonadError` which returns an implicit monad given an implicit backend.

The former is more straightforward, but the latter seems closer to the true needs of the `asXxxF` description.

Could you maybe prepare a PR?

**Comment by xicmiah** [comment]
Sure, I'll try to make a PR this week.

**Comment by frekw** [comment]
For ZIO, something like this works fine:

```scala
import sttp.client._
import sttp.client.circe.
import io.circe._
import zio._

def asJsonF[T: Decoder: IsOption]: ResponseAs[Task[T], Nothing] = asJson[T].map {
  case Left(error)  => Task.fail(error)
  case Right(value) => Task.succeed(value)
}

sttpClient.send(req.response(asJsonF[A]).flatMap(_.body) // => ZIO[Any, Throwable, A]
```

**Comment by ghostbuster91** [comment]
As we are extending response handling possibilities in https://github.com/softwaremill/sttp/pull/620 I'm not sure if it is a good idea to duplicate every possible responseAs handling with it's `F` equivalent. Maybe we could just add a `liftF` method to the `ResponseAs` class?

It would only make sense to invoke such method if there is an instance of monad error for given `T` from `ResponseAs` as other methods e.g. `asJsonAlwaysUnsafe` already fail within the terms of given effect.

That way we will be able to control what is being emitted as error:
e.g.
`asJson[Result].liftF` will throw `ResponseError` which might be either `HttpError` or `DeserializationError`
`asJsonAlways[Result].liftF` will throw only `DeserializationError`

and last but not least:
`either(asJsonAlways[MyErrorModel], asJsonAlways[Result]).liftF` will result in either `HttpError` with parsed `MyErrorModel` or `DeserializationError` being thrown (apart from other exceptions which might be thrown as well).

When it comes to zio we might want to lift errors into error channel by converting it to `IO[E,T]` , as later error type `E` can be eliminated by using standard zio operators.

**Comment by adamw** [comment]
In `v3`, this is now implemented using `failLeft`, which for response specifications of the shape `Either[A, B]` throws the `A` exception (or wraps it with `HttpError`, if it's not an exception), or return `B`.

So the original use-case would become: `asString.failLeft: ResponseAs[String, Any]`. The resulting exception will contain the original request (due to wrapping with `SttpClientException`), and the status code in `HttpError`.

Similarly, `asJson.failLeft` implements the json case.
