### ISSUE TITLE
Support Scala.js 1

### ISSUE THREAD

**Issue by a1russell** [softwaremill/sttp#454]
[Scala.js 1.0.0 has been released.](https://www.scala-js.org/news/2020/02/25/announcing-scalajs-1.0.0/) Could you please publish a build that supports it?

**Comment by adamw** [comment]
Yes, as soon as possible. There's no monix and fs2 for sjs1, so I think it will be better to wait until those get released (hopefully soon), rather than disabling them

**Comment by adamw** [comment]
The linked issues for monix would be https://github.com/monix/monix/issues/1131, and fs2: https://github.com/functional-streams-for-scala/fs2/issues/1778

**Comment by cheleb** [comment]
I could not wait :D ( #StayAtHome syndrom )
https://github.com/softwaremill/sttp/pull/495

**Comment by trywe-ltd** [comment]
Hi - any ETA on a new release containing the sjs 1.0 update? I think both the dependencies cited above are now done and released.
