### ISSUE TITLE
Cats-effect version is wrong

### ISSUE THREAD

**Issue by ghostdogpr** [softwaremill/sttp#457]
@adamw during the last release, I think you accidentally changed the cats-effect version from 2.0.0 to 2.0.1 while changing the version of sttp: https://github.com/softwaremill/sttp/commit/d1d0285dfbf8f232c4273d5d14301eaa9e5ace22#diff-fdc3abdfd754eeb24090dbd90aeec2ceR316

That version doesn't exist for Scala 2.11 so loading sttp in sbt fails.

**Comment by adamw** [comment]
Ah :D good one ... I'll have to fix the script in sbt-softwaremill.

Anyway, fixed, along with using different versions of cats-effect for 2.11/2.12+: https://github.com/softwaremill/sttp/commit/fc97587d87ed41830abbdf051301c4c0d192eccd

Thanks for spotting this!
