### ISSUE TITLE
Uri with original masking

### ISSUE THREAD

**Issue by Paulymorph** [softwaremill/sttp#474]
In brief: I would like to have access to the preinterpolated version of `uri`.

I want to get metrics for my SttpBackends grouped by paths. Requests like `GET /users/123` and `GET /users/1234` should be grouped together. I had a look at [PrometheusBackend](https://sttp.softwaremill.com/en/latest/backends/wrappers/prometheus.html) where I would have to keep the masks of paths `/users/{}` somewhere. I also would have to write interpreters of the masks to match a given request to the mask and handle the cases when they do not match. 
I thought, it would be nice if I could extract the original mask of the uri from the request on its creation.
If you have a look at the [Uri documentation](https://sttp.softwaremill.com/en/latest/model/uri.html) you will notice, the mask is already there.
I create all the requests in such a way:
```scala
val baseUrl = "http://my.address.com/api" // actually goes from config
val userId = 123
val uri = uri"$baseUrl/users/$userId"
basicRequest.get(uri)
```
I would be pretty happy if I could retrieve the original `uri` string without substitutions
```scala
uri.originalMask // "$baseUrl/users/$userId"
```
And the masking for metrics will be trivial to write.

What do you think about such a feature?

**Comment by adamw** [comment]
I understand the rationale but I think it would be quite tricky to implement. Definitely not trivial :)

**Comment by adamw** [comment]
After the `Uri` instance is created, the interpolation information is lost - it's not possible to determine, what was coming from interpolated values, and what from string constants. So this would require a separate interpolator, and a separate `UriWithMetadata` abstraction, which is outside of our scope.
