### ISSUE TITLE
cats-effect diverging implicit expansion error

### ISSUE THREAD

**Issue by abdolence** [softwaremill/sttp#476]
I created a very simple test app with cats-effect and sttp:

```scala
  import cats._
  import cats.syntax._
  import cats.implicits._
  import cats.effect.implicits._
  import cats.effect.syntax._
  import scala.concurrent.ExecutionContext.Implicits.global

  import sttp.client.asynchttpclient.cats.AsyncHttpClientCatsBackend

  AsyncHttpClientCatsBackend().flatMap { implicit backend => ??? }
````

And it doesn't compile with

> diverging implicit expansion for type cats.effect.Concurrent[F]

Is this version or documentation problem? It seems it's looking for some implicits that aren't defined.

(I don't see anything special at your docs here as well: https://sttp.readthedocs.io/en/stable/backends/catseffect.html)

Scala: 2.13.1
cats-core: 2.1.1
cats-effect: 2.1.2
sttp: 2.0.6

It seems working if you specify it like this:

```scala

implicit val cs: ContextShift[IO] = IO.contextShift( scala.concurrent.ExecutionContext.global )
AsyncHttpClientCatsBackend[IO]().flatMap { backEnd => ??? }

```

**Comment by adamw** [comment]
Definitely a documentation problem :) You need to specify the effect type explicitly, I don't think it can be inferred. Maybe you could fix the docs & create a PR?

**Comment by abdolence** [comment]
> Definitely a documentation problem :) You need to specify the effect type explicitly, I don't think it can be inferred. Maybe you could fix the docs & create a PR?

Of course, I will, why not (I'll do it this Monday evening probably) :) 

I wasn't sure about your intentions, this is why I created this issue. 
Now I know that was a documentation issue :)
