### ISSUE TITLE
Escaping embedded colons

### ISSUE THREAD

**Issue by ecurtin** [softwaremill/sttp#50]
Howdy! Thanks for the great project. It's made my work a _lot_ easier.

I seem to have found a bug with escaping colons.  From what you've written [here](http://sttp.readthedocs.io/en/latest/requests/uri.html) it seems like this case should work, but it doesn't seem to.

Using 1.0.6 and Scala 2.11.8
```scala
import com.softwaremill.sttp._

println(uri"localhost:8998")
// http://localhost:8998

val str = "localhost:8998"
println(uri"$str")
// http://localhost%3A8998
```

Is this a bug or a user error?

**Comment by adamw** [comment]
I just pushed this specific feature (parsing of embedded host+port combinations) today, but didn't do a release yet. The docs are probably for `master`, hence the confusion.

But, I'm doing a release right now, so this should be fixed very soon :)

**Comment by ecurtin** [comment]
Awesome! Thanks so much!

**Comment by adamw** [comment]
1.1.0 should be in central in ~15 minutes. Let me know if the above works - or if there are other problems :)

**Comment by ecurtin** [comment]
Got it and it works! Thanks!
