### ISSUE TITLE
Basic Authorization Fails

### ISSUE THREAD

**Issue by joe-chimienti** [softwaremill/sttp#504]
Setting the basic authorization header always returns 401 while executing the request.toCurl command returns 201

Note that the service provided me with an apiKey & not a username and password
```scala
    val c = new String(Base64.getEncoder.encode(s"${config.apiKey}".getBytes("utf-8")), "utf-8")
    val request = sttp.client.basicRequest
      .post(uri"${config.baseUrl}/invoices")
      .contentType(MediaType.ApplicationJson)
      .header("Authorization", s"Basic $c")
      .body(Json.toJson(inv).toString)
      .response(asStringAlways)
    
    // seding request via curl returns 200
    val curl = request.toCurl
    // sending request returns 401
    request.send()

```

**Comment by amdelamar** [comment]
Are there redirects in the initial response?

If so, by default sttp follows redirects but strips out "Authorization" header on the subsequent requests. Its possible `curl` does not strip that header and includes the original headers of the request after redirects.

**Comment by joe-chimienti** [comment]
Don't believe there are redirects, I tested w/ curl setting --max-redirs=0 and got 200, and with the sttp client `response.history`

```
curl -L --max-redirs 0 -X POST -H 'Authorization: Basic**REDACTED**==' -H 'Content-Type: application/json' -H 'Content-Length: 267' --data '{"buyer":{"name":"John doe test","address1":"address1","locality":"","region":"region","postalCode":"19087","country":"USA","email":"tester@gmail.com"},"redirectUrl":"https://example.com/swag?paid=true","itemDesc":"3\" rounded","price":1.5,"currency":"USD"}' 'https://example.com/invoices'

**Comment by joe-chimienti** [comment]
Thanks @amdelamar there are redirects, and I see the header being stripped thanks!

Is there a workaround for this, and do you recommend opening issue with API about redirects?

**Comment by adamw** [comment]
@joe-chimienti if you'd like to modify the redirect behavior, you can wrap your backend with `FollowRedirectsBackend` and configure it so that headers are not stripped (it's one of the constructor parameters). This will deactive any other redirect backends along the chain.

**Comment by j-chimienti** [comment]
Thanks adam, I was able to overwrite with sensitive headers param and verified that the header is not stripped. I'm still getting the same error. Here's my history for reference


history:

```
Response((),302,Found,List(Content-Type: none/none, Content-Length: 0, Server: nginx, Date: Thu, 21 Jan 2021 14:50:45 GMT, Connection: keep-alive, Location: https://server.com/Account/Login?ReturnUrl=%2Finvoices%xxxx, Strict-Transport-Security: max-age=31536000),List())
```

**Comment by joe-chimienti** [comment]
Note: Revoked keys below


I was looking at the requests over wireshark and noticed that Akka is stripping the '='. from the string. Curl does not strip the equal sign. Seems like a bug w/ akka


![curl-req](https://user-images.githubusercontent.com/55401154/105631044-62855d00-5e1a-11eb-95e8-981b84e31177.png)
![sttp-req](https://user-images.githubusercontent.com/55401154/105631045-674a1100-5e1a-11eb-8235-2afd9fd8922d.png)

**Comment by adamw** [comment]
Hm that's interesting, though the `Authorization` headers are different - the difference in `=` is because the second one has the `bzo=` suffix, while the first `bw==`. This shows in the decoded version - the second has an empty-string password, while the first has no password at all. Maybe that's the difference?

**Comment by scottweaver** [comment]
> Are there redirects in the initial response?
> 
> If so, by default sttp follows redirects but strips out "Authorization" header on the subsequent requests. Its possible `curl` does not strip that header and includes the original headers of the request after redirects.

This should be added to the documentation some where it is blatantly obvious.  We just recently got bit by this issue and got lucky by finding this ticket.  There is no mention either under the Redirects nor Authentication sections that call out this behavior.

**Comment by adamw** [comment]
@scottweaver Where in the docs would you like this to be documented? Maybe you can add the appropriate note? It's as easy as modifying an .md file in https://github.com/softwaremill/sttp/tree/master/docs :)

Btw. this behavior is implemented by many http clients (see e.g. https://stackoverflow.com/a/28671822/362531)

**Comment by scottweaver** [comment]
> @scottweaver Where in the docs would you like this to be documented? Maybe you can add the appropriate note? It's as easy as modifying an .md file in https://github.com/softwaremill/sttp/tree/master/docs :)
> 

Sure, I can take swing at it :).  I think it might be good to point this out in Authentication section and maybe another call out in Redirects as well.

> Btw. this behavior is implemented by many http clients (see e.g. https://stackoverflow.com/a/28671822/362531)

Be that as it may it doesn't hurt to point this out as @j-chimienti stated above they were completely unaware that redirects were occurring until further investigation, it was the same in our case as well.  

I will honestly claim ignorance to this "feature" even as I have been working with JVM http clients since the late '90s early '00s I guess just have never hit the "prefect storm" of redirects + plus  auth header stripping until now. Just goes to show you can always learn something new.  :)

**Comment by adamw** [comment]
Sounds good! :)

**Comment by adamw** [comment]
And yes, there's always something surprising hiding behind the corner ;)

**Comment by scottweaver** [comment]
PR up, https://github.com/softwaremill/sttp/pull/1102
