### ISSUE TITLE
Artifact has broken scm url

### ISSUE THREAD

**Issue by kiranbayram** [softwaremill/sttp#505]
The maven artifact scm url is broken, could you please fix that?

```
<scm>
        <url>https://github.com/softwaremill/core</url> (THIS HERE)
        <connection>git@github.com:softwaremill/core.git</connection>
    </scm>
```

**Comment by kiranbayram** [comment]
And some other modules have similar issue as well

**Comment by LGLO** [comment]
@kiranbayram  thanks for reporting, further artifacts will have this fixed.

**Comment by kiranbayram** [comment]
Thanks for fixing 👏
