### ISSUE TITLE
Feature Request: add config to follow redirects with Sensitive Headers

### ISSUE THREAD

**Issue by amdelamar** [softwaremill/sttp#523]
Can we get the ability to enable/disable sensitive headers when following redirects?

Seems the default is to always remove headers like `Authorization` which has caused unexpected problems for me: https://github.com/softwaremill/sttp/blob/master/core/src/main/scala/sttp/client/FollowRedirectsBackend.scala#L78

```scala
private def stripSensitiveHeaders[T](request: Request[T, S]): Request[T, S] = {
    request.copy[Identity, T, S](
      headers = request.headers.filterNot(h => sensitiveHeaders.contains(h.name.toLowerCase()))
    )
  }
```

I'd like the ability to opt-in to resend `Authorization` and other headers when following redirects.

Currently, I have to work around this by immediately `flatMap`-ing after a response to check if it returned `401` with `history.nonEmpty` and the last response had a `Location` header, then re-issue the original request with an updated uri to this location. And combining that workaround with the logging backend means I'm always making valid API calls, but the logs are polluted with Http 401s.

**Comment by adamw** [comment]
One possibility to achieve this today is to wrap your backend in `FollowRedirectsBackend`. This effectively deactivates any nested `FollowRedirectsBackend` (which are there by default).

So you can do: `val myBackend = new FollowRedirectsBackend(delegateBackend, sensitiveHeaders = Set.empty)`

Maybe this would need better documentation :)

**Comment by amdelamar** [comment]
Ok I tried that and it works.

```scala
val sttpBackend = Slf4jLoggingBackend[Future, Source[ByteString, Any], Nothing](
  new FollowRedirectsBackend[Future, Source[ByteString, Any], Nothing](
    AkkaHttpBackend(),
    sensitiveHeaders = Set.empty // we want redirects with Authorization
  )
)
```

That's interesting, because I would expect it to fail after the initial `FollowRedirectsBackend` redirects and gets `401` and bubbles that up to the second `FollowRedirectsBackend`, which shouldn't redirect because its not a Http `3XX`code. Seems the redirect logic does not look at status codes, only `Location` header.

**Comment by adamw** [comment]
Any nested `FollowRedirectsBackend`s are effectively deactivated, as the request that's passed down the chain has `followReidrects` set to `false`. So only the outer one does any work - and it does take into account status codes :)
