### ISSUE TITLE
OkHttp can't override Accept-Encoding

### ISSUE THREAD

**Issue by ignacioPL** [softwaremill/sttp#531]
With the OKHttpBackend I can't override de Accept-Encoding it always defaults to GZIP and OkHttp supports brotli.

I think that the problem comes from this lines, in OkHttpBackend.scala:

```scala
request.headers
    .filterNot(h => h.is(HeaderNames.AcceptEncoding) || h.is(HeaderNames.ContentType))
    .foreach {
          case Header(name, value) => builder.addHeader(name, value)
    }
```

**Comment by ignacioPL** [comment]
I can change it from the OkHttp Client

**Comment by ghostbuster91** [comment]
I will keep it reopen so we could improve user's experience here.

**Comment by ghostbuster91** [comment]
Done via #542
