### ISSUE TITLE
Terminating actor system shows Error log 

### ISSUE THREAD

**Issue by Ha5hBr0wn** [softwaremill/sttp#533]
When I terminate my Actor System when using the Akka Backend this error message shows up on my log

`[ERROR] [05/07/2020 15:56:02.901] [tester-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(tester)] Outgoing request stream error (akka.stream.AbruptTerminationException: Processor actor [Actor[akka://tester/system/Materializers/StreamSupervisor-1/flow-0-0-PoolFlow#19997066]] terminated abruptly)`

Is this normal behavior?

**Comment by adamw** [comment]
Are you calling `actorSystem.terminate()` and then waiting for the returned Future?

**Comment by Ha5hBr0wn** [comment]
Here is my Main code 

```
object Main extends App{
  val system = ActorSystem(AccountManagerTester(), "tester")
  val sttp_backend = AkkaHttpBackend.usingActorSystem(system.classicSystem)
  system ! AccountManagerTester.Start

  Thread.sleep(5000)
  system.terminate()
}
```

I don't wait on any future because terminate() returns Unit

**Comment by Ha5hBr0wn** [comment]
Actually apparently this is a know issue if you google the error, and it is a harmless error log. So never mind. Although as a different question is there anyway for me to configure the max-connections that Akka-http will use so that I don't experience a BufferOverflowException. It seems the default is 4, but when I tried to change that in a application.conf file it didn't help.

**Comment by adamw** [comment]
hmm which version of akka are you using, if `.terminate` return `Unit` and not `Future`?

How are you setting the max-connections? This should be done sth like `akka.http.server.max-connections = 128`

**Comment by Ha5hBr0wn** [comment]
I am using the latest version 2.6.5. Also do I just add that line in a file named src/main/resources/application.conf? Like standalone or in some kind of bracketed structure?

**Comment by adamw** [comment]
Hm I have the following method signature in `ActorSystem`: `def terminate(): Future[Terminated]`

Anyway, yes, you should just add the following line to application.conf. No brackets :)

**Comment by Ha5hBr0wn** [comment]
Yeah I checked the API and it looks like akka.actors.ActorSystem.terminate has that signature. I am using akka.actors.typed.ActorSystem.terminate which has a different signature.

**Comment by Ha5hBr0wn** [comment]
It seems the setting I was looking for was 

`akka.http.host-connection-pool.max-connections = 20`

Depending on how I change that number I get more or less Error logs to my console when my system terminates. 

So right now I am getting 20 of these when the system ends 

`[ERROR] [05/08/2020 08:26:34.771] [tester-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(tester)] Outgoing request stream error (akka.stream.AbruptTerminationException: Processor actor [Actor[akka://tester/system/Materializers/StreamSupervisor-1/flow-0-0-PoolFlow#11175175]] terminated abruptly)

According to some posts on Akka's GitHub this error is harmless. I have a logback.xml file of my own that writes my log messages to a file. But these show up in my console and are somewhat annoying to see every time I run my program. Is there a way for me to adjust that?
`

**Comment by adamw** [comment]
don't you have a console appender in your logback.xml as well?

**Comment by Ha5hBr0wn** [comment]
Nope I just write all logging statements to a file (for better or worse). And that is where all my logging statements appear except for these ones. These pop up only in my console (not in the file) when the program terminates.

**Comment by Ha5hBr0wn** [comment]
It seems adding these lines of code after creating the system and backend fixes the issues.

```
CoordinatedShutdown(system).addTask(CoordinatedShutdown.PhaseBeforeActorSystemTerminate, "shut down connection pools") { () =>
    implicit val ec = system.executionContext
    Future{Http(system).shutdownAllConnectionPools; Done}
  }
```

The Error messages are no longer logged to the console as the streams in the backend are terminated before the system finishes shutting down.

**Comment by adamw** [comment]
Interesting! Where did you find that :)

Maybe that's what we should do in the backend's `close` method

**Comment by Ha5hBr0wn** [comment]
I was looking at the Akka coordinated shutdown section of the documentation where you can add some extra phases to the termination of the actor system, and I just added a phase to shut down the connection pools and the terminated abruptly error went away. This is Akka 2.6.5

**Comment by adamw** [comment]
@Ha5hBr0wn thanks for the input, I've added the code to the akka backend
