### ISSUE TITLE
How to ignore ssl?

### ISSUE THREAD

**Issue by Krever** [softwaremill/sttp#54]
Is it possible to ignore invalid ssl certificate? 

Im using `HttpURLConnectionBackend` but can switch to any other if needed.

**Comment by adamw** [comment]
Yes, but it's different for every backend, and not possible to implement in a generic way. See: http://sttp.readthedocs.io/en/latest/conf/ssl.html

For `HttpURLConnectionBackend`, see e.g.: https://stackoverflow.com/questions/19723415/java-overriding-function-to-disable-ssl-certificate-check

**Comment by Krever** [comment]
Thanks for quick response and sorry I missed the docs.
