### ISSUE TITLE
Null pointer exception if backend is not setup in time

### ISSUE THREAD

**Issue by Ha5hBr0wn** [softwaremill/sttp#541]
It seems the backend is set up asynchronously which can cause issues because if you use it too soon and don't give it time to setup you'll get null. 

I solved it by just putting a sleep in a thread that was going to use it immediately when the program started, but that seems like a bad way to handle it. 

Is there a fix for this?

**Comment by adamw** [comment]
The akka http backend? How are you creating it? And where's the NPE coming from?

**Comment by Ha5hBr0wn** [comment]
I create it using my own actor system inside my an object Main that extends App. When the actor system is created I have an actor called HttpClient that has 
`implicit val backend = Main.backend`.

When I actually .send() the request I get the NPE and it is the backend that is null. However if the system takes long enough to actually send a request to the HttPClient that actually makes it, the NPE doesn't show up. (By long enough I mean just a few hundreds of milliseconds)

It could just be because I create the actor system and then set the backend, but before that backend is actually set I have spawned all these actors that are working. So even though making that backend in Main is my second line of code besides making the actor system it is possible to get the NPE. I realize now when typing this I should be making the backend in the HTTP client setup so that this cannot happen.
