### ISSUE TITLE
zio RC19

### ISSUE THREAD

**Issue by TimPigden** [softwaremill/sttp#548]
Please update to RC19 for zio backend.
Thanks

**Comment by ghostdogpr** [comment]
I'm in the process of upgrading sttp zio dependencies: just published [interop-reactive-streams](https://github.com/zio/interop-reactive-streams/releases/tag/v1.0.3.5-RC8), the last one is zio-telemetry where I just opened a [PR](https://github.com/zio/zio-telemetry/pull/151). Once this is done, sttp can be upgraded.
