### ISSUE TITLE
Socks/Tor proxy not working via sttp/okhttp, but fine in okhttp by itself

### ISSUE THREAD

**Issue by fancellu** [softwaremill/sttp#561]
https://gist.github.com/fancellu/eba17511fc1cba273355f939bc886e29

val sttpversion="2.0.0-RC2"

"com.softwaremill.sttp.client" %% "okhttp-backend" % "2.1.2"

"SOCKS server general failure"

Any idea why?

Thanks

**Comment by adamw** [comment]
No idea - do I read the gist output correctly that it works when directly suing okhttp's client, but not when through sttp?

That would be quite weird. I would try to compare the request created by hand, and the one coverted from sttp to okhttp. Maybe there's something different there. But that would require some work with the debugger :)

**Comment by fancellu** [comment]
Yes. okhttp works fine, I then plug the same client instance into sttpbackend, and it errors

I'm happy to use okhttp raw, but thought you'd like to know it has "surprising behaviour" when plugged into sttp

This issue with http clients and SOCKS handling (plus proper DNS resolution) is quite common, which is why I was happy when I found okhttp handled it properly

JDK11 HttpClient doesn't work with SOCKS, and neither does AsyncHttpClient (and by extension play-ws)

**Comment by adamw** [comment]
Yeah, though the weird thing is that sttp should do more or less what you are doing in your "direct" code. But to debug what exactly happens, would require a local env to reproduce :)

**Comment by fancellu** [comment]
You can either install Tor cli directly, or just the Tor browser, and point the code to 9150 instead of 9050. 

When you start Tor browser it kicks off a SOCKS proxy for you

https://www.torproject.org/download/

**Comment by adamw** [comment]
Thanks, I'll try that when I get some time to debug this :)

**Comment by LGLO** [comment]
@fancellu I'm don't know much about SOCKS but I managed to "fix" your gist by changing scheme to `http` from `https`.
When `https` is used with plain OkHttp client exception is same.

**Comment by fancellu** [comment]
Gah, you're right, I must have put the https by mistake. 

Consider this closed
