### ISSUE TITLE
multipart POST always have Content-Type: multipart/form-data

### ISSUE THREAD

**Issue by avilshadow** [softwaremill/sttp#588]
I have a code smt like:

```
basicRequest
      .post(uri)
      .multipartBody(body)
      .headers(
        Map("Content-Type" -> "multipart/mixed")
      ).send()
```

but server receives request with ''multipart/form-data'.
is there any way to override it?

tried with   "2.1.5" and HttpURLConnectionBackend()
before actual `send`, there is the correct header value, after sending - not.

**Comment by adamw** [comment]
Should be fixed in 2.2.0
