### ISSUE TITLE
add statusText/reason/message to Response

### ISSUE THREAD

**Issue by ILLKO** [softwaremill/sttp#59]
very common, how to name it better?

| lib  | int  | text  | 
| --- | --- | --- |
| sttp  | code  |  add statusText/reason/message? |   
| js fetch  |  status | statusText  |   
| gigahorse  | status  | statusText |   
| akka http | StatusCode.intValue | StatusCode.reason |
| HttpURLConnection | getResponseCode | getResponseMessage |
| asynchttpclient | getStatusCode | getStatusText |
| okhttp3 | code | message |

**Comment by adamw** [comment]
Released in 1.1.5. Thanks @intracer !

**Comment by adamw** [comment]
sorry, 1.1.4 :)
