### ISSUE TITLE
sttp core tests library no longer published since 2.1.0

### ISSUE THREAD

**Issue by tarmath** [softwaremill/sttp#591]
It looks like it was dropped between 2.0.9 and 2.1.0:

https://repo1.maven.org/maven2/com/softwaremill/sttp/client/core_2.13/2.0.9/
https://repo1.maven.org/maven2/com/softwaremill/sttp/client/core_2.13/2.1.0/

Was this a conscious decision? Or did it move somewhere else?

**Comment by adamw** [comment]
I think it worked :) https://repo1.maven.org/maven2/com/softwaremill/sttp/client/core_2.13/2.2.0/
