### ISSUE TITLE
Recurring test failures in Scala community build

### ISSUE THREAD

**Issue by SethTisue** [softwaremill/sttp#598]
the two AsyncHttpClient FS2 failures in particular are happening often enough (today there was a streak of four consecutive failed runs) to have become a problem, so I'm going to disable those tests. happy to try re-enabling them on request, if the issue is believed to be resolved

~~they seem to be especially prone to failure on JDK 11 and 14, but it's hard to be sure without more data.~~

```
**sttp** fail Jun 16
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/970/artifact/logs/sttp-build.log
  sttp.client.asynchttpclient.fs2.AsyncHttpClientFs2HttpStreamingTest
  sttp.client.asynchttpclient.fs2.AsyncHttpClientPipedFs2WebsocketsTest
**sttp** fail Jun 16
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/969/artifact/logs/sttp-build.log
  sttp.client.asynchttpclient.fs2.AsyncHttpClientFs2HttpStreamingTest
**sttp** fail Jun 16
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/968/artifact/logs/sttp-build.log
  sttp.client.prometheus.PrometheusBackendTest
**sttp** fail Jun 16
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/967/artifact/logs/sttp-build.log
  sttp.client.asynchttpclient.fs2.AsyncHttpClientFs2HttpStreamingTest
**sttp** fail Jun 1
  https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5796/artifact/logs/sttp-build.log
  com.softwaremill.sttp.http4s.Http4sHttpTest
**sttp** fail May 29
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/938/artifact/logs/sttp-build.log
  sttp.client.asynchttpclient.fs2.AsyncHttpClientPipedFs2WebsocketsTest
**sttp** fail May 8
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/898/artifact/logs/sttp-build.log
  sttp.client.asynchttpclient.fs2.AsyncHttpClientPipedFs2WebsocketsTest
**sttp** fail Apr 4
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1335/artifact/logs/sttp-build.log
  sttp.client.asynchttpclient.fs2.AsyncHttpClientPipedFs2WebsocketsTest
**sttp** fail Apr 3
  https://scala-ci.typesafe.com/job/scala-2.12.x-jdk11-integrate-community-build/1184/artifact/logs/sttp-build.log
  com.softwaremill.sttp.http4s.Http4sHttpTest
**sttp** fail Mar 30
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/802/artifact/logs/sttp-build.log
  sttp.client.asynchttpclient.fs2.AsyncHttpClientPipedFs2WebsocketsTest
**sttp** fail Mar 24
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/783/artifact/logs/sttp-build.log
  sttp.client.asynchttpclient.fs2.AsyncHttpClientPipedFs2WebsocketsTest
**sttp** fail Mar 21
  https://scala-ci.typesafe.com/job/scala-2.12.x-jdk14-integrate-community-build/801/artifact/logs/sttp-build.log
  com.softwaremill.sttp.http4s.Http4sHttpTest
**sttp** fail Mar 20
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1262/artifact/logs/sttp-build.log
  sttp.client.asynchttpclient.fs2.AsyncHttpClientPipedFs2WebsocketsTest
```

**Comment by SethTisue** [comment]
also this intermittently fails:

```
[info] - receive a stream from an https site *** FAILED ***
[info]   0 was not equal to 100 (StreamingTest.scala:139)
[info] Run completed in 2 seconds, 381 milliseconds.
[info] Total number of tests run: 7
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 6, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	sttp.client.akkahttp.AkkaHttpStreamingTest
```

I had left this off the list originally because I had seen it fail 5 runs in a row so I figured it must be a “real” failure, but no, it does sometimes pass. sometimes it even passes 5 runs in a row, go figure.

**Comment by SethTisue** [comment]
> they seem to be especially prone to failure on JDK 11 and 14, but it's hard to be sure without more data

oops, scratch that, I forgot that fs2 doesn't build on JDK 8 anymore, and sttp is downstream, so the community build never tests sttp on JDK 8

**Comment by adamw** [comment]
Thanks for the report. We've seem similar problems on travis (but not locally or on jenkins, where we build releases), so it's about time we've investigated :)

I think it's rather a race condition somewhere in the tests, rather than timeouts. They're quite large already.

**Comment by adamw** [comment]
The `AsyncHttpClientPipedFs2WebsocketsTest` should be fixed. Waiting a couple of builds until the others occur on travis as well

**Comment by SethTisue** [comment]
cool — I can't easily help test at the moment because we are using frozen versions of some of sttp's dependencies, but I've added a comment to check on this next time we unfreeze

**Comment by SethTisue** [comment]
https://github.com/scala/community-build/pull/1199 is merged, moving to latest sttp

but that PR actually removes `httpClientBackendFs2`, because of some fs2 version mismatch (a compile-time error) that IMO it isn't worth troubleshooting 🤷 — we don't need to have every integration, it isn't always worth fiddling with. but the good news is that the PR also re-adds some of the integrations that were disabled before, e.g. for monix

optimistically closing the issue. I'll come back here if I notice any recurring failures with the new version
