### ISSUE TITLE
Extend ReponseError to allow arbitrary types for error case

### ISSUE THREAD

**Issue by ghostbuster91** [softwaremill/sttp#618]
This is a summary and continuation of two discussions:
- https://github.com/softwaremill/sttp-model/issues/5
- https://github.com/OpenAPITools/openapi-generator/pull/6684#discussion_r443485605

As in openapi specification we are aware of possible error responses there should be an easy way to express that in sttp.

That would require adding another generic parameter to `ResponseError `, while default `ResponseError` would be still parametrized by `String` type.

Additional `ResponseError` type is needed in order to represent unmapped error codes.

All existing functions which deals with `ResponseError` (like `asJsonAlwaysUnsafe`) need to be refined.

**Comment by adamw** [comment]
Fixed in v3
