### ISSUE TITLE
Armeria backend

### ISSUE THREAD

**Issue by ngbinh** [softwaremill/sttp#619]
https://armeria.dev/ is a great Netty based http/grpc client. Would be great to have Armeria backend on sttp

**Comment by ikhoon** [comment]
Hi @ngbinh, I found this issue today. I was working on Armeria backend for sttp. I have been preparing to release Armeria 1.0.0 . Let me open a PR soon. 😉

**Comment by ngbinh** [comment]
That's amazing. Thanks

**Comment by ngbinh** [comment]
@ikhoon is there anything I can do to help? As `asynchttpclient` main maintainer has stepped down per https://twitter.com/slandelle/status/1274385687438073857 , I am looking for a better replacement.

**Comment by ikhoon** [comment]
Sorry, I am waiting for https://github.com/line/armeria/pull/2894 is merged. 😅
As Armeria does not support multipart at the moment, I made the PR for multipart support in Armeria.

**Comment by ngbinh** [comment]
@ikhoon Thanks for the update. No rush here though! Please let me know if I can do anything to help

**Comment by trustin** [comment]
Please stay tuned! We're very eager to add multipart support to Armeria. :wink:

**Comment by kubinio123** [comment]
when https://github.com/line/armeria/issues/253 will be merged, we'll add multipart support to Armeria backend in sttp. ;)

**Comment by ikhoon** [comment]
Armeria backend is not merged to sttp GitHub yet. I worked Armeria backend in a local branch. 
Are you interested in implementing only the multipart implementation or Armeria backend?

**Comment by adamw** [comment]
A basic Armeria backend got released in 3.1.1. Thanks @kubinio123 !
