### ISSUE TITLE
Unable to POST with akka backend

### ISSUE THREAD

**Issue by TsundereBug** [softwaremill/sttp#63]
POST acts as GET when using the Akka backend.

**Comment by adamw** [comment]
Can you provide a failing test? There are test cases for this but everything works fine, also in our codebases.

**Comment by TsundereBug** [comment]
Not at home right now; I will send a case as soon as I can.

I'm POSTing to a Discord channel's messages, and instead of POSTing to the
URL it acts as GETting to the URL. This may be a way with how I pick
sttp.host(uri"stuff") from a match?

**Comment by adamw** [comment]
Not sure I understand "This may be a way with how I pick sttp.host(uri"stuff") from a match" - there's `sttp.post` and `sttp.get` which selects the method

**Comment by TsundereBug** [comment]
See https://github.com/DiscordScala/discord.scala src/main/scala
github.discordscala.core.util.RequestUtil for an example (down towards the
bottom of the file is where we handle HTTP)

(Yes it's bad code and I'm planning on going back and refactoring soon)

**Comment by adamw** [comment]
Well, maybe you have a bug in your default parameters, for example `awaitRestRequestFuture:63` doesn't pass the chosen method to `restRequestFuture`?

**Comment by TsundereBug** [comment]
🤦 how did I miss that?!

I will fix as soon as possible. Thanks for catching this.

**Comment by TsundereBug** [comment]
Yep. I still don't know how I missed that.
