### ISSUE TITLE
How to use different proxy per request?

### ISSUE THREAD

**Issue by user753** [softwaremill/sttp#650]
Should I create backend for each request?

**Comment by adamw** [comment]
Proxy settings are typically part of the underlying client's settings, hence they are part of the backend configuration. How many proxy settings do you have? Maybe you can somehow pool them?

One option to consider would be providing methods to copy a backend with different proxy settings, but re-using the same thread pool to service requests, for example. This can be already in some part implemented by creating a backend using an AHC client / Akka actor system /... (not sure which backend you are using) and adjusting its configuration to create a number of backends.

**Comment by user753** [comment]
>How many proxy settings do you have? Maybe you can somehow pool them?

Around five. I use a pool of backends, but I think it isn't optimal, because they all have separate thread pools.
I will try to use akka backend.

**Comment by adamw** [comment]
I think all of the backends have a variatn which allows constructing them given a lower-level client implementation. You should be able to create the low-level client once, and then re-use it multiple times to construct the backends.
