### ISSUE TITLE
It is difficult to determine the ultimate URI of a resource when using `FollowRedirectsBackend`

### ISSUE THREAD

**Issue by stephenjudkins** [softwaremill/sttp#656]
`FollowRedirectsBackend` works well to transparently follow a chain of 30x redirects to a new resource. However, when at that resource the ultimate URI is difficult to determine. This is problematic because the resource may contain relative URIs, and knowledge of the resource's URI is necessary to canonicalize them. One must follow the chain of redirects in `history` and reproduce the same logic for this to work.

**Comment by adamw** [comment]
Will be released in 3.0.0-RC2
