### ISSUE TITLE
a little bit awkward when trying to log the response

### ISSUE THREAD

**Issue by jasonqu** [softwaremill/sttp#66]
I want to log the response before converting to json, so I wrote

```
  def logRequest(uri: String, resStr: String): String = {
    println(resStr)
    resStr
  }

  val request = sttp.get(uri"https://httpbin.org/get")
    .mapResponse(logRequest(uri, _))
    .response(asJson[HttpBinResponse])
    .send().foreach(println)
```

It's not working, because `mapResponse` would apply map to `ResponseAs`, 
and `response` would set a new `ResponseAs`, ignore the previous one completely.

* Is it possible to add compile error or a warning for such code?

and I end up logging with `res: Response[String]` like this

```
    if (res.isSuccess) {
      val resStr = res.body.right.get
      val respTruncated = if (resStr.length > 300) resStr.substring(0, 300) + "..." else resStr
      clientLog.info("request to {} with {} got {}", uri, reqBody, respTruncated)
      Success(resStr)
    } else {
      clientLog.error("response to {} with {} got code {}, body {}", uri, reqBody, res.code + "", res.body.left.get)
      Failure(UnknownServerError)
    }
```
* Is there some kind of best practice for logging the raw response?

**Comment by adamw** [comment]
I don't have a good idea as to how catch errors like this on compile time - as `.response` is essentially a decorated `.copy` from a case class, hence it overwrites whatever was there before.

However, logging the raw response is definitely a very good use case. What do you think about introducing response mappers, e.g. `toJson`, which would be the response-mapping functions? Your example then could be:

```
sttp.get("...")
  .response(asString) // not needed, as it's the default
  .mapResponse(logRequest(uri, _))
  .mapResponse(toJson[HttpBinResponse])
```

?

**Comment by jasonqu** [comment]
that will do for success response.
I choose to use `Response` directly because I have to log the error message as well :)

**Comment by adamw** [comment]
I've added a scaladoc (https://github.com/softwaremill/sttp/commit/a38dfc9475c61e3cd6b489f35526ec8f4c70f6a5), do you think it explains the issue well, or more is needed?

As for logging the response, I don't think we'll be able to do better than handling the `Either`, as you did. At least I don't have any better ideas right now :) Btw., instead of `.isSuccess` + `.get` (which is always possible to mess up), you might also use `.fold` or pattern matching on `Left`/`Right`.

**Comment by jasonqu** [comment]
Got it.

The comment looks good to me : )
