### ISSUE TITLE
Inconsistent handling of Host header

### ISSUE THREAD

**Issue by nxdcforciea** [softwaremill/sttp#668]
I've been trying to use sttp for a utility to make requests across a bunch of different IPs but all with the same Host header, so that I can bypass a load balancer. It appears that sttp treats the Host header in a special way, which causes some problems:

1) Host is apparently set someplace I don't have access to manipulate. Unless I'm missing something in the API that gives me access to it, I think sttp is not usable for my (I would have thought straightforward) use case.

2) The behavior is surprising because it happens automatically and does not model the underlying protocol it is supposed to represent. The Host header is just another header, and one would reasonably expect to be able to set it by calling .header("Host", hostname) on a request. Instead, setting the header that way appears to work just fine, but it is sneakily replaced at the last minute with a different value.

3) Other functions in sttp behave incorrectly because they are also not privy to the magic manipulation of the Host header. For instance, if you as above set the Host header by calling .header("Host", header) on a RequestT and then call .toCurl on it, it will generate a curl command that is not actually representative of the request. It will generate with a Host header specified by the .header call, which as stated above is not the Host header that sttp will actually send when it makes the call.

**Comment by adamw** [comment]
Thanks for the report! Which backend are you using?

**Comment by nxdcforciea** [comment]
I am using the default backend. Specifically, the relevant code amounts to bringing in 
`"com.softwaremill.sttp.client" %% "core" % "2.2.4"`
in build.sbt and then running something equivalent to

`import sttp.client._
val ip = "10.10.40.1"
val request = basicRequest.get(uri"http://$ip/endpoint")
val response = request.send()`

To repro the incorrect output from toCurl you can instead do

`import sttp.client._
val ip = "10.10.40.1"
val request = basicRequest.get(uri"http://$ip/endpoint").header("Host", "hostname.net")
println(request.toCurl)`

That will output `curl -L --max-redirs 32 -X GET -H 'Host: hostname.net' 'http://10.10.40.1/endpoint'` but if you actually call request.send(), that Host header will not be what is sent.

**Comment by nxdcforciea** [comment]
I poked around and realized that this is an issue with the underlying java library. I don't know that it makes sense to do anything explicitly about it, since the underlying library's expected usage is to set the sun.net.http.allowRestrictedHeaders system variable, but it's probably worth a note in the documentation so it's more obvious to users that my described use case doesn't work without additional fiddling.

**Comment by adamw** [comment]
Yes, it would probably be good to document that. Also, behavior when using e.g. async-http-client or OkHttp might be different.

**Comment by kubinio123** [comment]
Docs about overriding host header has been updated ;)
