### ISSUE TITLE
URI params: `?` gets wrongly in some situations

### ISSUE THREAD

**Issue by asheshambasta** [softwaremill/sttp#68]
I seem to have run into a situation where I see `?` getting wrongly encoded.
Consider:

```scala
import com.softwaremill.sttp._

def uriP(param: Boolean) = uri"https://someapi.com${if (param) "?f=1" else ""}"

uriP(false) // https://someapi.com -- as expected
uriP(true) // https://someapi.com%3Ff=1 -- the `?` seems to be encoded
```

_Version: 1.1.5_

I can understand this may be a bit of an edge case, but in any case, the leading `?` shouldn't be escaped.

**Comment by adamw** [comment]
Just use an `Option`: `uri"https://someapi.com?f=${if (param) Some(1) else None}"`

You should get the URI you want :)

**Comment by asheshambasta** [comment]
@adamw yeah, thats what I'm using at this point. But the point was that the first `?` should almost never be escaped. I'm failing to come to a use case where URL encoding it can be useful.

Thanks for replying though!

**Comment by adamw** [comment]
Well, it might be part of the path. Not very common, but definitely valid and probable :)

**Comment by asheshambasta** [comment]
@adamw allright, thanks. Closing this though – its kind of an edge case anyway.
