### ISSUE TITLE
Few typos in docs that leads to wrong links

### ISSUE THREAD

**Issue by AlekseiMolokovskikh** [softwaremill/sttp#686]
There are few typos in `Note` section at  these pages:
https://sttp.softwaremill.com/en/latest/requests/basics.html
https://sttp.softwaremill.com/en/latest/requests/streaming.html
https://sttp.softwaremill.com/en/latest/responses/basics.html

Because of this link looks like 
`https://sttp.softwaremill.com/en/latest/requests/type.md` instead of
`https://sttp.softwaremill.com/en/latest/requests/type.html`

I want to fix this issue if nobody minds.

**Comment by adamw** [comment]
Thanks for noticing - sure, go ahead, PRs are always welcome! :)
