### ISSUE TITLE
How to create a mock for AkkaHttpBackend

### ISSUE THREAD

**Issue by putnam120** [softwaremill/sttp#712]
In my code I'm using the AkkaHttpBackend within a typed Actor via
`val sttpBackend = AkkaHttpBackend.usingActorSystem(system)`

I would like to add an argument to the `apply()` method of my Actor so that I can pass in a mock of the SttpBackend. How would I go about doing this? When I try
```
def apply(httpBackend: SttpBackend[Future, Source[ByteString, Any], NothingT] =
        AkkaHttpBackend())
```
My code compiles with no issues. However, in my test if I try `myActor(AkkaHttpBackend.stub)` I get an error stating that there's a type mismatch. Any advice on how I can change things so that I can use the AkkaHttpBackend in my production code but the AkkaHttpBackend.stub (or any other stub) in the unit test would be greatly appreciated.

**Comment by putnam120** [comment]
The observed type error in the test file.

`type mismatch;
 found   : sttp.client.testing.SttpBackendStub[scala.concurrent.Future,Nothing,[γ$5$]akka.stream.scaladsl.Flow[akka.http.scaladsl.model.ws.Message,akka.http.scaladsl.model.ws.Message,γ$5$]]
 required: sttp.client.SttpBackend[scala.concurrent.Future,akka.stream.scaladsl.Source[akka.util.ByteString,Any],sttp.client.NothingT]`

**Comment by adamw** [comment]
Indeed the signature is incorrent, it's missing the streams capability. I'll fix in v3, here you can try: `SttpBackendStub(new FutureMonad())` with an implicit EC in scope (e.g. `ExecutionContext.Implicits.global`)
