### ISSUE TITLE
URI parameter: symbol `;` not encoded properly.

### ISSUE THREAD

**Issue by fsanaulla** [softwaremill/sttp#72]
```scala> import com.softwaremill.sttp._
import com.softwaremill.sttp._

scala> val u = uri"http://localhost:8080/query?q=firstQuery;secondQuery"
u: com.softwaremill.sttp.Uri = http://localhost:8080/query?q=firstQuery;secondQuery
```
it should looks like: `http://localhost:8080/query?q=firstQuery%3BsecondQuery`. 
Using latest `sttp` version.

**Comment by adamw** [comment]
According to https://tools.ietf.org/html/rfc3986#section-3.4, `;` is an allowed character in the query. Why would it need to be escaped?

**Comment by fsanaulla** [comment]
You right. Thanks.
