### ISSUE TITLE
A problem with a stub & AsyncHttpClientZioBackend

### ISSUE THREAD

**Issue by gchudnov** [softwaremill/sttp#726]
Hi

I'm trying to write a test for zio "1.0.3" & sttp "3.0.0-RC5" and have an issue with Has[_].

```
java.lang.Error: Defect in zio.Has: Set(SttpBackend[=λ %2:0 → ZIO[-Any,+Throwable,+2:0],+{ZioStreams & package::WebSockets}]) statically known to be contained within the environment are missing
```

it looks like a problem in ZIO and I raised an issue https://github.com/zio/zio/issues/4340 there

but I noticed there is a [comment in sttp regarding Has](https://github.com/softwaremill/sttp/blob/d09e1f5f31bea1b28e3dfde5ebafe4900ab85888/implementations/zio/src/main/scala/sttp/client/impl/zio/SttpClientStubbingBase.scala#L13) and wondering if there is a workaround for the problem I bumped into? 
or if I'm writing this test in a wrong way ?

the minimized code that gives an error looks something like:

```scala
import sttp.client3._
import sttp.client3.asynchttpclient.zio.stubbing._
import sttp.client3.asynchttpclient.zio.{ send, AsyncHttpClientZioBackend, SttpClient, SttpClientStubbing }
import sttp.model.Uri
import zio.test.Assertion._
import zio.test._
import zio.{ Layer, ZIO }

object SendSpec extends DefaultRunnableSpec {

  private val eventsUri = Uri("https://some-url.org/")
  private val request   = basicRequest.get(eventsUri)

  override def spec: ZSpec[Environment, Failure] =
    suite("SendSpec")(
      testM("can be tested with an sttp stub") {
        val httpEnv: Layer[Throwable, SttpClient with SttpClientStubbing] = AsyncHttpClientZioBackend.stubLayer

        val runEffect: ZIO[SttpClient, Throwable, TestResult] = for {
          res <- send(request)
        } yield assert(res.body)(isRight)

        val stubEffect: ZIO[SttpClientStubbing, Throwable, Unit] = for {
          _ <- whenAnyRequest.thenRespond("RESPONSE")
        } yield ()

        val program: ZIO[SttpClient with SttpClientStubbing, Throwable, TestResult] = stubEffect *> runEffect

        program.provideCustomLayer(httpEnv)
      }
    )
}
```

An advice is appreciated.

Thank you,
Grigorii

**Comment by adamw** [comment]
I've just tested locally and the test worked fine (well I was using scalatest instead of zio-test, could this be a factor)? Maybe you could give more details on the exception, where is it thrown exactly?

**Comment by gchudnov** [comment]
hm. got it, thank you for reply.
let me check without zio-test...

I'm constantly getting an error inside of `zio.Has` [here](https://github.com/zio/zio/blob/33f8b4c119cd3cd1ee6533b3bc071612b862e82b/core/shared/src/main/scala/zio/Has.scala#L197)

when setting a breakpoint there I can see there 2 sets, but `SttpBackend` is a bit different inside (see below).
and the exception is thrown `throw new Error(s"Defect in zio.Has: ${missingServices} statically known to be contained within the environment are missing")`


set:
```scala
set = {Set$Set2@3055} "Set$Set2" size = 2
 0 = {LightTypeTag$$anon$1@3063} "package::SttpClientStubbing::Service"
 1 = {LightTypeTag$$anon$1@3064} "SttpBackend[=λ %2:0 → ZIO[-Any,+Throwable,+2:0],+{ZioStreams & package::WebSockets}]"
```

self.map.keySet:
```scala
keySet = {MapOps$ImmutableKeySet@3089} "MapOps$ImmutableKeySet" size = 2
 0 = {LightTypeTag$ParsedLightTypeTag@3087} "package::SttpClientStubbing::Service"
 1 = {LightTypeTag$ParsedLightTypeTag@3088} "SttpBackend[=λ %1:0 → ZIO[-Any,+Throwable,+1:0],+{package::WebSockets & ZioStreams}]"
```

**Comment by gchudnov** [comment]
@adamw 

hm. just run without zio-test, still the same exception.

created a really simple project that reproduces the problem:
https://github.com/gchudnov/zio-sttp-test

--
Wondering if your current code for v3 branch significantly diverged from "3.0.0-RC5" and doesn't have this problem anymore (?)

**Comment by adamw** [comment]
This is really weird. Indeed, when I copy-paste your code into sttp for a quick test, it works. When I run your project, it fails. And the only changes there were are in docs: https://github.com/softwaremill/sttp/compare/v3.0.0-RC5...master

**Comment by adamw** [comment]
Ah! It works with zio 1.0.1, but breaks with 1.0.3. So maybe that's a regression in their code? I didn't investigate much further. 

While not a fix, it's always a work-around (to use the older zio version)

sttp is still on 1.0.1 because of dotty, I need to upgrade that one day :)

**Comment by adamw** [comment]
I think that's a binary incompatibility between 1.0.1 and 1.0.3. After updating sttp to 1.0.3, it works again. I'll release RC6 soon with update zio.

**Comment by gchudnov** [comment]
got it,
thank you for the explanation!

guess this issue can be closed.

**Comment by adamw** [comment]
3.0.0-RC6 is out, please test :)

**Comment by gchudnov** [comment]
@adamw 

yes, it works!
thank you very much!
