### ISSUE TITLE
httpclient-backend isn't released for 2.12

### ISSUE THREAD

**Issue by kubukoz** [softwaremill/sttp#727]
It would be nice to see it released for that version too.

**Comment by adamw** [comment]
A quick test gives the following error when compiling: `[error] 'jvm-11' is not a valid choice for '-target'`
That's because we do:

```
scalacOptions ++= {
      if (scalaVersion.value == scala3) Nil else List("-target:jvm-11")
    },
```

in the project settings. Do you know what's the status of compiling scala 2.12 for jvm 11? Should we just skip the flag and it will work fine?

**Comment by notxcain** [comment]
We use Open JDK 11 in production and run Scala 2.12 just fine without any flags.
