### ISSUE TITLE
scala-native

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [softwaremill/sttp#73]
curious if there are any plans for scala-native back-end support?
https://github.com/scala-native/scala-native

**Comment by adamw** [comment]
No specific plans, and I don't really know what would be needed to create one, but if somebody contributed one I'd be happy to merge it!

**Comment by pcejrowski** [comment]
I have just opened a PR: https://github.com/softwaremill/sttp/pull/105

**Comment by adamw** [comment]
Available now in 1.3.0-RC2. Thanks @pcejrowski !

Please test :)
