### ISSUE TITLE
ZIO SttpClient name conflict

### ISSUE THREAD

**Issue by hxx0215** [softwaremill/sttp#732]
It seems the
``` scala
type SttpClient = Has[Sttp.Service]
```

and

``` scala
  object SttpClient {
    ...
  }
```
will make the compiler cannot infer the type.

``` scala
ZIO.accessM[SttpClient]{c =>
    val x = c.get
    ...
  }
```
the x here will be infer as Any

if I rename it like
``` scala
type SttpClientService = Has[SttpClient.Service]
ZIO.accessM[SttpClient]{c =>
    val x = c.get
    ...
}
```
the x can be infer as Sttp.Service correctly

**Comment by adamw** [comment]
Which version of sttp are you using? Could you give a complete example which is failing?

I've tried a very simple example:

```
ZIO
      .accessM[SttpClient] { c =>
        val x = c.get
        println(x)
        x.close()
      }
      .provideCustomLayer(AsyncHttpClientZioBackend.layer())
      .exitCode
```

and things worked just fine. 

The `object SttpClient` doesn't define an `SttpClient` type (it's a singleobject, with type `SttpClient.type`), so I doubt it interfers with the type alias. I see that in `Has[Sttp.Service]` you are using the `Sttp` object, what is that? Is it your custom code?

**Comment by hxx0215** [comment]
Hi @adamw, thank you. I am sorry I tried it again. Your are right, it works fine. I think it was Intellij's problem.
<img width="553" alt="image" src="https://user-images.githubusercontent.com/4247737/97009125-b88fef00-1511-11eb-9dc8-4d4188059fa0.png">
I trying to combine sttpclient with other service to make a new layer. Am I misused it?

**Comment by adamw** [comment]
I think combining `SttpClient` with another service is fine, though I don't have the context and I'm not that proficient in ZIO :)

**Comment by adamw** [comment]
Closing the issue then
