### ISSUE TITLE
Netty Eviction Warning

### ISSUE THREAD

**Issue by omar-f** [softwaremill/sttp#752]
Hello all,

I'm seeing this eviction warning in SBT when adding in `async-http-client-backend-future`.

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* io.netty:netty-handler:4.1.48.Final is selected over 4.1.43.Final
[warn] 	    +- org.asynchttpclient:async-http-client:2.12.1       (depends on 4.1.48.Final)
[warn] 	    +- io.netty:netty-codec-http:4.1.48.Final             (depends on 4.1.48.Final)
[warn] 	    +- com.typesafe.netty:netty-reactive-streams:2.0.4    (depends on 4.1.43.Final)
```

I am using version **2.2.9**.

I found this older issue which is related, https://github.com/softwaremill/sttp/issues/101.

Here is the dependency graph.

<img width="1254" alt="SBT dependency graph" src="https://user-images.githubusercontent.com/22119074/99182582-24e7c200-274f-11eb-883d-3b0c081dc33b.png">

**Comment by adamw** [comment]
Is this causing any problems?

Also, as you you can see on the graph, the eviction in the async-http-client dependency subtree, so if at all, I think this might be an issue for https://github.com/AsyncHttpClient/async-http-client ?

**Comment by omar-f** [comment]
Nope, it's not causing any issues, I just figured the dependency could be upgraded. But you are right, I didn't notice it's actually from https://github.com/AsyncHttpClient/async-http-client.
