### ISSUE TITLE
No headers in stream parts of multipart body

### ISSUE THREAD

**Issue by pinguinson** [softwaremill/sttp#773]
The following request:
```
val binaryPart =
  multipart("file", Array[Byte](77, 83, 71))
    .fileName("bar.bin")
    .contentType(MediaType.ApplicationOctetStream)

val textPart = 
  multipart("text_parameter", "some_random_text")

basicRequest
  .post(uri"http://foo.com/send")
  .multipartBody(List(binaryPart, textPart))
  .send(httpClient)
```
Is rendered into an invalid request with header-less subpart containing binary data (request data taken from `mitmproxy`):
```
Content-Length: 89
Host: foo.com
User-Agent: Java-http-client/11.0.8
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=ab04a1b3-2472-4c80-9ec6-81d3fd7ea716
--ab04a1b3-2472-4c80-9ec6-81d3fd7ea716


MSG
--ab04a1b3-2472-4c80-9ec6-81d3fd7ea716
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=text_parameter

some_random_text
--ab04a1b3-2472-4c80-9ec6-81d3fd7ea716--
```
I think the issue is in [MultiPartBodyPublisher](https://github.com/softwaremill/sttp/blob/3f47b1c97c8c4135ef7c62a36a3a6021af79fbb2/httpclient-backend/src/main/scala/sttp/client3/httpclient/MultiPartBodyPublisher.java#L51). `PartsSpecification` with type `STREAM` is created without headers, and its `contentType` is written to but never used afterwards.

**Comment by adamw** [comment]
Which backend are you using?

**Comment by pinguinson** [comment]
I'm using `HttpClientZioBackend`
