### ISSUE TITLE
[Question] API consistency for Monad (IdMonad)

### ISSUE THREAD

**Issue by eugeniyk** [softwaremill/sttp#779]
Hi!
during migration to sttp3 (RC10 so far) found that `IdMonad` is under `sttp.client3.monad`, at the same time all other monads are under `sttp.monad` (under shared:core)

Do you want to move it there or there is specific reason for that?

**Comment by adamw** [comment]
Yes, the monad interface is now part of sttp-shared, as to provide smooth interoperation, it needs to be used both by sttp-client and sttp-tapir. Hence the `sttp.monad` package name. 

The implementations for the built-in types is also there (`Either`, `Try`, `Future`), but any use-case-specific implementations are either in tapir or sttp-client. There wasn't a need to share `Identity` so it stayed in the client.

**Comment by eugeniyk** [comment]
Got it, thanks 
as a suggestion to https://github.com/softwaremill/sttp/issues/610 you may consider using cats-core instead of own monads (I believe cats-core should be small one). Apart of that they dropped support for 2.11 which may not work for you

**Comment by adamw** [comment]
@eugeniyk sttp integrates with a number of stacks (just-jdk, akka, monix, fs2, cats, zio, scalaz) so adding a cats dependency wouldn't be desired. It's just a bunch of small classes so the duplication we get by including `Monad` isn't that big :)

**Comment by adamw** [comment]
Closing as we won't be including cats as a dependency of `core`
