### ISSUE TITLE
Redirect with error "Location" header will broke the ZIO action.

### ISSUE THREAD

**Issue by djx314** [softwaremill/sttp#782]
https://github.com/softwaremill/sttp/blob/b365f2cf6edd8669480a21732ca44076fc9bd35d/core/src/main/scala/sttp/client3/FollowRedirectsBackend.scala#L60

Following the code in line 58 & 60. If the `Location` is not start with `/`, `http` nor `https`, the ZIO Async Backend will broke the whole ZIO action and can not catch any Exception.

Like the code:
```scala
for {
  uri1        <- ZIO.effect(Uri.unsafeParse(ac.baseUrl))
  response1   <- ZIO.effect(sendRequestUri(uri1))
  response    <- response1.mapError(new UriRequestError(_)) // Can not catch with the Response's Location Header is oldnews_html.asp?newsid=3278
} yield response
```

I think there's two way to fix.  
One is catch the exception.  
The other is catch the exception and resolve the url to the real path. Because this url write in Location(`oldnews_html.asp?newsid=3278`) works fine in firefox.

**Comment by adamw** [comment]
Do I understand correctly that the problem is with a redirect which points to a relative address, e.g. `Location: xyz.html`?

The fix than would be to patch the `isRelative` function to properly determine if the request is relative?

**Comment by djx314** [comment]
> Do I understand correctly that the problem is with a redirect which points to a relative address, e.g. Location: xyz.html?

Yes.

>The fix than would be to patch the isRelative function to properly determine if the request is relative?

Now my problem is ZIO cannot catch the exception when code is outside `ZIO.effect` and so on. Like

```scala
val action = for {
  i1 <- ZIO.effect(action1)
  i2 = throw new Exception()
  i3 <- ZIO.effect(action2)
} yield i3

action.mapError((e: Throwable) => UriParseError(e))
```

In this code, action can not route to UriParseError bacause `i2` is not catch. But I need to do something when the request is failed.

`i2` in sttp is the code
```scala
uri"${url}"
```
this function will throw error when parse is fail.

**Comment by adamw** [comment]
See the linked PR, this should fix relative detection.

I don't understand however why you cannot handle the exceptions coming from the uri parsing.This is an ordinary `IllegalArgumentException`, so it should be possible to handle it like any other.

**Comment by djx314** [comment]
Yes, this can slove my problem. The problem that handle exceptions is more better to ask in zio. If I have some examples of a production environment, I will ask this question in `zio/zio`.
