### ISSUE TITLE
play-json: ScalaJS support missing for recent versions

### ISSUE THREAD

**Issue by lazno** [softwaremill/sttp#789]
Hi there,

Im in the means of upgrading a project to scalajs 1.0.0. We use it for our SPA where our API calls to our backend are facilitated using tapir, sttp client and play-json as serializer.

While doing the upgrade I realized that for the artifact `"com.softwaremill.sttp.client" %%% "play-json" ` no scalajs version was published since version 2.0.9. Past versions also only supported scalajs 0.6.x.

https://mvnrepository.com/artifact/com.softwaremill.sttp.client/play-json

From what I understood (by asking one of softwaremill's employees) support was not dropped as I initially suspected, but the problem is merely caused by a bug in a buildfile.

If you could look into that, it would be highly appreciated.

**Comment by adamw** [comment]
I think play-json didn't have a scalajs 1.x release for some time, hence this was disabled in the build. I did a release for version 2.2.9 of that module, and in 3.x this is already enabled.
