### ISSUE TITLE
Optional follow-redirect support

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp#8]

**Comment by robsonpeixoto** [comment]
A suggestion about follow-redirect. On the response add the field `history` with all requests/responses required before the last one.

Reference: http://docs.python-requests.org/en/master/user/quickstart/#redirection-and-history
Obs: The `Response` class has the `request` field: http://docs.python-requests.org/en/master/api/#requests.Response.request

**Comment by adamw** [comment]
Implemented in 0.0.9
Thanks @robsonpeixoto for the suggestion - there's a `history` field on the response. However, I didn't add the back-reference to request from response - not sure if that would be so useful, we'll see if there will be requests to add it later.
