### ISSUE TITLE
could not import AsyncHttpClientScalazBackend

### ISSUE THREAD

**Issue by prayagupd** [softwaremill/sttp#80]
I'm trying to use scalaz backend for my sttp but could not find one. Here's my sbt

```scala
name := "customer-order-specs"

version := "0.1"

scalaVersion := "2.12.5"

libraryDependencies += "com.softwaremill.sttp" %% "core" % "1.1.12"
libraryDependencies += "com.softwaremill.sttp" %% "async-http-client-backend" % "1.1.12"

libraryDependencies += "com.softwaremill.sttp" %% "async-http-client-handler-scalaz" % "0.0.13"

libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.0-SNAP10" % Test

libraryDependencies += "org.scalacheck" %% "scalacheck" % "1.13.4" % "test"

```

I do not see ScalazBackend in `async-http-client-handler-scalaz.jar`.

<img width="716" alt="screen shot 2018-04-21 at 6 47 06 pm" src="https://user-images.githubusercontent.com/978095/39090452-8707c830-4594-11e8-9a19-4aa8a4bd355e.png">

I'm trying to simple scalaz backed http client example, as described in README with `HttpURLConnectionBackend `

```scala
  test("scalaz example") {
    import com.softwaremill.sttp.asynchttpclient.scalaz._

    implicit val backend: SttpBackend[Id, Nothing] = AsyncHttpClientScalazBackend()
    val httpRequest = sttp
      .post(uri"http://httpbin.org/post")
      .body("Hello, world!")

    val httpResponse = httpRequest.send()

    httpResponse.body.isRight shouldBe true
  }
```

**Comment by prayagupd** [comment]
Nevermind, I needed `async-http-client-backend-scalaz` which I could not find in the README at all but somehow mentioned in https://softwaremill.com/introducing-sttp-the-scala-http-client/

```scala
libraryDependencies += "com.softwaremill.sttp" %% "async-http-client-backend-scalaz" % "1.1.12"

```

**Comment by adamw** [comment]
Ah, it's currently listed on http://sttp.readthedocs.io/en/latest/backends/asynchttpclient.html, but maybe it's not that obvious. Where did you look? :)
