### ISSUE TITLE
ZIO backend is not published for dotty

### ISSUE THREAD

**Issue by dwlizlo** [softwaremill/sttp#800]
According to [https://sttp.softwaremill.com/en/latest/backends/zio.html#using-async-http-client](docs)
`"com.softwaremill.sttp.client3" %% "async-http-client-backend-zio" % "3.0.0-RC13"` should be built for scala 3.

However, it wasn't published for any of the 3.0.0 milestones. Is it an error in docs or artifacts are in fact missing?

**Comment by adamw** [comment]
Is a ZIO release available for any of the Scala3 milestones? It wasn't published due to the fact that ZIO wasn't :)

**Comment by adamw** [comment]
I think the update is still not merged: https://github.com/zio/zio/pull/4516

**Comment by dwlizlo** [comment]
Got it, just wanted to double check. Thanks!
