### ISSUE TITLE
Request: Support non-string bodies for failed requests

### ISSUE THREAD

**Issue by wbertelsen** [softwaremill/sttp#83]
This library makes a conscious decision to always parse the bodies of failed requests as strings. This is a needless restriction that makes this otherwise very nice looking library unusable in an environment where 4xx's are returned to clients that expect binary payloads with error information (in our case serialized protobufs).

The easiest change in my mind would to simply change the body Either form`Either[String, T]` to `Either[Array[Byte], T]` with a helper on `Response` to lazily deserialize the bytes into a string.

This looks like a relatively simple refactor to do (I'm considering doing it in a fork) - but I imagine this would be an annoying API break for existing users. Because of this I'm not trying to force this change upstream, but I wanted to flag the issue so it was on the project's radar.

**Comment by adamw** [comment]
Thanks for the info! Well that definitely would need at least a 1.2 release. Do you have an idea what could be the method's name which returns a `Either[String, T]` - which I think is a sane default for the majority of users?

Or the other way - we could have `body: Either[String, T]` as a `lazy val`/`def`, and have another method for getting the body with "raw errors"

**Comment by wbertelsen** [comment]
For reference, heres what I'm going to go with in the fork for now: https://github.com/eero-inc/sttp/pull/1

**Comment by adamw** [comment]
@wbertelsen See 1.2.0-RC1 - fixed there

**Comment by wbertelsen** [comment]
@adamw just came back around to this, thanks so much 🙏
