### ISSUE TITLE
httpclient-backend (the new java http client) for 2.12

### ISSUE THREAD

**Issue by wix-andriusb** [softwaremill/sttp#849]
Hi guys, is it possible to get a release for httpclient-backend for scala 2.12?

**Comment by adamw** [comment]
```scala
def httpClientBackendProject(proj: String, includeDotty: Boolean = false) = {
  ProjectMatrix(s"httpClientBackend${proj.capitalize}", file(s"httpclient-backend/$proj"))
    .settings(commonJvmSettings)
    .settings(testServerSettings)
    .settings(name := s"httpclient-backend-$proj")
    .jvmPlatform(
      scalaVersions = List(scala2_12, scala2_13) ++ (if (includeDotty) scala3 else Nil)
    )
    .dependsOn(httpClientBackend % compileAndTest)
}
```

should be there :) which artifact fails to be found?

**Comment by wix-andriusb** [comment]
I'm looking here:  https://mvnrepository.com/artifact/com.softwaremill.sttp.client/httpclient-backend
can't find 2.12, my understanding of maven is limited, maybe I fail to understand something

**Comment by adamw** [comment]
If you're looking for latest (3.1), that organization id is different: https://mvnrepository.com/artifact/com.softwaremill.sttp.client3/httpclient-backend

**Comment by wix-andriusb** [comment]
We are still using 2.2.8 here, need to investigate if I can do an upgrade, but that is another topic

**Comment by wix-andriusb** [comment]
I imagine you need to publish 2.2.8 builds for scala 2.12 on maven?

**Comment by adamw** [comment]
Yes, in progress, sonatype is slow for a change :)
And I'm releasing it for 2.2.9, the latest in 2.x

**Comment by adamw** [comment]
There you go: https://repo1.maven.org/maven2/com/softwaremill/sttp/client/httpclient-backend_2.12/
