### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by allquantor** [softwaremill/sttp#87]
Any plans to add it? There is no solid websocket client library that I know in Scala. Except of akka-http but that you are bound into akka-stream context.

**Comment by adamw** [comment]
Not sure - I didn't think about this yet really.

Although websockets kind of imply streaming, so wouldn't streams be the natural way to deal with them?

**Comment by mushtaq** [comment]
@adamw Does the new `FetchMonixBackend` allow to connect to websocket streams? 

We need to connect to a streaming server, which can support either server-sent-events (SSE) or websockets. Wondering if any of the current streaming backend works for that use case? Thanks.

**Comment by adamw** [comment]
@mushtaq No, the `FetchMonixBackend` allows making "normal" HTTP requests from a Scala.JS environment.

I didn't yet have time to think about a possible design of adding websockets support. But the streaming interface exposed by akka-http is really convenient to work with, so unless using Akka is a blocker, I'd go with that for now.

**Comment by mushtaq** [comment]
Thanks.

Akka-http is great, but we were hoping to use the same client from Scala.JS too where akka-http won't work.

**Comment by adamw** [comment]
Ah I see ... well we're not there yet for now, if that's at all possible (abstracting over streams). Though, that's probably what reactive streams is. But again, I'd have to research it more to come to any conclusions :)

**Comment by ehrlichja** [comment]
Any good options for websocket clients compatible with zio? I am looking at the websocket client in standard library of java 11, but it is taking a lot of thinking to try and reason how how to interface from the world of addHandler() to the world of zio.

**Comment by lbialy** [comment]
@ehrlichja fs2-http maybe?

**Comment by adamw** [comment]
Released in 2.0.0-M6
