### ISSUE TITLE
What is meaning of "Fully non-blocking" in Supported backends pages?

### ISSUE THREAD

**Issue by leedgdev** [softwaremill/sttp#872]
hi, i'm looking for Scala WebSocket Client which support Compression.

i think only backend that supports WebSocket Compression is  async-http-client and ok http.

by the way, i found there is "Fully non-blocking" keyword in below link.
[https://sttp.softwaremill.com/en/latest/backends/summary.html
](https://sttp.softwaremill.com/en/latest/backends/summary.html)

(see the blue square at the top-right corner)
![image](https://user-images.githubusercontent.com/68420663/108831719-dd09ee00-760d-11eb-9993-e16ee4555158.png)

Could you tell me meaning or URL that i can check or keyword which i can search for what is meaning of "Fully Non-Blocking"?

i thought okhttp/asnyc-http-client backend supports Non-Blocking I/O(Network), because they say they offer async api in their home page.

**Comment by adamw** [comment]
The OkHttp backends are blocking as they require that a streaming body be written synchronously via `OkHttpRequestBody` - so the stream is converted to an `Iterable`, with some blocking happening behind the scenes.

They might offer an async API, but still have a blocking implementation underneath.

AHC is fully non-blocking, *except* for saving responses as files, which happens synchronously (using blocking operations)

**Comment by adamw** [comment]
I don't know about compression & web sockets, but if you would find something out, please let us know!

**Comment by leedgdev** [comment]
thanks a lot.
for those who looking for websocket client with compression support.
akka-http : does not support yet.
okhttp, aync-http-client : supports
Java11 HttpClient : does not supports.

**Comment by adamw** [comment]
Thanks - maybe you could add a small section to https://sttp.softwaremill.com/en/latest/websockets.html with that information?
