### ISSUE TITLE
Provide constants for standard http values

### ISSUE THREAD

**Issue by jsw** [softwaremill/sttp#88]
It would be handy to have constants for standard http values like header names, status codes, content types, etc. 

Play exposes these via https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/http/StandardValues.scala

Have you considered providing these?

**Comment by adamw** [comment]
@jsw Yes, that's a good question - there's a handful of methods for specifying the content type, checking if the response is 2xx, 3xx etc., but that's about it. The akka-http model that @ktoso mentioned is tempting, but:

(a) working with the fully typed model and having to separately specify the `MediaType` & `ContentType` is sometimes a bit hard to work with
(b) I wouldn't want to copy-paste all that code, on the other making `core` dependent on `akka-http` isn't possible as well

so I'm on the fence here - not sure what would be the best way to go. I'm open to suggestions though :)

**Comment by jsw** [comment]
I agree that sttp should not depend on `akka-http-core`, especially as it brings in other dependencies. (@ktoso Thanks for linking to the model and informing that Play is moving towards it - good to know).

I also agree the `akka-http` model looks a bit heavy for sttp purpose.

What do you think of the Play approach? It is essentially a simple set of traits with constant Strings and Ints that are easy to stack together. This approach means the API doesn't have to change. Then it's easy to do

```
class TwitterClient extends Headers with ContentTypes {
   def getFeed() = sttp.header(Accept, Json)...
}
```

The only alternatives I see for users are
* Magic strings
* Building up their own set of constants
* Finding some library that contains these definitions (both Play and akka-http would be overkill to add to an app that doesn't otherwise contain them).

Many users might already be in the context of a Play or akka-http framework and can leverage that, but I'm thinking that the code that use sttp could be more portable and independent if they have their own definitions.

**Comment by adamw** [comment]
@jsw Yes, I suppose we could go with a hybrid approach. That is, keep methods that accept strings (if people would like to specify special custom headers) and provide a typed variant as well. Opaque types would be nice here ;)

I like the idea of grouping these in `trait`s, but maybe we could modify this a little, and have objects inside of the `sttp` package, `Headers` and `ContentTypes`? Then you you would do:

```
sttp.header(Headers.Accept, ContentTypes.Json)
sttp.contentType(ContentTypes.Json)
```

The `Header` trait (implemented e.g. by `Headers.Accept`) could have a type parameter specifying the allowed values (`String`s or `ContentType`s, for example), hence restricting what could be the second parameter of the `.header` method. What do you think?

**Comment by adamw** [comment]
Ah yes, a `trait`+`object` will definitely work.

You're right that while the hybrid approach would work for the create side (creating the request), it wouldn't for the read side (reading the response headers), so let's stick to `String`s

**Comment by jsw** [comment]
@adamw Sounds good. Would you like me to submit a PR or do you want to take this one? If I were to do it, it would look similar to the Play approach, though with `TitleCase` instead of `ALL_CAPS`, which I think is more idiomatic for scala constants.

**Comment by adamw** [comment]
@jsw if you could create a PR, that would be great! Of course, using `CamelCase` :)
