### ISSUE TITLE
[AsyncHttpClientZioBackend] Websocket receive blocks if payload contains a large amount of unicode characters

### ISSUE THREAD

**Issue by yangzai** [softwaremill/sttp#901]
Sample code:
```scala
import sttp.client3._
import sttp.client3.asynchttpclient.zio.{AsyncHttpClientZioBackend, sendR}
//import sttp.client3.httpclient.zio.{HttpClientZioBackend, sendR}
import zio._
import zio.console.Console.Service.live.putStrLn


object Client extends zio.App {
  val wsReq = basicRequest.get(uri"wss://echo.websocket.org") response asWebSocketAlways[Task, Unit] { ws =>
    for {
      _ <- putStrLn("start")
      _ <- ws.sendText('x'.toString * 3000) &> ws.receiveText().flatMap(putStrLn)
      _ <- ws.sendText('□'.toString * 3000) &> ws.receiveText().flatMap(putStrLn)
      _ <- ws.sendText('x'.toString * 3500) &> ws.receiveText().flatMap(putStrLn) //ascii chars are fine
      _ <- ws.sendText('□'.toString * 3500) &> ws.receiveText().flatMap(putStrLn) //blocks!
      _ <- putStrLn("end")
    } yield ()
  }
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    sendR(wsReq).provideCustomLayer(AsyncHttpClientZioBackend.layer()).exitCode
}
```

This happens with `AsyncHttpClientZioBackend`, everything works fine when I switch to `HttpClientZioBackend`. I've only tested with the ZIO backends so far.

**Comment by adamw** [comment]
When running this test locally, I got the following exception:

```
[info] - should send and receive unicode text messages *** FAILED ***
[info]   io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 10240 has been exceeded.
[info]   at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:426)
[info]   at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:286)
[info]   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
[info]   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
[info]   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[info]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[info]   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```

The default web socket frame size for async http client can be changed in the config, e.g. using `(new DefaultAsyncHttpClientConfig.Builder()).setWebSocketMaxFrameSize(...)`. I've amended the docs to include this information.

**Comment by yangzai** [comment]
> When running this test locally, I got the following exception:
> 
> ```
> [info] - should send and receive unicode text messages *** FAILED ***
> [info]   io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 10240 has been exceeded.
> [info]   at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:426)
> [info]   at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:286)
> [info]   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
> [info]   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
> [info]   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
> [info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> [info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> [info]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> [info]   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> [info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> ```
> 
> The default web socket frame size for async http client can be changed in the config, e.g. using `(new DefaultAsyncHttpClientConfig.Builder()).setWebSocketMaxFrameSize(...)`. I've amended the docs to include this information.

Verified to work with modified sample code:
```scala
import sttp.client3._
import sttp.client3.asynchttpclient.zio.{AsyncHttpClientZioBackend, sendR}
//import sttp.client3.httpclient.zio.{HttpClientZioBackend, sendR}
import zio._
import zio.console.Console.Service.live.putStrLn


object Client extends zio.App {
  val wsReq = basicRequest.get(uri"wss://echo.websocket.org") response asWebSocketAlways[Task, Unit] { ws =>
    for {
      _ <- putStrLn("start")
      _ <- ws.sendText('x'.toString * 3000) &> ws.receiveText().flatMap(putStrLn)
      _ <- ws.sendText('□'.toString * 3000) &> ws.receiveText().flatMap(putStrLn)
      _ <- ws.sendText('x'.toString * 3500) &> ws.receiveText().flatMap(putStrLn)
      _ <- ws.sendText('□'.toString * 3500) &> ws.receiveText().flatMap(putStrLn)
      _ <- putStrLn("end")
    } yield ()
  }
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    sendR(wsReq).provideCustomLayer(
      AsyncHttpClientZioBackend.layerUsingConfigBuilder(_.setWebSocketMaxFrameSize(20480)) //doubled default size
    ).exitCode
}
```
