### ISSUE TITLE
Issue with scala-sttp client generator for OpenAPI (via OpenAPI Generator)

### ISSUE THREAD

**Issue by manasbajaj** [softwaremill/sttp#903]
Hello sttp team

We are facing an issue with scala-sttp OpenAPI generator wherein additionalProperties specified for an Object are not being handled when the Scala client is generated. We have reported the issue in the OpenAPI generator and wanted to bring this to your attention.

https://github.com/OpenAPITools/openapi-generator/issues/8955

Any feedback/workaround you may provide would be much appreciated.

Thanks,
Manas

**Comment by ghostbuster91** [comment]
Hi,

Thanks, for letting us know.
I took some time to look into that issue, still one thing remains unclear to me. 
How do you coop with such objects later, I mean the objects from the hashMap? What do they actually represents in the runtime? Are they just unparsed json objects with types specific to the chosen library?

If they are primitives you could probably parse them in runtime to the jvm primitives, but that's a special case as in generally they can be arbitrary json objects. Should we parse the primitives and leave the complex objects untouched?

**Comment by ghostbuster91** [comment]
Now you can also try a dedicated sttp->openapi generator: https://github.com/ghostbuster91/sttp-openapi-generator/

**Comment by Pask423** [comment]
Closing as we are not able to fix this situation from sttp perspective.
