### ISSUE TITLE
backend.flatMap { backend => ??? } is highly confusing in the documentation

### ISSUE THREAD

**Issue by antonkulaga** [softwaremill/sttp#910]
You have a lot of examples with 
```
backend.flatMap { backend => ??? }
```
for many backend, however, it is not clear what to put instead of ??? there, I suggest that you give concrete examples

**Comment by antonkulaga** [comment]
for many backend, however, it is not clear what to put instead of ??? there, I suggest that you give concrete examples.
For client creation maybe as an example, you can provide code that is actually used by sttp to create clients? 
For zio runtime it is not really clear how I can either create or retrieve a zio runtime for sttp httpclient to be able to use runtime.unsafeRun(myrequest)?

**Comment by adamw** [comment]
Can you point to some specific places where you can see those examples? I can't find `backend.flatMap { backend => ??? }` in the source code or docs code

**Comment by Angel-O** [comment]
> You also provide "???" for http clients creation maybe as an example, you can provide code that is actually used by sttp to create clients?

@antonkulaga if you're using ZIO backend based on HTTP Client (Java 11+) you can build a client this way, but this isn't really `sttp` specific to my understanding.

```
  import java.net.http.HttpClient
  HttpClient.newHttpClient()
```

You can also avoid building a client yourself this way:

```
HttpClientZioBackend.managed().useNow => gives you a ZIO[R, E, SttpBackend] 
```

That will give you a backend with a client already assembled for you. You shouldn't worry about the runtime 

> For zio runtime it is not really clear how I can either create or retrieve a zio runtime for sttp httpclient to be able to use runtime.unsafeRun(myrequest)?

This might help, although I don't think this is the best way to do it

```
ZIO.runtime[Any].map(runtime => ....)
```

**Comment by antonkulaga** [comment]
Thanks guys. I figured out and rewrote my code with Zio. However, I would not be able to figure things out without your comment. Using flatMap all the time I want to use backend is quite counterintuitive, esp. for nonexerienced zio users

**Comment by adamw** [comment]
@antonkulaga Maybe you can pinpoint which parts of the docs did you read, and which ones caused the confusion? We can try to improve things, but we have to know where is the problem :) And where did you find the problematic `flatMap`s

**Comment by antonkulaga** [comment]
@adamw zio backend is highly inconsistent in comparison with other backends. For example:
```
 val backend: Task[SttpBackend[Task, ZioStreams with capabilities.WebSockets]] = HttpClientZioBackend()
  val backend: SttpBackend[Task, ZioStreams with capabilities.WebSockets] =  HttpClientZioBackend.usingClient(java.net.http.HttpClient.newBuilder().build())
```
in the first case you get Task[backend] which you have to flatmap all the time to get real backend in the second case you get proper backend to which you are accustomed from other sttp implementations. It caused me a lot of confusion.
Another thing I advice to give real examples instead of ???

**Comment by adamw** [comment]
Closing due to insufficient detail
