### ISSUE TITLE
Feature Request: add method to convert Request to RFC 2616 Format

### ISSUE THREAD

**Issue by phdoerfler** [softwaremill/sttp#956]
Ever since I ran into https://marketplace.visualstudio.com/items?itemName=humao.rest-client I have grown attached to writing HTTP requests like this:

```http
POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
```

From this format these requests can be easily executed in a dedicated REST client and converted into, e.g., curl command lines etc.

I'd love to see, e.g., a def `.toRfc2616` (or a catchier name) def in `Request` so one can convert a request into this format for easier debugging and experimenting with HTTP requests.

**Comment by ghostbuster91** [comment]
Sounds cool, shouldn't be a problem as we already has `toCurl` converter :)

**Comment by rojekp** [comment]
@phdoerfler, do you need support for `ByteArrayBody`, `ByteBufferBody`, `InputStreamBody` or `StreamBody`? If not, examples like that POST above should be ok for now.

**Comment by phdoerfler** [comment]
@rojekp @adamw thanks 🙂
