### ISSUE TITLE
opentracing: allow enriching any RequestT 

### ISSUE THREAD

**Issue by Krever** [softwaremill/sttp#960]
Right now [syntax exposed by OpenTracingBackend](https://github.com/softwaremill/sttp/blob/8dcc4878b9f400fb45c10d80e5878f5a3d605830/metrics/open-tracing-backend/src/main/scala/sttp/client3/opentracing/OpenTracingBackend.scala#L80) works only on `Request` and not any `RequestT`, preventing enriching the request before method/uri is set. 

Is there a reason for that?

**Comment by adamw** [comment]
No, I don't think so, probably someone wrote `Request`, it worked and that was it ;)
