### ISSUE TITLE
Incompatible Sttp Core versions between Sttp Client 2 and Sttp Client 3 ?

### ISSUE THREAD

**Issue by thiloplanz** [softwaremill/sttp#964]
We are in the middle of upgrading a code base from Sttp2 to Sttp3, and are now getting this error from the Sttp2 code.

```
java.lang.NoSuchMethodError: sttp.model.MediaType.copy(Ljava/lang/String;Ljava/lang/String;Lscala/Option;)Lsttp/model/MediaType;
at sttp.client.RequestT.withBasicBody(RequestT.scala:325)
at sttp.client.RequestTExtensions.body(RequestTExtensions.scala:35)
at sttp.client.RequestTExtensions.body$(RequestTExtensions.scala:34)
at sttp.client.RequestT.body(RequestT.scala:39)
```

It looks like Sttp Client 2 is not compatible with the version of Sttp Core that is pulled in by Sttp Client 3?

Versions used: `com.softwaremill.sttp.client:core:2.2.9` and `com.softwaremill.sttp.client3:core:3.3.0`

**Comment by thiloplanz** [comment]
I think this is caused by adding an extra field to

```
case class MediaType(mainType: String, subType: String, charset: Option[String] = None)
```

in `sttp-model:core`.

The version (model 1.3.x) used for Sttp Client 3.1.x still works, but with 3.2.x and above the case class (model 1.4.x) is missing the three argument copy constructor.

For now, we can revert to using 3.1.9.

I suppose the fix is to manually amend the missing copy method in the companion object or issue a patch for Sttp Client 2?

**Comment by adamw** [comment]
Yes this indeed did change. Let me try to do a release of sttp 2 with the new model

**Comment by adamw** [comment]
That's not that easy unfortunately. I'd need to change quite a lot of things in sttp 2 so that it compiles with the new model (and this also includes web socket etc. changes).

I suppose while you are migrating to from sttp2 to sttp3, you'll have to keep using 3.1.9. Hopefully that's not too big of a problem.

**Comment by thiloplanz** [comment]
> I suppose while you are migrating to from sttp2 to sttp3, you'll have to keep using 3.1.9. Hopefully that's not too big of a problem.

Yeah, that'll work for the moment. The plan is to migrate off sttp2 anyway (this is good motivation to speed that up), and it's not like we don't have to do similar version pinning for other things as well. Comes with the territory in Scala. Only problem might be if things like Caliban start pulling in (and depending on) Sttp3 beyond 3.1.9.

**Comment by adamw** [comment]
@thiloplanz I guess that's a common problem on the JVM in general :). Sorry for the trouble, it's hard to keep in mind all of the possible ways things might break. MiMA would probably be useful here, if you'd like to help setting it up for model/shared/client, contributions are always welcome :)

**Comment by adamw** [comment]
Closing as we can't do anything about this as the releases are out
