### ISSUE TITLE
.toCurl vs. form data with url encoding

### ISSUE THREAD

**Issue by phdoerfler** [softwaremill/sttp#965]
# Inequality of a request and its .toCurl representation

`someRequest.toCurl` produces:

```
-F 'text=Hi+I+can+convert+text+to+audio&language=english'
```

as part of its curl command line. Issuing said command line causes the used API to issue a Bad Gateway error.
However, sending the request with sttp works just fine.

Replacing the above fragment with:

```
--data 'text=Hi I can convert text to audio' --data 'language=english'
```

resolves the issue.

## Full example

```scala
def fetch(text: String) = {
  basicRequest
  .post(uri"https://text-to-speech16.p.rapidapi.com/tts/api/v1.3")
  .header("content-type", "application/x-www-form-urlencoded")
  .header("x-rapidapi-host", "text-to-speech16.p.rapidapi.com")
  .header("x-rapidapi-key", "heregoesyourapikey")
  .body(Map("text" -> text, "language" -> "english"))
  .response(asJson[Reply])
}
```

A `.toCurl` produces this defunct command line:

`curl -L --max-redirs 32 -X POST -H 'content-type: application/x-www-form-urlencoded' -H 'x-rapidapi-host: text-to-speech16.p.rapidapi.com' -H 'x-rapidapi-key: heregoesyourapikey' -H 'Content-Length: 52' -F 'text=Hi+I+can+convert+text+to+audio&language=english' 'https://text-to-speech16.p.rapidapi.com/tts/api/v1.3'`

With aforementioned change the issue is resolved:

`curl -L --max-redirs 32 -X POST -H 'content-type: application/x-www-form-urlencoded' -H 'x-rapidapi-host: text-to-speech16.p.rapidapi.com' -H 'x-rapidapi-key: heregoesyourapikey' -H 'Content-Length: 52' --data 'text=Hi I can convert text to audio' --data 'language=english' 'https://text-to-speech16.p.rapidapi.com/tts/api/v1.3'`

## Further Information

Looking at the tests I see that there is a clear distinction in how the curl command line is generated: In case of `content-type: application/x-www-form-urlencoded` the data is not passed as `--data` but instead as an urlencoded `-F`.
I'm not deep enough into HTTP to hazard a guess as to what is the correct behavior. I proposed that `--data` would be the right thing to use with `content-type: application/x-www-form-urlencoded` merely because the code generator of [rapidapi.com](https://rapidapi.com/gaurmanojkumar530/api/text-to-speech16) produced the following:

```shell
curl --request POST \
	--url https://text-to-speech16.p.rapidapi.com/tts/api/v1.3 \
	--header 'content-type: application/x-www-form-urlencoded' \
	--header 'x-rapidapi-host: text-to-speech16.p.rapidapi.com' \
	--header 'x-rapidapi-key: heregoesyourapikey' \
	--data 'text=Hi I can convert text to audio' \
	--data language=english
```

And this does indeed work correctly, whereas the curl command line produced by sttp does not, even though the same request that generated the defunct curl call does work when used without `.toCurl`.

@ghostbuster91 Care to shine some light on this?

**Comment by phdoerfler** [comment]
This may or may not be related to: https://github.com/softwaremill/sttp/issues/220#issuecomment-807175141

**Comment by ghostbuster91** [comment]
Hi, thanks for the detailed investigation. 

It seems that it is a bug and we should use `--data` instead of `-F`(`--form`). The latter one is used for sending data as a multipart form, it even sets `contentType` header to `multipart/form-data`. As we are overrding that header manually this results in broken curl request.

> I'm not deep enough into HTTP 

Neither do I, hence the bug :) 

We can observe the difference in payload being sent using `--trace-ascii /dev/stdout` option.
```
curl --trace-ascii /dev/stdout --request  POST \
        --url https://text-to-speech16.p.rapidapi.com/tts/api/v1.3 \
        --header 'content-type: application/x-www-form-urlencoded' \
        --header 'x-rapidapi-host: text-to-speech16.p.rapidapi.com' \
        --header 'x-rapidapi-key: heregoesyourapikey' \
        --data 'text=Hi I can convert text to audio' \
        --data language=englis
```

produces following body:
```
00f1: Content-Length: 52
0105:
=> Send data, 52 bytes (0x34)
0000: text=Hi I can convert text to audio&language=english
== Info: upload completely sent off: 52 out of 52 bytes
<= Recv header, 24 bytes (0x18)
```

while `--form` produces:
```
00c0: Content-Length: 275
00d5: Content-Type: application/x-www-form-urlencoded; boundary=------
0115: ------------------22497e1d5c69eaf4
0139:
=> Send data, 275 bytes (0x113)
0000: --------------------------22497e1d5c69eaf4
002c: Content-Disposition: attachment; name="text"
005a:
005c: Hi I can convert text to audio
007c: --------------------------22497e1d5c69eaf4
00a8: Content-Disposition: attachment; name="language"
00da:
00dc: english
00e5: --------------------------22497e1d5c69eaf4--
== Info: We are completely uploaded and fine
<= Recv header, 24 bytes (0x18)
```
