### ISSUE TITLE
Scala 3 support dropped from circe interop

### ISSUE THREAD

**Issue by ghostdogpr** [softwaremill/sttp#982]
Version 3.3.3 of circe artifact doesn't have Scala 3 support: https://mvnrepository.com/artifact/com.softwaremill.sttp.client3/circe

Maybe that's because circe was not ready yet? Is it possible to do another release now that circe supports it? 🙏

**Comment by adamw** [comment]
Yes, that's already in master, release coming soon :)

I think we're still missing zio-nio and monix-nio to have the whole package

**Comment by adamw** [comment]
Should be done in 3.3.4 :)

**Comment by ghostdogpr** [comment]
@adamw it looks like it's still missing for Scala.js. It was supported until 3.0.0-RC3 (https://repo1.maven.org/maven2/com/softwaremill/sttp/client3/circe_sjs1_3.0.0-RC3/ but no https://repo1.maven.org/maven2/com/softwaremill/sttp/client3/circe_sjs1_3.0.0/ )

**Comment by adamw** [comment]
Ah ... there's only circe-core released for scala3/js, but not circe-generic (which is used in tests): https://repo1.maven.org/maven2/io/circe/

**Comment by ghostdogpr** [comment]
Argh, you're right 😢

**Comment by ghostdogpr** [comment]
Turns out I only needed `circeBodySerializer` which is a one-liner so that was easy to workaround 😄
