### ISSUE TITLE
httpclient-backend-zio_3 missing?

### ISSUE THREAD

**Issue by francisdb** [softwaremill/sttp#985]
https://repo1.maven.org/maven2/com/softwaremill/sttp/client3/httpclient-backend-zio_3/3.3.4/httpclient-backend-zio_3-3.3.4.pom

I see the other `*-backend-zio_3` artifacts are available, any reason for this one to be missing?

**Comment by adamw** [comment]
It uses zio-nio, see: https://github.com/zio/zio-nio/issues/352

**Comment by adamw** [comment]
Released in 3.3.5
